/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NBIOT-RRC-Definitions"
 * 	found in "../../Skeletons/ASN_files/LTE/lte-rrc-19.0.0.asn1"
 * 	`asn1c -fcompound-names -pdu=all -gen-PER`
 */

#include "NTN-Parameters-NB-v1800.h"

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static asn_oer_constraints_t asn_OER_type_ntn_LocationBasedMeasTrigger_EFC_r18_constr_2 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_ntn_LocationBasedMeasTrigger_EFC_r18_constr_2 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 0,  0,  0,  0 }	/* (0..0) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_ntn_LocationBasedMeasTrigger_EMC_r18_constr_4 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_ntn_LocationBasedMeasTrigger_EMC_r18_constr_4 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 0,  0,  0,  0 }	/* (0..0) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_ntn_TimeBasedMeasTrigger_r18_constr_6 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_ntn_TimeBasedMeasTrigger_r18_constr_6 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 0,  0,  0,  0 }	/* (0..0) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_ntn_RRC_HarqDisableSingleTB_r18_constr_8 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_ntn_RRC_HarqDisableSingleTB_r18_constr_8 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 0,  0,  0,  0 }	/* (0..0) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_ntn_OverriddenHarqDisableSingleTB_r18_constr_10 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_ntn_OverriddenHarqDisableSingleTB_r18_constr_10 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 0,  0,  0,  0 }	/* (0..0) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_ntn_DCI_HarqDisableSingleTB_r18_constr_12 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_ntn_DCI_HarqDisableSingleTB_r18_constr_12 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 0,  0,  0,  0 }	/* (0..0) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_ntn_RRC_HarqDisableMultiTB_r18_constr_14 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_ntn_RRC_HarqDisableMultiTB_r18_constr_14 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 0,  0,  0,  0 }	/* (0..0) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_ntn_OverriddenHarqDisableMultiTB_r18_constr_16 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_ntn_OverriddenHarqDisableMultiTB_r18_constr_16 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 0,  0,  0,  0 }	/* (0..0) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_ntn_DCI_HarqDisableMultiTB_r18_constr_18 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_ntn_DCI_HarqDisableMultiTB_r18_constr_18 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 0,  0,  0,  0 }	/* (0..0) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_ntn_UplinkHarq_ModeB_SingleTB_r18_constr_20 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_ntn_UplinkHarq_ModeB_SingleTB_r18_constr_20 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 0,  0,  0,  0 }	/* (0..0) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_ntn_UplinkHarq_ModeB_MultiTB_r18_constr_22 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_ntn_UplinkHarq_ModeB_MultiTB_r18_constr_22 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 0,  0,  0,  0 }	/* (0..0) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_ntn_HarqEnhScenarioSupport_r18_constr_24 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_ntn_HarqEnhScenarioSupport_r18_constr_24 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_ntn_Triggered_GNSS_Fix_r18_constr_27 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_ntn_Triggered_GNSS_Fix_r18_constr_27 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 0,  0,  0,  0 }	/* (0..0) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_ntn_Autonomous_GNSS_Fix_r18_constr_29 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_ntn_Autonomous_GNSS_Fix_r18_constr_29 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 0,  0,  0,  0 }	/* (0..0) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_ntn_UplinkTxExtension_r18_constr_31 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_ntn_UplinkTxExtension_r18_constr_31 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 0,  0,  0,  0 }	/* (0..0) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_ntn_GNSS_EnhScenarioSupport_r18_constr_33 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_ntn_GNSS_EnhScenarioSupport_r18_constr_33 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static const asn_INTEGER_enum_map_t asn_MAP_ntn_LocationBasedMeasTrigger_EFC_r18_value2enum_2[] = {
	{ 0,	9,	"supported" }
};
static const unsigned int asn_MAP_ntn_LocationBasedMeasTrigger_EFC_r18_enum2value_2[] = {
	0	/* supported(0) */
};
static const asn_INTEGER_specifics_t asn_SPC_ntn_LocationBasedMeasTrigger_EFC_r18_specs_2 = {
	asn_MAP_ntn_LocationBasedMeasTrigger_EFC_r18_value2enum_2,	/* "tag" => N; sorted by tag */
	asn_MAP_ntn_LocationBasedMeasTrigger_EFC_r18_enum2value_2,	/* N => "tag"; sorted by N */
	1,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_ntn_LocationBasedMeasTrigger_EFC_r18_tags_2[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ntn_LocationBasedMeasTrigger_EFC_r18_2 = {
	"ntn-LocationBasedMeasTrigger-EFC-r18",
	"ntn-LocationBasedMeasTrigger-EFC-r18",
	&asn_OP_NativeEnumerated,
	asn_DEF_ntn_LocationBasedMeasTrigger_EFC_r18_tags_2,
	sizeof(asn_DEF_ntn_LocationBasedMeasTrigger_EFC_r18_tags_2)
		/sizeof(asn_DEF_ntn_LocationBasedMeasTrigger_EFC_r18_tags_2[0]) - 1, /* 1 */
	asn_DEF_ntn_LocationBasedMeasTrigger_EFC_r18_tags_2,	/* Same as above */
	sizeof(asn_DEF_ntn_LocationBasedMeasTrigger_EFC_r18_tags_2)
		/sizeof(asn_DEF_ntn_LocationBasedMeasTrigger_EFC_r18_tags_2[0]), /* 2 */
	{ &asn_OER_type_ntn_LocationBasedMeasTrigger_EFC_r18_constr_2, &asn_PER_type_ntn_LocationBasedMeasTrigger_EFC_r18_constr_2, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_ntn_LocationBasedMeasTrigger_EFC_r18_specs_2	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_ntn_LocationBasedMeasTrigger_EMC_r18_value2enum_4[] = {
	{ 0,	9,	"supported" }
};
static const unsigned int asn_MAP_ntn_LocationBasedMeasTrigger_EMC_r18_enum2value_4[] = {
	0	/* supported(0) */
};
static const asn_INTEGER_specifics_t asn_SPC_ntn_LocationBasedMeasTrigger_EMC_r18_specs_4 = {
	asn_MAP_ntn_LocationBasedMeasTrigger_EMC_r18_value2enum_4,	/* "tag" => N; sorted by tag */
	asn_MAP_ntn_LocationBasedMeasTrigger_EMC_r18_enum2value_4,	/* N => "tag"; sorted by N */
	1,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_ntn_LocationBasedMeasTrigger_EMC_r18_tags_4[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ntn_LocationBasedMeasTrigger_EMC_r18_4 = {
	"ntn-LocationBasedMeasTrigger-EMC-r18",
	"ntn-LocationBasedMeasTrigger-EMC-r18",
	&asn_OP_NativeEnumerated,
	asn_DEF_ntn_LocationBasedMeasTrigger_EMC_r18_tags_4,
	sizeof(asn_DEF_ntn_LocationBasedMeasTrigger_EMC_r18_tags_4)
		/sizeof(asn_DEF_ntn_LocationBasedMeasTrigger_EMC_r18_tags_4[0]) - 1, /* 1 */
	asn_DEF_ntn_LocationBasedMeasTrigger_EMC_r18_tags_4,	/* Same as above */
	sizeof(asn_DEF_ntn_LocationBasedMeasTrigger_EMC_r18_tags_4)
		/sizeof(asn_DEF_ntn_LocationBasedMeasTrigger_EMC_r18_tags_4[0]), /* 2 */
	{ &asn_OER_type_ntn_LocationBasedMeasTrigger_EMC_r18_constr_4, &asn_PER_type_ntn_LocationBasedMeasTrigger_EMC_r18_constr_4, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_ntn_LocationBasedMeasTrigger_EMC_r18_specs_4	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_ntn_TimeBasedMeasTrigger_r18_value2enum_6[] = {
	{ 0,	9,	"supported" }
};
static const unsigned int asn_MAP_ntn_TimeBasedMeasTrigger_r18_enum2value_6[] = {
	0	/* supported(0) */
};
static const asn_INTEGER_specifics_t asn_SPC_ntn_TimeBasedMeasTrigger_r18_specs_6 = {
	asn_MAP_ntn_TimeBasedMeasTrigger_r18_value2enum_6,	/* "tag" => N; sorted by tag */
	asn_MAP_ntn_TimeBasedMeasTrigger_r18_enum2value_6,	/* N => "tag"; sorted by N */
	1,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_ntn_TimeBasedMeasTrigger_r18_tags_6[] = {
	(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ntn_TimeBasedMeasTrigger_r18_6 = {
	"ntn-TimeBasedMeasTrigger-r18",
	"ntn-TimeBasedMeasTrigger-r18",
	&asn_OP_NativeEnumerated,
	asn_DEF_ntn_TimeBasedMeasTrigger_r18_tags_6,
	sizeof(asn_DEF_ntn_TimeBasedMeasTrigger_r18_tags_6)
		/sizeof(asn_DEF_ntn_TimeBasedMeasTrigger_r18_tags_6[0]) - 1, /* 1 */
	asn_DEF_ntn_TimeBasedMeasTrigger_r18_tags_6,	/* Same as above */
	sizeof(asn_DEF_ntn_TimeBasedMeasTrigger_r18_tags_6)
		/sizeof(asn_DEF_ntn_TimeBasedMeasTrigger_r18_tags_6[0]), /* 2 */
	{ &asn_OER_type_ntn_TimeBasedMeasTrigger_r18_constr_6, &asn_PER_type_ntn_TimeBasedMeasTrigger_r18_constr_6, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_ntn_TimeBasedMeasTrigger_r18_specs_6	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_ntn_RRC_HarqDisableSingleTB_r18_value2enum_8[] = {
	{ 0,	9,	"supported" }
};
static const unsigned int asn_MAP_ntn_RRC_HarqDisableSingleTB_r18_enum2value_8[] = {
	0	/* supported(0) */
};
static const asn_INTEGER_specifics_t asn_SPC_ntn_RRC_HarqDisableSingleTB_r18_specs_8 = {
	asn_MAP_ntn_RRC_HarqDisableSingleTB_r18_value2enum_8,	/* "tag" => N; sorted by tag */
	asn_MAP_ntn_RRC_HarqDisableSingleTB_r18_enum2value_8,	/* N => "tag"; sorted by N */
	1,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_ntn_RRC_HarqDisableSingleTB_r18_tags_8[] = {
	(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ntn_RRC_HarqDisableSingleTB_r18_8 = {
	"ntn-RRC-HarqDisableSingleTB-r18",
	"ntn-RRC-HarqDisableSingleTB-r18",
	&asn_OP_NativeEnumerated,
	asn_DEF_ntn_RRC_HarqDisableSingleTB_r18_tags_8,
	sizeof(asn_DEF_ntn_RRC_HarqDisableSingleTB_r18_tags_8)
		/sizeof(asn_DEF_ntn_RRC_HarqDisableSingleTB_r18_tags_8[0]) - 1, /* 1 */
	asn_DEF_ntn_RRC_HarqDisableSingleTB_r18_tags_8,	/* Same as above */
	sizeof(asn_DEF_ntn_RRC_HarqDisableSingleTB_r18_tags_8)
		/sizeof(asn_DEF_ntn_RRC_HarqDisableSingleTB_r18_tags_8[0]), /* 2 */
	{ &asn_OER_type_ntn_RRC_HarqDisableSingleTB_r18_constr_8, &asn_PER_type_ntn_RRC_HarqDisableSingleTB_r18_constr_8, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_ntn_RRC_HarqDisableSingleTB_r18_specs_8	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_ntn_OverriddenHarqDisableSingleTB_r18_value2enum_10[] = {
	{ 0,	9,	"supported" }
};
static const unsigned int asn_MAP_ntn_OverriddenHarqDisableSingleTB_r18_enum2value_10[] = {
	0	/* supported(0) */
};
static const asn_INTEGER_specifics_t asn_SPC_ntn_OverriddenHarqDisableSingleTB_r18_specs_10 = {
	asn_MAP_ntn_OverriddenHarqDisableSingleTB_r18_value2enum_10,	/* "tag" => N; sorted by tag */
	asn_MAP_ntn_OverriddenHarqDisableSingleTB_r18_enum2value_10,	/* N => "tag"; sorted by N */
	1,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_ntn_OverriddenHarqDisableSingleTB_r18_tags_10[] = {
	(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ntn_OverriddenHarqDisableSingleTB_r18_10 = {
	"ntn-OverriddenHarqDisableSingleTB-r18",
	"ntn-OverriddenHarqDisableSingleTB-r18",
	&asn_OP_NativeEnumerated,
	asn_DEF_ntn_OverriddenHarqDisableSingleTB_r18_tags_10,
	sizeof(asn_DEF_ntn_OverriddenHarqDisableSingleTB_r18_tags_10)
		/sizeof(asn_DEF_ntn_OverriddenHarqDisableSingleTB_r18_tags_10[0]) - 1, /* 1 */
	asn_DEF_ntn_OverriddenHarqDisableSingleTB_r18_tags_10,	/* Same as above */
	sizeof(asn_DEF_ntn_OverriddenHarqDisableSingleTB_r18_tags_10)
		/sizeof(asn_DEF_ntn_OverriddenHarqDisableSingleTB_r18_tags_10[0]), /* 2 */
	{ &asn_OER_type_ntn_OverriddenHarqDisableSingleTB_r18_constr_10, &asn_PER_type_ntn_OverriddenHarqDisableSingleTB_r18_constr_10, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_ntn_OverriddenHarqDisableSingleTB_r18_specs_10	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_ntn_DCI_HarqDisableSingleTB_r18_value2enum_12[] = {
	{ 0,	9,	"supported" }
};
static const unsigned int asn_MAP_ntn_DCI_HarqDisableSingleTB_r18_enum2value_12[] = {
	0	/* supported(0) */
};
static const asn_INTEGER_specifics_t asn_SPC_ntn_DCI_HarqDisableSingleTB_r18_specs_12 = {
	asn_MAP_ntn_DCI_HarqDisableSingleTB_r18_value2enum_12,	/* "tag" => N; sorted by tag */
	asn_MAP_ntn_DCI_HarqDisableSingleTB_r18_enum2value_12,	/* N => "tag"; sorted by N */
	1,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_ntn_DCI_HarqDisableSingleTB_r18_tags_12[] = {
	(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ntn_DCI_HarqDisableSingleTB_r18_12 = {
	"ntn-DCI-HarqDisableSingleTB-r18",
	"ntn-DCI-HarqDisableSingleTB-r18",
	&asn_OP_NativeEnumerated,
	asn_DEF_ntn_DCI_HarqDisableSingleTB_r18_tags_12,
	sizeof(asn_DEF_ntn_DCI_HarqDisableSingleTB_r18_tags_12)
		/sizeof(asn_DEF_ntn_DCI_HarqDisableSingleTB_r18_tags_12[0]) - 1, /* 1 */
	asn_DEF_ntn_DCI_HarqDisableSingleTB_r18_tags_12,	/* Same as above */
	sizeof(asn_DEF_ntn_DCI_HarqDisableSingleTB_r18_tags_12)
		/sizeof(asn_DEF_ntn_DCI_HarqDisableSingleTB_r18_tags_12[0]), /* 2 */
	{ &asn_OER_type_ntn_DCI_HarqDisableSingleTB_r18_constr_12, &asn_PER_type_ntn_DCI_HarqDisableSingleTB_r18_constr_12, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_ntn_DCI_HarqDisableSingleTB_r18_specs_12	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_ntn_RRC_HarqDisableMultiTB_r18_value2enum_14[] = {
	{ 0,	9,	"supported" }
};
static const unsigned int asn_MAP_ntn_RRC_HarqDisableMultiTB_r18_enum2value_14[] = {
	0	/* supported(0) */
};
static const asn_INTEGER_specifics_t asn_SPC_ntn_RRC_HarqDisableMultiTB_r18_specs_14 = {
	asn_MAP_ntn_RRC_HarqDisableMultiTB_r18_value2enum_14,	/* "tag" => N; sorted by tag */
	asn_MAP_ntn_RRC_HarqDisableMultiTB_r18_enum2value_14,	/* N => "tag"; sorted by N */
	1,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_ntn_RRC_HarqDisableMultiTB_r18_tags_14[] = {
	(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ntn_RRC_HarqDisableMultiTB_r18_14 = {
	"ntn-RRC-HarqDisableMultiTB-r18",
	"ntn-RRC-HarqDisableMultiTB-r18",
	&asn_OP_NativeEnumerated,
	asn_DEF_ntn_RRC_HarqDisableMultiTB_r18_tags_14,
	sizeof(asn_DEF_ntn_RRC_HarqDisableMultiTB_r18_tags_14)
		/sizeof(asn_DEF_ntn_RRC_HarqDisableMultiTB_r18_tags_14[0]) - 1, /* 1 */
	asn_DEF_ntn_RRC_HarqDisableMultiTB_r18_tags_14,	/* Same as above */
	sizeof(asn_DEF_ntn_RRC_HarqDisableMultiTB_r18_tags_14)
		/sizeof(asn_DEF_ntn_RRC_HarqDisableMultiTB_r18_tags_14[0]), /* 2 */
	{ &asn_OER_type_ntn_RRC_HarqDisableMultiTB_r18_constr_14, &asn_PER_type_ntn_RRC_HarqDisableMultiTB_r18_constr_14, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_ntn_RRC_HarqDisableMultiTB_r18_specs_14	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_ntn_OverriddenHarqDisableMultiTB_r18_value2enum_16[] = {
	{ 0,	9,	"supported" }
};
static const unsigned int asn_MAP_ntn_OverriddenHarqDisableMultiTB_r18_enum2value_16[] = {
	0	/* supported(0) */
};
static const asn_INTEGER_specifics_t asn_SPC_ntn_OverriddenHarqDisableMultiTB_r18_specs_16 = {
	asn_MAP_ntn_OverriddenHarqDisableMultiTB_r18_value2enum_16,	/* "tag" => N; sorted by tag */
	asn_MAP_ntn_OverriddenHarqDisableMultiTB_r18_enum2value_16,	/* N => "tag"; sorted by N */
	1,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_ntn_OverriddenHarqDisableMultiTB_r18_tags_16[] = {
	(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ntn_OverriddenHarqDisableMultiTB_r18_16 = {
	"ntn-OverriddenHarqDisableMultiTB-r18",
	"ntn-OverriddenHarqDisableMultiTB-r18",
	&asn_OP_NativeEnumerated,
	asn_DEF_ntn_OverriddenHarqDisableMultiTB_r18_tags_16,
	sizeof(asn_DEF_ntn_OverriddenHarqDisableMultiTB_r18_tags_16)
		/sizeof(asn_DEF_ntn_OverriddenHarqDisableMultiTB_r18_tags_16[0]) - 1, /* 1 */
	asn_DEF_ntn_OverriddenHarqDisableMultiTB_r18_tags_16,	/* Same as above */
	sizeof(asn_DEF_ntn_OverriddenHarqDisableMultiTB_r18_tags_16)
		/sizeof(asn_DEF_ntn_OverriddenHarqDisableMultiTB_r18_tags_16[0]), /* 2 */
	{ &asn_OER_type_ntn_OverriddenHarqDisableMultiTB_r18_constr_16, &asn_PER_type_ntn_OverriddenHarqDisableMultiTB_r18_constr_16, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_ntn_OverriddenHarqDisableMultiTB_r18_specs_16	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_ntn_DCI_HarqDisableMultiTB_r18_value2enum_18[] = {
	{ 0,	9,	"supported" }
};
static const unsigned int asn_MAP_ntn_DCI_HarqDisableMultiTB_r18_enum2value_18[] = {
	0	/* supported(0) */
};
static const asn_INTEGER_specifics_t asn_SPC_ntn_DCI_HarqDisableMultiTB_r18_specs_18 = {
	asn_MAP_ntn_DCI_HarqDisableMultiTB_r18_value2enum_18,	/* "tag" => N; sorted by tag */
	asn_MAP_ntn_DCI_HarqDisableMultiTB_r18_enum2value_18,	/* N => "tag"; sorted by N */
	1,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_ntn_DCI_HarqDisableMultiTB_r18_tags_18[] = {
	(ASN_TAG_CLASS_CONTEXT | (8 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ntn_DCI_HarqDisableMultiTB_r18_18 = {
	"ntn-DCI-HarqDisableMultiTB-r18",
	"ntn-DCI-HarqDisableMultiTB-r18",
	&asn_OP_NativeEnumerated,
	asn_DEF_ntn_DCI_HarqDisableMultiTB_r18_tags_18,
	sizeof(asn_DEF_ntn_DCI_HarqDisableMultiTB_r18_tags_18)
		/sizeof(asn_DEF_ntn_DCI_HarqDisableMultiTB_r18_tags_18[0]) - 1, /* 1 */
	asn_DEF_ntn_DCI_HarqDisableMultiTB_r18_tags_18,	/* Same as above */
	sizeof(asn_DEF_ntn_DCI_HarqDisableMultiTB_r18_tags_18)
		/sizeof(asn_DEF_ntn_DCI_HarqDisableMultiTB_r18_tags_18[0]), /* 2 */
	{ &asn_OER_type_ntn_DCI_HarqDisableMultiTB_r18_constr_18, &asn_PER_type_ntn_DCI_HarqDisableMultiTB_r18_constr_18, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_ntn_DCI_HarqDisableMultiTB_r18_specs_18	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_ntn_UplinkHarq_ModeB_SingleTB_r18_value2enum_20[] = {
	{ 0,	9,	"supported" }
};
static const unsigned int asn_MAP_ntn_UplinkHarq_ModeB_SingleTB_r18_enum2value_20[] = {
	0	/* supported(0) */
};
static const asn_INTEGER_specifics_t asn_SPC_ntn_UplinkHarq_ModeB_SingleTB_r18_specs_20 = {
	asn_MAP_ntn_UplinkHarq_ModeB_SingleTB_r18_value2enum_20,	/* "tag" => N; sorted by tag */
	asn_MAP_ntn_UplinkHarq_ModeB_SingleTB_r18_enum2value_20,	/* N => "tag"; sorted by N */
	1,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_ntn_UplinkHarq_ModeB_SingleTB_r18_tags_20[] = {
	(ASN_TAG_CLASS_CONTEXT | (9 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ntn_UplinkHarq_ModeB_SingleTB_r18_20 = {
	"ntn-UplinkHarq-ModeB-SingleTB-r18",
	"ntn-UplinkHarq-ModeB-SingleTB-r18",
	&asn_OP_NativeEnumerated,
	asn_DEF_ntn_UplinkHarq_ModeB_SingleTB_r18_tags_20,
	sizeof(asn_DEF_ntn_UplinkHarq_ModeB_SingleTB_r18_tags_20)
		/sizeof(asn_DEF_ntn_UplinkHarq_ModeB_SingleTB_r18_tags_20[0]) - 1, /* 1 */
	asn_DEF_ntn_UplinkHarq_ModeB_SingleTB_r18_tags_20,	/* Same as above */
	sizeof(asn_DEF_ntn_UplinkHarq_ModeB_SingleTB_r18_tags_20)
		/sizeof(asn_DEF_ntn_UplinkHarq_ModeB_SingleTB_r18_tags_20[0]), /* 2 */
	{ &asn_OER_type_ntn_UplinkHarq_ModeB_SingleTB_r18_constr_20, &asn_PER_type_ntn_UplinkHarq_ModeB_SingleTB_r18_constr_20, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_ntn_UplinkHarq_ModeB_SingleTB_r18_specs_20	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_ntn_UplinkHarq_ModeB_MultiTB_r18_value2enum_22[] = {
	{ 0,	9,	"supported" }
};
static const unsigned int asn_MAP_ntn_UplinkHarq_ModeB_MultiTB_r18_enum2value_22[] = {
	0	/* supported(0) */
};
static const asn_INTEGER_specifics_t asn_SPC_ntn_UplinkHarq_ModeB_MultiTB_r18_specs_22 = {
	asn_MAP_ntn_UplinkHarq_ModeB_MultiTB_r18_value2enum_22,	/* "tag" => N; sorted by tag */
	asn_MAP_ntn_UplinkHarq_ModeB_MultiTB_r18_enum2value_22,	/* N => "tag"; sorted by N */
	1,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_ntn_UplinkHarq_ModeB_MultiTB_r18_tags_22[] = {
	(ASN_TAG_CLASS_CONTEXT | (10 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ntn_UplinkHarq_ModeB_MultiTB_r18_22 = {
	"ntn-UplinkHarq-ModeB-MultiTB-r18",
	"ntn-UplinkHarq-ModeB-MultiTB-r18",
	&asn_OP_NativeEnumerated,
	asn_DEF_ntn_UplinkHarq_ModeB_MultiTB_r18_tags_22,
	sizeof(asn_DEF_ntn_UplinkHarq_ModeB_MultiTB_r18_tags_22)
		/sizeof(asn_DEF_ntn_UplinkHarq_ModeB_MultiTB_r18_tags_22[0]) - 1, /* 1 */
	asn_DEF_ntn_UplinkHarq_ModeB_MultiTB_r18_tags_22,	/* Same as above */
	sizeof(asn_DEF_ntn_UplinkHarq_ModeB_MultiTB_r18_tags_22)
		/sizeof(asn_DEF_ntn_UplinkHarq_ModeB_MultiTB_r18_tags_22[0]), /* 2 */
	{ &asn_OER_type_ntn_UplinkHarq_ModeB_MultiTB_r18_constr_22, &asn_PER_type_ntn_UplinkHarq_ModeB_MultiTB_r18_constr_22, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_ntn_UplinkHarq_ModeB_MultiTB_r18_specs_22	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_ntn_HarqEnhScenarioSupport_r18_value2enum_24[] = {
	{ 0,	4,	"ngso" },
	{ 1,	3,	"gso" }
};
static const unsigned int asn_MAP_ntn_HarqEnhScenarioSupport_r18_enum2value_24[] = {
	1,	/* gso(1) */
	0	/* ngso(0) */
};
static const asn_INTEGER_specifics_t asn_SPC_ntn_HarqEnhScenarioSupport_r18_specs_24 = {
	asn_MAP_ntn_HarqEnhScenarioSupport_r18_value2enum_24,	/* "tag" => N; sorted by tag */
	asn_MAP_ntn_HarqEnhScenarioSupport_r18_enum2value_24,	/* N => "tag"; sorted by N */
	2,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_ntn_HarqEnhScenarioSupport_r18_tags_24[] = {
	(ASN_TAG_CLASS_CONTEXT | (11 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ntn_HarqEnhScenarioSupport_r18_24 = {
	"ntn-HarqEnhScenarioSupport-r18",
	"ntn-HarqEnhScenarioSupport-r18",
	&asn_OP_NativeEnumerated,
	asn_DEF_ntn_HarqEnhScenarioSupport_r18_tags_24,
	sizeof(asn_DEF_ntn_HarqEnhScenarioSupport_r18_tags_24)
		/sizeof(asn_DEF_ntn_HarqEnhScenarioSupport_r18_tags_24[0]) - 1, /* 1 */
	asn_DEF_ntn_HarqEnhScenarioSupport_r18_tags_24,	/* Same as above */
	sizeof(asn_DEF_ntn_HarqEnhScenarioSupport_r18_tags_24)
		/sizeof(asn_DEF_ntn_HarqEnhScenarioSupport_r18_tags_24[0]), /* 2 */
	{ &asn_OER_type_ntn_HarqEnhScenarioSupport_r18_constr_24, &asn_PER_type_ntn_HarqEnhScenarioSupport_r18_constr_24, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_ntn_HarqEnhScenarioSupport_r18_specs_24	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_ntn_Triggered_GNSS_Fix_r18_value2enum_27[] = {
	{ 0,	9,	"supported" }
};
static const unsigned int asn_MAP_ntn_Triggered_GNSS_Fix_r18_enum2value_27[] = {
	0	/* supported(0) */
};
static const asn_INTEGER_specifics_t asn_SPC_ntn_Triggered_GNSS_Fix_r18_specs_27 = {
	asn_MAP_ntn_Triggered_GNSS_Fix_r18_value2enum_27,	/* "tag" => N; sorted by tag */
	asn_MAP_ntn_Triggered_GNSS_Fix_r18_enum2value_27,	/* N => "tag"; sorted by N */
	1,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_ntn_Triggered_GNSS_Fix_r18_tags_27[] = {
	(ASN_TAG_CLASS_CONTEXT | (12 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ntn_Triggered_GNSS_Fix_r18_27 = {
	"ntn-Triggered-GNSS-Fix-r18",
	"ntn-Triggered-GNSS-Fix-r18",
	&asn_OP_NativeEnumerated,
	asn_DEF_ntn_Triggered_GNSS_Fix_r18_tags_27,
	sizeof(asn_DEF_ntn_Triggered_GNSS_Fix_r18_tags_27)
		/sizeof(asn_DEF_ntn_Triggered_GNSS_Fix_r18_tags_27[0]) - 1, /* 1 */
	asn_DEF_ntn_Triggered_GNSS_Fix_r18_tags_27,	/* Same as above */
	sizeof(asn_DEF_ntn_Triggered_GNSS_Fix_r18_tags_27)
		/sizeof(asn_DEF_ntn_Triggered_GNSS_Fix_r18_tags_27[0]), /* 2 */
	{ &asn_OER_type_ntn_Triggered_GNSS_Fix_r18_constr_27, &asn_PER_type_ntn_Triggered_GNSS_Fix_r18_constr_27, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_ntn_Triggered_GNSS_Fix_r18_specs_27	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_ntn_Autonomous_GNSS_Fix_r18_value2enum_29[] = {
	{ 0,	9,	"supported" }
};
static const unsigned int asn_MAP_ntn_Autonomous_GNSS_Fix_r18_enum2value_29[] = {
	0	/* supported(0) */
};
static const asn_INTEGER_specifics_t asn_SPC_ntn_Autonomous_GNSS_Fix_r18_specs_29 = {
	asn_MAP_ntn_Autonomous_GNSS_Fix_r18_value2enum_29,	/* "tag" => N; sorted by tag */
	asn_MAP_ntn_Autonomous_GNSS_Fix_r18_enum2value_29,	/* N => "tag"; sorted by N */
	1,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_ntn_Autonomous_GNSS_Fix_r18_tags_29[] = {
	(ASN_TAG_CLASS_CONTEXT | (13 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ntn_Autonomous_GNSS_Fix_r18_29 = {
	"ntn-Autonomous-GNSS-Fix-r18",
	"ntn-Autonomous-GNSS-Fix-r18",
	&asn_OP_NativeEnumerated,
	asn_DEF_ntn_Autonomous_GNSS_Fix_r18_tags_29,
	sizeof(asn_DEF_ntn_Autonomous_GNSS_Fix_r18_tags_29)
		/sizeof(asn_DEF_ntn_Autonomous_GNSS_Fix_r18_tags_29[0]) - 1, /* 1 */
	asn_DEF_ntn_Autonomous_GNSS_Fix_r18_tags_29,	/* Same as above */
	sizeof(asn_DEF_ntn_Autonomous_GNSS_Fix_r18_tags_29)
		/sizeof(asn_DEF_ntn_Autonomous_GNSS_Fix_r18_tags_29[0]), /* 2 */
	{ &asn_OER_type_ntn_Autonomous_GNSS_Fix_r18_constr_29, &asn_PER_type_ntn_Autonomous_GNSS_Fix_r18_constr_29, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_ntn_Autonomous_GNSS_Fix_r18_specs_29	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_ntn_UplinkTxExtension_r18_value2enum_31[] = {
	{ 0,	9,	"supported" }
};
static const unsigned int asn_MAP_ntn_UplinkTxExtension_r18_enum2value_31[] = {
	0	/* supported(0) */
};
static const asn_INTEGER_specifics_t asn_SPC_ntn_UplinkTxExtension_r18_specs_31 = {
	asn_MAP_ntn_UplinkTxExtension_r18_value2enum_31,	/* "tag" => N; sorted by tag */
	asn_MAP_ntn_UplinkTxExtension_r18_enum2value_31,	/* N => "tag"; sorted by N */
	1,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_ntn_UplinkTxExtension_r18_tags_31[] = {
	(ASN_TAG_CLASS_CONTEXT | (14 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ntn_UplinkTxExtension_r18_31 = {
	"ntn-UplinkTxExtension-r18",
	"ntn-UplinkTxExtension-r18",
	&asn_OP_NativeEnumerated,
	asn_DEF_ntn_UplinkTxExtension_r18_tags_31,
	sizeof(asn_DEF_ntn_UplinkTxExtension_r18_tags_31)
		/sizeof(asn_DEF_ntn_UplinkTxExtension_r18_tags_31[0]) - 1, /* 1 */
	asn_DEF_ntn_UplinkTxExtension_r18_tags_31,	/* Same as above */
	sizeof(asn_DEF_ntn_UplinkTxExtension_r18_tags_31)
		/sizeof(asn_DEF_ntn_UplinkTxExtension_r18_tags_31[0]), /* 2 */
	{ &asn_OER_type_ntn_UplinkTxExtension_r18_constr_31, &asn_PER_type_ntn_UplinkTxExtension_r18_constr_31, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_ntn_UplinkTxExtension_r18_specs_31	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_ntn_GNSS_EnhScenarioSupport_r18_value2enum_33[] = {
	{ 0,	4,	"ngso" },
	{ 1,	3,	"gso" }
};
static const unsigned int asn_MAP_ntn_GNSS_EnhScenarioSupport_r18_enum2value_33[] = {
	1,	/* gso(1) */
	0	/* ngso(0) */
};
static const asn_INTEGER_specifics_t asn_SPC_ntn_GNSS_EnhScenarioSupport_r18_specs_33 = {
	asn_MAP_ntn_GNSS_EnhScenarioSupport_r18_value2enum_33,	/* "tag" => N; sorted by tag */
	asn_MAP_ntn_GNSS_EnhScenarioSupport_r18_enum2value_33,	/* N => "tag"; sorted by N */
	2,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_ntn_GNSS_EnhScenarioSupport_r18_tags_33[] = {
	(ASN_TAG_CLASS_CONTEXT | (15 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ntn_GNSS_EnhScenarioSupport_r18_33 = {
	"ntn-GNSS-EnhScenarioSupport-r18",
	"ntn-GNSS-EnhScenarioSupport-r18",
	&asn_OP_NativeEnumerated,
	asn_DEF_ntn_GNSS_EnhScenarioSupport_r18_tags_33,
	sizeof(asn_DEF_ntn_GNSS_EnhScenarioSupport_r18_tags_33)
		/sizeof(asn_DEF_ntn_GNSS_EnhScenarioSupport_r18_tags_33[0]) - 1, /* 1 */
	asn_DEF_ntn_GNSS_EnhScenarioSupport_r18_tags_33,	/* Same as above */
	sizeof(asn_DEF_ntn_GNSS_EnhScenarioSupport_r18_tags_33)
		/sizeof(asn_DEF_ntn_GNSS_EnhScenarioSupport_r18_tags_33[0]), /* 2 */
	{ &asn_OER_type_ntn_GNSS_EnhScenarioSupport_r18_constr_33, &asn_PER_type_ntn_GNSS_EnhScenarioSupport_r18_constr_33, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_ntn_GNSS_EnhScenarioSupport_r18_specs_33	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_NTN_Parameters_NB_v1800_1[] = {
	{ ATF_POINTER, 16, offsetof(struct NTN_Parameters_NB_v1800, ntn_LocationBasedMeasTrigger_EFC_r18),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ntn_LocationBasedMeasTrigger_EFC_r18_2,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ntn-LocationBasedMeasTrigger-EFC-r18"
		},
	{ ATF_POINTER, 15, offsetof(struct NTN_Parameters_NB_v1800, ntn_LocationBasedMeasTrigger_EMC_r18),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ntn_LocationBasedMeasTrigger_EMC_r18_4,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ntn-LocationBasedMeasTrigger-EMC-r18"
		},
	{ ATF_POINTER, 14, offsetof(struct NTN_Parameters_NB_v1800, ntn_TimeBasedMeasTrigger_r18),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ntn_TimeBasedMeasTrigger_r18_6,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ntn-TimeBasedMeasTrigger-r18"
		},
	{ ATF_POINTER, 13, offsetof(struct NTN_Parameters_NB_v1800, ntn_RRC_HarqDisableSingleTB_r18),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ntn_RRC_HarqDisableSingleTB_r18_8,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ntn-RRC-HarqDisableSingleTB-r18"
		},
	{ ATF_POINTER, 12, offsetof(struct NTN_Parameters_NB_v1800, ntn_OverriddenHarqDisableSingleTB_r18),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ntn_OverriddenHarqDisableSingleTB_r18_10,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ntn-OverriddenHarqDisableSingleTB-r18"
		},
	{ ATF_POINTER, 11, offsetof(struct NTN_Parameters_NB_v1800, ntn_DCI_HarqDisableSingleTB_r18),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ntn_DCI_HarqDisableSingleTB_r18_12,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ntn-DCI-HarqDisableSingleTB-r18"
		},
	{ ATF_POINTER, 10, offsetof(struct NTN_Parameters_NB_v1800, ntn_RRC_HarqDisableMultiTB_r18),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ntn_RRC_HarqDisableMultiTB_r18_14,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ntn-RRC-HarqDisableMultiTB-r18"
		},
	{ ATF_POINTER, 9, offsetof(struct NTN_Parameters_NB_v1800, ntn_OverriddenHarqDisableMultiTB_r18),
		(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ntn_OverriddenHarqDisableMultiTB_r18_16,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ntn-OverriddenHarqDisableMultiTB-r18"
		},
	{ ATF_POINTER, 8, offsetof(struct NTN_Parameters_NB_v1800, ntn_DCI_HarqDisableMultiTB_r18),
		(ASN_TAG_CLASS_CONTEXT | (8 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ntn_DCI_HarqDisableMultiTB_r18_18,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ntn-DCI-HarqDisableMultiTB-r18"
		},
	{ ATF_POINTER, 7, offsetof(struct NTN_Parameters_NB_v1800, ntn_UplinkHarq_ModeB_SingleTB_r18),
		(ASN_TAG_CLASS_CONTEXT | (9 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ntn_UplinkHarq_ModeB_SingleTB_r18_20,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ntn-UplinkHarq-ModeB-SingleTB-r18"
		},
	{ ATF_POINTER, 6, offsetof(struct NTN_Parameters_NB_v1800, ntn_UplinkHarq_ModeB_MultiTB_r18),
		(ASN_TAG_CLASS_CONTEXT | (10 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ntn_UplinkHarq_ModeB_MultiTB_r18_22,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ntn-UplinkHarq-ModeB-MultiTB-r18"
		},
	{ ATF_POINTER, 5, offsetof(struct NTN_Parameters_NB_v1800, ntn_HarqEnhScenarioSupport_r18),
		(ASN_TAG_CLASS_CONTEXT | (11 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ntn_HarqEnhScenarioSupport_r18_24,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ntn-HarqEnhScenarioSupport-r18"
		},
	{ ATF_POINTER, 4, offsetof(struct NTN_Parameters_NB_v1800, ntn_Triggered_GNSS_Fix_r18),
		(ASN_TAG_CLASS_CONTEXT | (12 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ntn_Triggered_GNSS_Fix_r18_27,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ntn-Triggered-GNSS-Fix-r18"
		},
	{ ATF_POINTER, 3, offsetof(struct NTN_Parameters_NB_v1800, ntn_Autonomous_GNSS_Fix_r18),
		(ASN_TAG_CLASS_CONTEXT | (13 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ntn_Autonomous_GNSS_Fix_r18_29,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ntn-Autonomous-GNSS-Fix-r18"
		},
	{ ATF_POINTER, 2, offsetof(struct NTN_Parameters_NB_v1800, ntn_UplinkTxExtension_r18),
		(ASN_TAG_CLASS_CONTEXT | (14 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ntn_UplinkTxExtension_r18_31,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ntn-UplinkTxExtension-r18"
		},
	{ ATF_POINTER, 1, offsetof(struct NTN_Parameters_NB_v1800, ntn_GNSS_EnhScenarioSupport_r18),
		(ASN_TAG_CLASS_CONTEXT | (15 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ntn_GNSS_EnhScenarioSupport_r18_33,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ntn-GNSS-EnhScenarioSupport-r18"
		},
};
static const int asn_MAP_NTN_Parameters_NB_v1800_oms_1[] = { 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15 };
static const ber_tlv_tag_t asn_DEF_NTN_Parameters_NB_v1800_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_NTN_Parameters_NB_v1800_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* ntn-LocationBasedMeasTrigger-EFC-r18 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* ntn-LocationBasedMeasTrigger-EMC-r18 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* ntn-TimeBasedMeasTrigger-r18 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* ntn-RRC-HarqDisableSingleTB-r18 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* ntn-OverriddenHarqDisableSingleTB-r18 */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* ntn-DCI-HarqDisableSingleTB-r18 */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0 }, /* ntn-RRC-HarqDisableMultiTB-r18 */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 7, 0, 0 }, /* ntn-OverriddenHarqDisableMultiTB-r18 */
    { (ASN_TAG_CLASS_CONTEXT | (8 << 2)), 8, 0, 0 }, /* ntn-DCI-HarqDisableMultiTB-r18 */
    { (ASN_TAG_CLASS_CONTEXT | (9 << 2)), 9, 0, 0 }, /* ntn-UplinkHarq-ModeB-SingleTB-r18 */
    { (ASN_TAG_CLASS_CONTEXT | (10 << 2)), 10, 0, 0 }, /* ntn-UplinkHarq-ModeB-MultiTB-r18 */
    { (ASN_TAG_CLASS_CONTEXT | (11 << 2)), 11, 0, 0 }, /* ntn-HarqEnhScenarioSupport-r18 */
    { (ASN_TAG_CLASS_CONTEXT | (12 << 2)), 12, 0, 0 }, /* ntn-Triggered-GNSS-Fix-r18 */
    { (ASN_TAG_CLASS_CONTEXT | (13 << 2)), 13, 0, 0 }, /* ntn-Autonomous-GNSS-Fix-r18 */
    { (ASN_TAG_CLASS_CONTEXT | (14 << 2)), 14, 0, 0 }, /* ntn-UplinkTxExtension-r18 */
    { (ASN_TAG_CLASS_CONTEXT | (15 << 2)), 15, 0, 0 } /* ntn-GNSS-EnhScenarioSupport-r18 */
};
asn_SEQUENCE_specifics_t asn_SPC_NTN_Parameters_NB_v1800_specs_1 = {
	sizeof(struct NTN_Parameters_NB_v1800),
	offsetof(struct NTN_Parameters_NB_v1800, _asn_ctx),
	asn_MAP_NTN_Parameters_NB_v1800_tag2el_1,
	16,	/* Count of tags in the map */
	asn_MAP_NTN_Parameters_NB_v1800_oms_1,	/* Optional members */
	16, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_NTN_Parameters_NB_v1800 = {
	"NTN-Parameters-NB-v1800",
	"NTN-Parameters-NB-v1800",
	&asn_OP_SEQUENCE,
	asn_DEF_NTN_Parameters_NB_v1800_tags_1,
	sizeof(asn_DEF_NTN_Parameters_NB_v1800_tags_1)
		/sizeof(asn_DEF_NTN_Parameters_NB_v1800_tags_1[0]), /* 1 */
	asn_DEF_NTN_Parameters_NB_v1800_tags_1,	/* Same as above */
	sizeof(asn_DEF_NTN_Parameters_NB_v1800_tags_1)
		/sizeof(asn_DEF_NTN_Parameters_NB_v1800_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_NTN_Parameters_NB_v1800_1,
	16,	/* Elements count */
	&asn_SPC_NTN_Parameters_NB_v1800_specs_1	/* Additional specs */
};

