/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "../../Skeletons/ASN_files/LTE/lte-rrc-19.0.0.asn1"
 * 	`asn1c -fcompound-names -pdu=all -gen-PER`
 */

#ifndef _SatelliteInfo_r17_H_
#define _SatelliteInfo_r17_H_


#include <asn_application.h>

/* Including external dependencies */
#include "TimeOffsetUTC-r17.h"
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct TLE_EphemerisParameters_r17;

/* SatelliteInfo-r17 */
typedef struct SatelliteInfo_r17 {
    long satelliteId_r17;
    struct SatelliteInfo_r17__serviceInfo_r17 {
        struct TLE_EphemerisParameters_r17 *tle_EphemerisParameters_r17 /* OPTIONAL */;
        TimeOffsetUTC_r17_t *t_ServiceStart_r17 /* OPTIONAL */;

        /* Context for parsing across buffer boundaries */
        asn_struct_ctx_t _asn_ctx;
    } serviceInfo_r17;
    struct SatelliteInfo_r17__footprintInfo_r17 {
        struct SatelliteInfo_r17__footprintInfo_r17__referencePoint_r17 {
            long longitude_r17;
            long latitude_r17;

            /* Context for parsing across buffer boundaries */
            asn_struct_ctx_t _asn_ctx;
        } *referencePoint_r17;
        struct SatelliteInfo_r17__footprintInfo_r17__elevationAngles_r17 {
            long elevationAngleRight_r17;
            long *elevationAngleLeft_r17 /* OPTIONAL */;

            /* Context for parsing across buffer boundaries */
            asn_struct_ctx_t _asn_ctx;
        } *elevationAngles_r17;
        long *radius_r17 /* OPTIONAL */;

        /* Context for parsing across buffer boundaries */
        asn_struct_ctx_t _asn_ctx;
    } footprintInfo_r17;

    /* Context for parsing across buffer boundaries */
    asn_struct_ctx_t _asn_ctx;
} SatelliteInfo_r17_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SatelliteInfo_r17;
extern asn_SEQUENCE_specifics_t asn_SPC_SatelliteInfo_r17_specs_1;
extern asn_TYPE_member_t asn_MBR_SatelliteInfo_r17_1[3];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "TLE-EphemerisParameters-r17.h"

#endif /* _SatelliteInfo_r17_H_ */
#include <asn_internal.h>
