/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "../../Skeletons/ASN_files/LTE/lte-rrc-19.0.0.asn1"
 * 	`asn1c -fcompound-names -pdu=all -gen-PER`
 */

#ifndef	_CarrierFreqNR_v1900_H_
#define	_CarrierFreqNR_v1900_H_


#include <asn_application.h>

/* Including external dependencies */
#include "SatelliteId-r18.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* CarrierFreqNR-v1900 */
typedef struct CarrierFreqNR_v1900 {
	struct CarrierFreqNR_v1900__satAssistanceInfoList_r19 {
		A_SEQUENCE_OF(SatelliteId_r18_t) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *satAssistanceInfoList_r19;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CarrierFreqNR_v1900_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CarrierFreqNR_v1900;
extern asn_SEQUENCE_specifics_t asn_SPC_CarrierFreqNR_v1900_specs_1;
extern asn_TYPE_member_t asn_MBR_CarrierFreqNR_v1900_1[1];

#ifdef __cplusplus
}
#endif

#endif	/* _CarrierFreqNR_v1900_H_ */
#include <asn_internal.h>
