/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NBIOT-RRC-Definitions"
 * 	found in "../../Skeletons/ASN_files/LTE/lte-rrc-19.0.0.asn1"
 * 	`asn1c -fcompound-names -pdu=all -gen-PER`
 */

#ifndef	_Paging_NB_v1610_IEs_H_
#define	_Paging_NB_v1610_IEs_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct PagingRecordList_NB_v1610;
struct Paging_NB_v1900_IEs;

/* Paging-NB-v1610-IEs */
typedef struct Paging_NB_v1610_IEs {
	struct PagingRecordList_NB_v1610	*pagingRecordList_v1610	/* OPTIONAL */;
	struct Paging_NB_v1900_IEs	*nonCriticalExtension	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Paging_NB_v1610_IEs_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Paging_NB_v1610_IEs;
extern asn_SEQUENCE_specifics_t asn_SPC_Paging_NB_v1610_IEs_specs_1;
extern asn_TYPE_member_t asn_MBR_Paging_NB_v1610_IEs_1[2];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "PagingRecordList-NB-v1610.h"
#include "Paging-NB-v1900-IEs.h"

#endif	/* _Paging_NB_v1610_IEs_H_ */
#include <asn_internal.h>
