/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NBIOT-RRC-Definitions"
 * 	found in "../../Skeletons/ASN_files/LTE/lte-rrc-19.0.0.asn1"
 * 	`asn1c -fcompound-names -pdu=all -gen-PER`
 */

#ifndef	_SupportedBandList_NB_v1710_H_
#define	_SupportedBandList_NB_v1710_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct SupportedBand_NB_v1710;

/* SupportedBandList-NB-v1710 */
typedef struct SupportedBandList_NB_v1710 {
	A_SEQUENCE_OF(struct SupportedBand_NB_v1710) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SupportedBandList_NB_v1710_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SupportedBandList_NB_v1710;
extern asn_SET_OF_specifics_t asn_SPC_SupportedBandList_NB_v1710_specs_1;
extern asn_TYPE_member_t asn_MBR_SupportedBandList_NB_v1710_1[1];
extern asn_per_constraints_t asn_PER_type_SupportedBandList_NB_v1710_constr_1;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "SupportedBand-NB-v1710.h"

#endif	/* _SupportedBandList_NB_v1710_H_ */
#include <asn_internal.h>
