/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "../../Skeletons/ASN_files/UMTS/rrc-25.331-r19.asn1"
 * 	`asn1c -fcompound-names -pdu=all`
 */

#ifndef	_AddOrReconfMAC_dFlow_H_
#define	_AddOrReconfMAC_dFlow_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct MAC_hs_AddReconfQueue_List;
struct MAC_hs_DelQueue_List;

/* AddOrReconfMAC-dFlow */
typedef struct AddOrReconfMAC_dFlow {
	struct MAC_hs_AddReconfQueue_List	*mac_hs_AddReconfQueue_List	/* OPTIONAL */;
	struct MAC_hs_DelQueue_List	*mac_hs_DelQueue_List	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} AddOrReconfMAC_dFlow_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AddOrReconfMAC_dFlow;
extern asn_SEQUENCE_specifics_t asn_SPC_AddOrReconfMAC_dFlow_specs_1;
extern asn_TYPE_member_t asn_MBR_AddOrReconfMAC_dFlow_1[2];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "MAC-hs-AddReconfQueue-List.h"
#include "MAC-hs-DelQueue-List.h"

#endif	/* _AddOrReconfMAC_dFlow_H_ */
#include <asn_internal.h>
