/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "../../Skeletons/ASN_files/UMTS/rrc-25.331-r19.asn1"
 * 	`asn1c -fcompound-names -pdu=all`
 */

#ifndef	_Antenna3And4_S_CPICH_H_
#define	_Antenna3And4_S_CPICH_H_


#include <asn_application.h>

/* Including external dependencies */
#include "S-CPICH-PowerOffset-4x4MIMO.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct Antenna3_S_CPICH;
struct Antenna4_S_CPICH;

/* Antenna3And4-S-CPICH */
typedef struct Antenna3And4_S_CPICH {
	struct Antenna3_S_CPICH	*antenna3_S_CPICH	/* OPTIONAL */;
	struct Antenna4_S_CPICH	*antenna4_S_CPICH	/* OPTIONAL */;
	S_CPICH_PowerOffset_4x4MIMO_t	*s_cpich_PowerOffset_Mimo	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Antenna3And4_S_CPICH_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Antenna3And4_S_CPICH;
extern asn_SEQUENCE_specifics_t asn_SPC_Antenna3And4_S_CPICH_specs_1;
extern asn_TYPE_member_t asn_MBR_Antenna3And4_S_CPICH_1[3];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "Antenna3-S-CPICH.h"
#include "Antenna4-S-CPICH.h"

#endif	/* _Antenna3And4_S_CPICH_H_ */
#include <asn_internal.h>
