/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "../../Skeletons/ASN_files/UMTS/rrc-25.331-r19.asn1"
 * 	`asn1c -fcompound-names -pdu=all`
 */

#ifndef	_CellMeasurementEventResultsOnSecUlFreq_H_
#define	_CellMeasurementEventResultsOnSecUlFreq_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NULL.h>
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum CellMeasurementEventResultsOnSecUlFreq_PR {
	CellMeasurementEventResultsOnSecUlFreq_PR_NOTHING,	/* No components present */
	CellMeasurementEventResultsOnSecUlFreq_PR_fdd,
	CellMeasurementEventResultsOnSecUlFreq_PR_spare
} CellMeasurementEventResultsOnSecUlFreq_PR;

/* Forward declarations */
struct PrimaryCPICH_Info;

/* CellMeasurementEventResultsOnSecUlFreq */
typedef struct CellMeasurementEventResultsOnSecUlFreq {
	CellMeasurementEventResultsOnSecUlFreq_PR present;
	union CellMeasurementEventResultsOnSecUlFreq_u {
		struct CellMeasurementEventResultsOnSecUlFreq__fdd {
			A_SEQUENCE_OF(struct PrimaryCPICH_Info) list;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} fdd;
		NULL_t	 spare;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CellMeasurementEventResultsOnSecUlFreq_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CellMeasurementEventResultsOnSecUlFreq;
extern asn_CHOICE_specifics_t asn_SPC_CellMeasurementEventResultsOnSecUlFreq_specs_1;
extern asn_TYPE_member_t asn_MBR_CellMeasurementEventResultsOnSecUlFreq_1[2];
extern asn_per_constraints_t asn_PER_type_CellMeasurementEventResultsOnSecUlFreq_constr_1;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "PrimaryCPICH-Info.h"

#endif	/* _CellMeasurementEventResultsOnSecUlFreq_H_ */
#include <asn_internal.h>
