/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "../../Skeletons/ASN_files/UMTS/rrc-25.331-r19.asn1"
 * 	`asn1c -fcompound-names -pdu=all`
 */

#ifndef	_DedicatedPriorityInformation_r13_H_
#define	_DedicatedPriorityInformation_r13_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NULL.h>
#include "T-322.h"
#include <BOOLEAN.h>
#include <constr_SEQUENCE.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum DedicatedPriorityInformation_r13__action_PR {
	DedicatedPriorityInformation_r13__action_PR_NOTHING,	/* No components present */
	DedicatedPriorityInformation_r13__action_PR_clearDedicatedPriorities,
	DedicatedPriorityInformation_r13__action_PR_configureDedicatedPriorities
} DedicatedPriorityInformation_r13__action_PR;

/* Forward declarations */
struct PriorityLevelList_r13;

/* DedicatedPriorityInformation-r13 */
typedef struct DedicatedPriorityInformation_r13 {
	struct DedicatedPriorityInformation_r13__action {
		DedicatedPriorityInformation_r13__action_PR present;
		union DedicatedPriorityInformation_r13__action_u {
			NULL_t	 clearDedicatedPriorities;
			struct DedicatedPriorityInformation_r13__action__configureDedicatedPriorities {
				T_322_t	*t_322	/* OPTIONAL */;
				struct PriorityLevelList_r13	*priorityLevelList	/* OPTIONAL */;
				BOOLEAN_t	 eutraDetection;
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} configureDedicatedPriorities;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} action;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DedicatedPriorityInformation_r13_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DedicatedPriorityInformation_r13;
extern asn_SEQUENCE_specifics_t asn_SPC_DedicatedPriorityInformation_r13_specs_1;
extern asn_TYPE_member_t asn_MBR_DedicatedPriorityInformation_r13_1[1];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "PriorityLevelList-r13.h"

#endif	/* _DedicatedPriorityInformation_r13_H_ */
#include <asn_internal.h>
