/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "../../Skeletons/ASN_files/UMTS/rrc-25.331-r19.asn1"
 * 	`asn1c -fcompound-names -pdu=all`
 */

#ifndef	_DGANSSSignalInformation_H_
#define	_DGANSSSignalInformation_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <BIT_STRING.h>
#include "UDRE.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* DGANSSSignalInformation */
typedef struct DGANSSSignalInformation {
	long	 satId;
	BIT_STRING_t	 iode_dganss;
	UDRE_t	 udre;
	long	 ganss_prc;
	long	 ganss_rrc;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DGANSSSignalInformation_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DGANSSSignalInformation;
extern asn_SEQUENCE_specifics_t asn_SPC_DGANSSSignalInformation_specs_1;
extern asn_TYPE_member_t asn_MBR_DGANSSSignalInformation_1[5];

#ifdef __cplusplus
}
#endif

#endif	/* _DGANSSSignalInformation_H_ */
#include <asn_internal.h>
