/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "../../Skeletons/ASN_files/UMTS/rrc-25.331-r19.asn1"
 * 	`asn1c -fcompound-names -pdu=all`
 */

#include "DGANSSInfo-r9.h"

asn_TYPE_member_t asn_MBR_DGANSSInfo_r9_1[] = {
	{ ATF_POINTER, 1, offsetof(struct DGANSSInfo_r9, ganssSignalId),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_GANSS_Signal_Id,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ganssSignalId"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct DGANSSInfo_r9, ganssStatusHealth),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_GANSS_Status_Health,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ganssStatusHealth"
		},
	{ ATF_POINTER, 1, offsetof(struct DGANSSInfo_r9, dgansssignalInformationList),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DGANSSSignalInformationList_r9,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"dgansssignalInformationList"
		},
};
static const int asn_MAP_DGANSSInfo_r9_oms_1[] = { 0, 2 };
static const ber_tlv_tag_t asn_DEF_DGANSSInfo_r9_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_DGANSSInfo_r9_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* ganssSignalId */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* ganssStatusHealth */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* dgansssignalInformationList */
};
asn_SEQUENCE_specifics_t asn_SPC_DGANSSInfo_r9_specs_1 = {
	sizeof(struct DGANSSInfo_r9),
	offsetof(struct DGANSSInfo_r9, _asn_ctx),
	asn_MAP_DGANSSInfo_r9_tag2el_1,
	3,	/* Count of tags in the map */
	asn_MAP_DGANSSInfo_r9_oms_1,	/* Optional members */
	2, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_DGANSSInfo_r9 = {
	"DGANSSInfo-r9",
	"DGANSSInfo-r9",
	&asn_OP_SEQUENCE,
	asn_DEF_DGANSSInfo_r9_tags_1,
	sizeof(asn_DEF_DGANSSInfo_r9_tags_1)
		/sizeof(asn_DEF_DGANSSInfo_r9_tags_1[0]), /* 1 */
	asn_DEF_DGANSSInfo_r9_tags_1,	/* Same as above */
	sizeof(asn_DEF_DGANSSInfo_r9_tags_1)
		/sizeof(asn_DEF_DGANSSInfo_r9_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_DGANSSInfo_r9_1,
	3,	/* Elements count */
	&asn_SPC_DGANSSInfo_r9_specs_1	/* Additional specs */
};

