/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "../../Skeletons/ASN_files/UMTS/rrc-25.331-r19.asn1"
 * 	`asn1c -fcompound-names -pdu=all`
 */

#ifndef	_DL_FDPCH_InfoPerRL_r7_H_
#define	_DL_FDPCH_InfoPerRL_r7_H_


#include <asn_application.h>

/* Including external dependencies */
#include "PCPICH-UsageForChannelEst.h"
#include "DPCH-FrameOffset.h"
#include "FDPCH-SlotFormat.h"
#include "SecondaryScramblingCode.h"
#include <NativeInteger.h>
#include "TPC-CombinationIndex.h"
#include "STTDIndication.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct SecondaryCPICH_Info;

/* DL-FDPCH-InfoPerRL-r7 */
typedef struct DL_FDPCH_InfoPerRL_r7 {
	PCPICH_UsageForChannelEst_t	 pCPICH_UsageForChannelEst;
	DPCH_FrameOffset_t	 fdpch_FrameOffset;
	FDPCH_SlotFormat_t	*fdpch_SlotFormat	/* OPTIONAL */;
	struct SecondaryCPICH_Info	*secondaryCPICH_Info	/* OPTIONAL */;
	SecondaryScramblingCode_t	*secondaryScramblingCode	/* OPTIONAL */;
	long	 dl_ChannelisationCode;
	TPC_CombinationIndex_t	 tpc_CombinationIndex;
	STTDIndication_t	*sttdIndication	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DL_FDPCH_InfoPerRL_r7_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DL_FDPCH_InfoPerRL_r7;
extern asn_SEQUENCE_specifics_t asn_SPC_DL_FDPCH_InfoPerRL_r7_specs_1;
extern asn_TYPE_member_t asn_MBR_DL_FDPCH_InfoPerRL_r7_1[8];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "SecondaryCPICH-Info.h"

#endif	/* _DL_FDPCH_InfoPerRL_r7_H_ */
#include <asn_internal.h>
