/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "../../Skeletons/ASN_files/UMTS/rrc-25.331-r19.asn1"
 * 	`asn1c -fcompound-names -pdu=all`
 */

#include "DL-FDPCH-InfoCommon-r6.h"

static int
memb_dl_FDPCH_TPCcommandErrorRate_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 1 && value <= 16)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_oer_constraints_t asn_OER_type_cfnHandling_constr_2 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_cfnHandling_constr_2 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_dl_FDPCH_TPCcommandErrorRate_constr_7 CC_NOTUSED = {
	{ 1, 1 }	/* (1..16) */,
	-1};
static asn_per_constraints_t asn_PER_memb_dl_FDPCH_TPCcommandErrorRate_constr_7 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 4,  4,  1,  16 }	/* (1..16) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_maintain_3[] = {
	{ ATF_POINTER, 1, offsetof(struct DL_FDPCH_InfoCommon_r6__cfnHandling__maintain, timingmaintainedsynchind),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TimingMaintainedSynchInd,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"timingmaintainedsynchind"
		},
};
static const int asn_MAP_maintain_oms_3[] = { 0 };
static const ber_tlv_tag_t asn_DEF_maintain_tags_3[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_maintain_tag2el_3[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 } /* timingmaintainedsynchind */
};
static asn_SEQUENCE_specifics_t asn_SPC_maintain_specs_3 = {
	sizeof(struct DL_FDPCH_InfoCommon_r6__cfnHandling__maintain),
	offsetof(struct DL_FDPCH_InfoCommon_r6__cfnHandling__maintain, _asn_ctx),
	asn_MAP_maintain_tag2el_3,
	1,	/* Count of tags in the map */
	asn_MAP_maintain_oms_3,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_maintain_3 = {
	"maintain",
	"maintain",
	&asn_OP_SEQUENCE,
	asn_DEF_maintain_tags_3,
	sizeof(asn_DEF_maintain_tags_3)
		/sizeof(asn_DEF_maintain_tags_3[0]) - 1, /* 1 */
	asn_DEF_maintain_tags_3,	/* Same as above */
	sizeof(asn_DEF_maintain_tags_3)
		/sizeof(asn_DEF_maintain_tags_3[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_maintain_3,
	1,	/* Elements count */
	&asn_SPC_maintain_specs_3	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_cfnHandling_2[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct DL_FDPCH_InfoCommon_r6__cfnHandling, choice.maintain),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		0,
		&asn_DEF_maintain_3,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"maintain"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct DL_FDPCH_InfoCommon_r6__cfnHandling, choice.initialise),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"initialise"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_cfnHandling_tag2el_2[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* maintain */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* initialise */
};
static asn_CHOICE_specifics_t asn_SPC_cfnHandling_specs_2 = {
	sizeof(struct DL_FDPCH_InfoCommon_r6__cfnHandling),
	offsetof(struct DL_FDPCH_InfoCommon_r6__cfnHandling, _asn_ctx),
	offsetof(struct DL_FDPCH_InfoCommon_r6__cfnHandling, present),
	sizeof(((struct DL_FDPCH_InfoCommon_r6__cfnHandling *)0)->present),
	asn_MAP_cfnHandling_tag2el_2,
	2,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_cfnHandling_2 = {
	"cfnHandling",
	"cfnHandling",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ &asn_OER_type_cfnHandling_constr_2, &asn_PER_type_cfnHandling_constr_2, CHOICE_constraint },
	asn_MBR_cfnHandling_2,
	2,	/* Elements count */
	&asn_SPC_cfnHandling_specs_2	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_DL_FDPCH_InfoCommon_r6_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct DL_FDPCH_InfoCommon_r6, cfnHandling),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_cfnHandling_2,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"cfnHandling"
		},
	{ ATF_POINTER, 2, offsetof(struct DL_FDPCH_InfoCommon_r6, dl_FDPCH_PowerControlInfo),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DL_DPCH_PowerControlInfo,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"dl-FDPCH-PowerControlInfo"
		},
	{ ATF_POINTER, 1, offsetof(struct DL_FDPCH_InfoCommon_r6, dl_FDPCH_TPCcommandErrorRate),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ &asn_OER_memb_dl_FDPCH_TPCcommandErrorRate_constr_7, &asn_PER_memb_dl_FDPCH_TPCcommandErrorRate_constr_7,  memb_dl_FDPCH_TPCcommandErrorRate_constraint_1 },
		0, 0, /* No default value */
		"dl-FDPCH-TPCcommandErrorRate"
		},
};
static const int asn_MAP_DL_FDPCH_InfoCommon_r6_oms_1[] = { 1, 2 };
static const ber_tlv_tag_t asn_DEF_DL_FDPCH_InfoCommon_r6_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_DL_FDPCH_InfoCommon_r6_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* cfnHandling */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* dl-FDPCH-PowerControlInfo */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* dl-FDPCH-TPCcommandErrorRate */
};
asn_SEQUENCE_specifics_t asn_SPC_DL_FDPCH_InfoCommon_r6_specs_1 = {
	sizeof(struct DL_FDPCH_InfoCommon_r6),
	offsetof(struct DL_FDPCH_InfoCommon_r6, _asn_ctx),
	asn_MAP_DL_FDPCH_InfoCommon_r6_tag2el_1,
	3,	/* Count of tags in the map */
	asn_MAP_DL_FDPCH_InfoCommon_r6_oms_1,	/* Optional members */
	2, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_DL_FDPCH_InfoCommon_r6 = {
	"DL-FDPCH-InfoCommon-r6",
	"DL-FDPCH-InfoCommon-r6",
	&asn_OP_SEQUENCE,
	asn_DEF_DL_FDPCH_InfoCommon_r6_tags_1,
	sizeof(asn_DEF_DL_FDPCH_InfoCommon_r6_tags_1)
		/sizeof(asn_DEF_DL_FDPCH_InfoCommon_r6_tags_1[0]), /* 1 */
	asn_DEF_DL_FDPCH_InfoCommon_r6_tags_1,	/* Same as above */
	sizeof(asn_DEF_DL_FDPCH_InfoCommon_r6_tags_1)
		/sizeof(asn_DEF_DL_FDPCH_InfoCommon_r6_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_DL_FDPCH_InfoCommon_r6_1,
	3,	/* Elements count */
	&asn_SPC_DL_FDPCH_InfoCommon_r6_specs_1	/* Additional specs */
};

