/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "../../Skeletons/ASN_files/UMTS/rrc-25.331-r19.asn1"
 * 	`asn1c -fcompound-names -pdu=all`
 */

#include "DL-TransportChannelIdentity-r7.h"

asn_TYPE_member_t asn_MBR_DL_TransportChannelIdentity_r7_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct DL_TransportChannelIdentity_r7, dl_TransportChannelType),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_DL_TrCH_TypeId2_r7,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"dl-TransportChannelType"
		},
};
static const ber_tlv_tag_t asn_DEF_DL_TransportChannelIdentity_r7_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_DL_TransportChannelIdentity_r7_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 } /* dl-TransportChannelType */
};
asn_SEQUENCE_specifics_t asn_SPC_DL_TransportChannelIdentity_r7_specs_1 = {
	sizeof(struct DL_TransportChannelIdentity_r7),
	offsetof(struct DL_TransportChannelIdentity_r7, _asn_ctx),
	asn_MAP_DL_TransportChannelIdentity_r7_tag2el_1,
	1,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_DL_TransportChannelIdentity_r7 = {
	"DL-TransportChannelIdentity-r7",
	"DL-TransportChannelIdentity-r7",
	&asn_OP_SEQUENCE,
	asn_DEF_DL_TransportChannelIdentity_r7_tags_1,
	sizeof(asn_DEF_DL_TransportChannelIdentity_r7_tags_1)
		/sizeof(asn_DEF_DL_TransportChannelIdentity_r7_tags_1[0]), /* 1 */
	asn_DEF_DL_TransportChannelIdentity_r7_tags_1,	/* Same as above */
	sizeof(asn_DEF_DL_TransportChannelIdentity_r7_tags_1)
		/sizeof(asn_DEF_DL_TransportChannelIdentity_r7_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_DL_TransportChannelIdentity_r7_1,
	1,	/* Elements count */
	&asn_SPC_DL_TransportChannelIdentity_r7_specs_1	/* Additional specs */
};

