/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "../../Skeletons/ASN_files/UMTS/rrc-25.331-r19.asn1"
 * 	`asn1c -fcompound-names -pdu=all`
 */

#ifndef	_DPCH_FrameOffset_H_
#define	_DPCH_FrameOffset_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* DPCH-FrameOffset */
typedef long	 DPCH_FrameOffset_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_DPCH_FrameOffset_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_DPCH_FrameOffset;
asn_struct_free_f DPCH_FrameOffset_free;
asn_struct_print_f DPCH_FrameOffset_print;
asn_constr_check_f DPCH_FrameOffset_constraint;
ber_type_decoder_f DPCH_FrameOffset_decode_ber;
der_type_encoder_f DPCH_FrameOffset_encode_der;
xer_type_decoder_f DPCH_FrameOffset_decode_xer;
xer_type_encoder_f DPCH_FrameOffset_encode_xer;
oer_type_decoder_f DPCH_FrameOffset_decode_oer;
oer_type_encoder_f DPCH_FrameOffset_encode_oer;
per_type_decoder_f DPCH_FrameOffset_decode_uper;
per_type_encoder_f DPCH_FrameOffset_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _DPCH_FrameOffset_H_ */
#include <asn_internal.h>
