/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "../../Skeletons/ASN_files/UMTS/rrc-25.331-r19.asn1"
 * 	`asn1c -fcompound-names -pdu=all`
 */

#include "E-DPCCH-Info-r7.h"

asn_TYPE_member_t asn_MBR_E_DPCCH_Info_r7_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct E_DPCCH_Info_r7, e_DPCCH_DPCCH_PowerOffset),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_E_DPCCH_DPCCH_PowerOffset,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"e-DPCCH-DPCCH-PowerOffset"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct E_DPCCH_Info_r7, happyBit_DelayCondition),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_HappyBit_DelayCondition,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"happyBit-DelayCondition"
		},
	{ ATF_POINTER, 2, offsetof(struct E_DPCCH_Info_r7, e_TFC_Boost_Info),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_E_TFC_Boost_Info_r7,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"e-TFC-Boost-Info"
		},
	{ ATF_POINTER, 1, offsetof(struct E_DPCCH_Info_r7, e_DPDCH_PowerInterpolation),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_E_DPDCH_PowerInterpolation,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"e-DPDCH-PowerInterpolation"
		},
};
static const int asn_MAP_E_DPCCH_Info_r7_oms_1[] = { 2, 3 };
static const ber_tlv_tag_t asn_DEF_E_DPCCH_Info_r7_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_E_DPCCH_Info_r7_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* e-DPCCH-DPCCH-PowerOffset */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* happyBit-DelayCondition */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* e-TFC-Boost-Info */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 } /* e-DPDCH-PowerInterpolation */
};
asn_SEQUENCE_specifics_t asn_SPC_E_DPCCH_Info_r7_specs_1 = {
	sizeof(struct E_DPCCH_Info_r7),
	offsetof(struct E_DPCCH_Info_r7, _asn_ctx),
	asn_MAP_E_DPCCH_Info_r7_tag2el_1,
	4,	/* Count of tags in the map */
	asn_MAP_E_DPCCH_Info_r7_oms_1,	/* Optional members */
	2, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_E_DPCCH_Info_r7 = {
	"E-DPCCH-Info-r7",
	"E-DPCCH-Info-r7",
	&asn_OP_SEQUENCE,
	asn_DEF_E_DPCCH_Info_r7_tags_1,
	sizeof(asn_DEF_E_DPCCH_Info_r7_tags_1)
		/sizeof(asn_DEF_E_DPCCH_Info_r7_tags_1[0]), /* 1 */
	asn_DEF_E_DPCCH_Info_r7_tags_1,	/* Same as above */
	sizeof(asn_DEF_E_DPCCH_Info_r7_tags_1)
		/sizeof(asn_DEF_E_DPCCH_Info_r7_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_E_DPCCH_Info_r7_1,
	4,	/* Elements count */
	&asn_SPC_E_DPCCH_Info_r7_specs_1	/* Additional specs */
};

