/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "../../Skeletons/ASN_files/UMTS/rrc-25.331-r19.asn1"
 * 	`asn1c -fcompound-names -pdu=all`
 */

#include "EUTRA-MeasuredResults-vb50ext.h"

asn_TYPE_member_t asn_MBR_EUTRA_MeasuredResults_vb50ext_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct EUTRA_MeasuredResults_vb50ext, eutraMeasuredResultList),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_EUTRA_MeasuredResultList_vb50ext,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"eutraMeasuredResultList"
		},
};
static const ber_tlv_tag_t asn_DEF_EUTRA_MeasuredResults_vb50ext_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_EUTRA_MeasuredResults_vb50ext_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 } /* eutraMeasuredResultList */
};
asn_SEQUENCE_specifics_t asn_SPC_EUTRA_MeasuredResults_vb50ext_specs_1 = {
	sizeof(struct EUTRA_MeasuredResults_vb50ext),
	offsetof(struct EUTRA_MeasuredResults_vb50ext, _asn_ctx),
	asn_MAP_EUTRA_MeasuredResults_vb50ext_tag2el_1,
	1,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_EUTRA_MeasuredResults_vb50ext = {
	"EUTRA-MeasuredResults-vb50ext",
	"EUTRA-MeasuredResults-vb50ext",
	&asn_OP_SEQUENCE,
	asn_DEF_EUTRA_MeasuredResults_vb50ext_tags_1,
	sizeof(asn_DEF_EUTRA_MeasuredResults_vb50ext_tags_1)
		/sizeof(asn_DEF_EUTRA_MeasuredResults_vb50ext_tags_1[0]), /* 1 */
	asn_DEF_EUTRA_MeasuredResults_vb50ext_tags_1,	/* Same as above */
	sizeof(asn_DEF_EUTRA_MeasuredResults_vb50ext_tags_1)
		/sizeof(asn_DEF_EUTRA_MeasuredResults_vb50ext_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_EUTRA_MeasuredResults_vb50ext_1,
	1,	/* Elements count */
	&asn_SPC_EUTRA_MeasuredResults_vb50ext_specs_1	/* Additional specs */
};

