/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "../../Skeletons/ASN_files/UMTS/rrc-25.331-r19.asn1"
 * 	`asn1c -fcompound-names -pdu=all`
 */

#ifndef	_ExtraDoppler_H_
#define	_ExtraDoppler_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <NativeEnumerated.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ExtraDoppler__dopplerUncertainty {
	ExtraDoppler__dopplerUncertainty_dopU40	= 0,
	ExtraDoppler__dopplerUncertainty_dopU20	= 1,
	ExtraDoppler__dopplerUncertainty_dopU10	= 2,
	ExtraDoppler__dopplerUncertainty_dopU5	= 3,
	ExtraDoppler__dopplerUncertainty_dopU2_5	= 4,
	ExtraDoppler__dopplerUncertainty_spare3	= 5,
	ExtraDoppler__dopplerUncertainty_spare2	= 6,
	ExtraDoppler__dopplerUncertainty_spare1	= 7
} e_ExtraDoppler__dopplerUncertainty;

/* ExtraDoppler */
typedef struct ExtraDoppler {
	long	 dopplerFirstOrder;
	long	 dopplerUncertainty;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ExtraDoppler_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_dopplerUncertainty_3;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_ExtraDoppler;
extern asn_SEQUENCE_specifics_t asn_SPC_ExtraDoppler_specs_1;
extern asn_TYPE_member_t asn_MBR_ExtraDoppler_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _ExtraDoppler_H_ */
#include <asn_internal.h>
