/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "../../Skeletons/ASN_files/UMTS/rrc-25.331-r19.asn1"
 * 	`asn1c -fcompound-names -pdu=all`
 */

#include "FilteredUEPowerHeadroomReportInfo.h"

asn_TYPE_member_t asn_MBR_FilteredUEPowerHeadroomReportInfo_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct FilteredUEPowerHeadroomReportInfo, timeToTrigger),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TimeToTrigger,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"timeToTrigger"
		},
	{ ATF_POINTER, 5, offsetof(struct FilteredUEPowerHeadroomReportInfo, hysteresis1),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Hysteresis,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"hysteresis1"
		},
	{ ATF_POINTER, 4, offsetof(struct FilteredUEPowerHeadroomReportInfo, hysteresis2),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Hysteresis,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"hysteresis2"
		},
	{ ATF_POINTER, 3, offsetof(struct FilteredUEPowerHeadroomReportInfo, uePowerHeadroomThreshold1),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UE_PowerHeadroomThreshold,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"uePowerHeadroomThreshold1"
		},
	{ ATF_POINTER, 2, offsetof(struct FilteredUEPowerHeadroomReportInfo, uePowerHeadroomThreshold2),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UE_PowerHeadroomThreshold,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"uePowerHeadroomThreshold2"
		},
	{ ATF_POINTER, 1, offsetof(struct FilteredUEPowerHeadroomReportInfo, filterCoefficient),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_FilterCoefficient,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"filterCoefficient"
		},
};
static const int asn_MAP_FilteredUEPowerHeadroomReportInfo_oms_1[] = { 1, 2, 3, 4, 5 };
static const ber_tlv_tag_t asn_DEF_FilteredUEPowerHeadroomReportInfo_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_FilteredUEPowerHeadroomReportInfo_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* timeToTrigger */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* hysteresis1 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* hysteresis2 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* uePowerHeadroomThreshold1 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* uePowerHeadroomThreshold2 */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 } /* filterCoefficient */
};
asn_SEQUENCE_specifics_t asn_SPC_FilteredUEPowerHeadroomReportInfo_specs_1 = {
	sizeof(struct FilteredUEPowerHeadroomReportInfo),
	offsetof(struct FilteredUEPowerHeadroomReportInfo, _asn_ctx),
	asn_MAP_FilteredUEPowerHeadroomReportInfo_tag2el_1,
	6,	/* Count of tags in the map */
	asn_MAP_FilteredUEPowerHeadroomReportInfo_oms_1,	/* Optional members */
	5, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_FilteredUEPowerHeadroomReportInfo = {
	"FilteredUEPowerHeadroomReportInfo",
	"FilteredUEPowerHeadroomReportInfo",
	&asn_OP_SEQUENCE,
	asn_DEF_FilteredUEPowerHeadroomReportInfo_tags_1,
	sizeof(asn_DEF_FilteredUEPowerHeadroomReportInfo_tags_1)
		/sizeof(asn_DEF_FilteredUEPowerHeadroomReportInfo_tags_1[0]), /* 1 */
	asn_DEF_FilteredUEPowerHeadroomReportInfo_tags_1,	/* Same as above */
	sizeof(asn_DEF_FilteredUEPowerHeadroomReportInfo_tags_1)
		/sizeof(asn_DEF_FilteredUEPowerHeadroomReportInfo_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_FilteredUEPowerHeadroomReportInfo_1,
	6,	/* Elements count */
	&asn_SPC_FilteredUEPowerHeadroomReportInfo_specs_1	/* Additional specs */
};

