/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "../../Skeletons/ASN_files/UMTS/rrc-25.331-r19.asn1"
 * 	`asn1c -fcompound-names -pdu=all`
 */

#ifndef	_FrequencyIndexForEnhancedMeas_H_
#define	_FrequencyIndexForEnhancedMeas_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* FrequencyIndexForEnhancedMeas */
typedef long	 FrequencyIndexForEnhancedMeas_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_FrequencyIndexForEnhancedMeas_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_FrequencyIndexForEnhancedMeas;
asn_struct_free_f FrequencyIndexForEnhancedMeas_free;
asn_struct_print_f FrequencyIndexForEnhancedMeas_print;
asn_constr_check_f FrequencyIndexForEnhancedMeas_constraint;
ber_type_decoder_f FrequencyIndexForEnhancedMeas_decode_ber;
der_type_encoder_f FrequencyIndexForEnhancedMeas_encode_der;
xer_type_decoder_f FrequencyIndexForEnhancedMeas_decode_xer;
xer_type_encoder_f FrequencyIndexForEnhancedMeas_encode_xer;
oer_type_decoder_f FrequencyIndexForEnhancedMeas_decode_oer;
oer_type_encoder_f FrequencyIndexForEnhancedMeas_encode_oer;
per_type_decoder_f FrequencyIndexForEnhancedMeas_decode_uper;
per_type_encoder_f FrequencyIndexForEnhancedMeas_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _FrequencyIndexForEnhancedMeas_H_ */
#include <asn_internal.h>
