/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "../../Skeletons/ASN_files/UMTS/rrc-25.331-r19.asn1"
 * 	`asn1c -fcompound-names -pdu=all`
 */

#ifndef	_GANSSMeasurementParameters_H_
#define	_GANSSMeasurementParameters_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <NativeInteger.h>
#include <NativeEnumerated.h>
#include <BIT_STRING.h>
#include <constr_SEQUENCE.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum GANSSMeasurementParameters__Member__multipathIndicator {
	GANSSMeasurementParameters__Member__multipathIndicator_nm	= 0,
	GANSSMeasurementParameters__Member__multipathIndicator_low	= 1,
	GANSSMeasurementParameters__Member__multipathIndicator_medium	= 2,
	GANSSMeasurementParameters__Member__multipathIndicator_high	= 3
} e_GANSSMeasurementParameters__Member__multipathIndicator;

/* Forward definitions */
typedef struct GANSSMeasurementParameters__Member {
	long	 satId;
	long	 cSurNzero;
	long	 multipathIndicator;
	BIT_STRING_t	*carrierQualityIndication	/* OPTIONAL */;
	long	 ganssCodePhase;
	long	*ganssIntegerCodePhase	/* OPTIONAL */;
	long	 codePhaseRmsError;
	long	 doppler;
	long	*adr	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} GANSSMeasurementParameters__Member;

/* GANSSMeasurementParameters */
typedef struct GANSSMeasurementParameters {
	A_SEQUENCE_OF(GANSSMeasurementParameters__Member) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} GANSSMeasurementParameters_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_multipathIndicator_5;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_GANSSMeasurementParameters;
extern asn_SET_OF_specifics_t asn_SPC_GANSSMeasurementParameters_specs_1;
extern asn_TYPE_member_t asn_MBR_GANSSMeasurementParameters_1[1];
extern asn_per_constraints_t asn_PER_type_GANSSMeasurementParameters_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _GANSSMeasurementParameters_H_ */
#include <asn_internal.h>
