/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "../../Skeletons/ASN_files/UMTS/rrc-25.331-r19.asn1"
 * 	`asn1c -fcompound-names -pdu=all`
 */

#include "HS-SCCH-LessInfo-r7.h"

static asn_oer_constraints_t asn_OER_type_hs_scchLessOperation_constr_2 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_hs_scchLessOperation_constr_2 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_hs_scchLessOperation_2[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct HS_SCCH_LessInfo_r7__hs_scchLessOperation, choice.Continue),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"continue"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct HS_SCCH_LessInfo_r7__hs_scchLessOperation, choice.newOperation),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_HS_SCCH_Less_NewOperation,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"newOperation"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_hs_scchLessOperation_tag2el_2[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* continue */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* newOperation */
};
static asn_CHOICE_specifics_t asn_SPC_hs_scchLessOperation_specs_2 = {
	sizeof(struct HS_SCCH_LessInfo_r7__hs_scchLessOperation),
	offsetof(struct HS_SCCH_LessInfo_r7__hs_scchLessOperation, _asn_ctx),
	offsetof(struct HS_SCCH_LessInfo_r7__hs_scchLessOperation, present),
	sizeof(((struct HS_SCCH_LessInfo_r7__hs_scchLessOperation *)0)->present),
	asn_MAP_hs_scchLessOperation_tag2el_2,
	2,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_hs_scchLessOperation_2 = {
	"hs-scchLessOperation",
	"hs-scchLessOperation",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ &asn_OER_type_hs_scchLessOperation_constr_2, &asn_PER_type_hs_scchLessOperation_constr_2, CHOICE_constraint },
	asn_MBR_hs_scchLessOperation_2,
	2,	/* Elements count */
	&asn_SPC_hs_scchLessOperation_specs_2	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_HS_SCCH_LessInfo_r7_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct HS_SCCH_LessInfo_r7, hs_scchLessOperation),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_hs_scchLessOperation_2,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"hs-scchLessOperation"
		},
};
static const ber_tlv_tag_t asn_DEF_HS_SCCH_LessInfo_r7_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_HS_SCCH_LessInfo_r7_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 } /* hs-scchLessOperation */
};
asn_SEQUENCE_specifics_t asn_SPC_HS_SCCH_LessInfo_r7_specs_1 = {
	sizeof(struct HS_SCCH_LessInfo_r7),
	offsetof(struct HS_SCCH_LessInfo_r7, _asn_ctx),
	asn_MAP_HS_SCCH_LessInfo_r7_tag2el_1,
	1,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_HS_SCCH_LessInfo_r7 = {
	"HS-SCCH-LessInfo-r7",
	"HS-SCCH-LessInfo-r7",
	&asn_OP_SEQUENCE,
	asn_DEF_HS_SCCH_LessInfo_r7_tags_1,
	sizeof(asn_DEF_HS_SCCH_LessInfo_r7_tags_1)
		/sizeof(asn_DEF_HS_SCCH_LessInfo_r7_tags_1[0]), /* 1 */
	asn_DEF_HS_SCCH_LessInfo_r7_tags_1,	/* Same as above */
	sizeof(asn_DEF_HS_SCCH_LessInfo_r7_tags_1)
		/sizeof(asn_DEF_HS_SCCH_LessInfo_r7_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_HS_SCCH_LessInfo_r7_1,
	1,	/* Elements count */
	&asn_SPC_HS_SCCH_LessInfo_r7_specs_1	/* Additional specs */
};

