/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "../../Skeletons/ASN_files/UMTS/rrc-25.331-r19.asn1"
 * 	`asn1c -fcompound-names -pdu=all`
 */

#ifndef	_InterFreqCellInfoList_r4_H_
#define	_InterFreqCellInfoList_r4_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct RemovedInterFreqCellList;
struct NewInterFreqCellList_r4;
struct CellsForInterFreqMeasList;

/* InterFreqCellInfoList-r4 */
typedef struct InterFreqCellInfoList_r4 {
	struct RemovedInterFreqCellList	*removedInterFreqCellList	/* OPTIONAL */;
	struct NewInterFreqCellList_r4	*newInterFreqCellList	/* OPTIONAL */;
	struct CellsForInterFreqMeasList	*cellsForInterFreqMeasList	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} InterFreqCellInfoList_r4_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_InterFreqCellInfoList_r4;
extern asn_SEQUENCE_specifics_t asn_SPC_InterFreqCellInfoList_r4_specs_1;
extern asn_TYPE_member_t asn_MBR_InterFreqCellInfoList_r4_1[3];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "RemovedInterFreqCellList.h"
#include "NewInterFreqCellList-r4.h"
#include "CellsForInterFreqMeasList.h"

#endif	/* _InterFreqCellInfoList_r4_H_ */
#include <asn_internal.h>
