/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "../../Skeletons/ASN_files/UMTS/rrc-25.331-r19.asn1"
 * 	`asn1c -fcompound-names -pdu=all`
 */

#ifndef	_InterRAT_UE_RadioAccessCapabilityList_H_
#define	_InterRAT_UE_RadioAccessCapabilityList_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct InterRAT_UE_RadioAccessCapability;

/* InterRAT-UE-RadioAccessCapabilityList */
typedef struct InterRAT_UE_RadioAccessCapabilityList {
	A_SEQUENCE_OF(struct InterRAT_UE_RadioAccessCapability) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} InterRAT_UE_RadioAccessCapabilityList_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_InterRAT_UE_RadioAccessCapabilityList;
extern asn_SET_OF_specifics_t asn_SPC_InterRAT_UE_RadioAccessCapabilityList_specs_1;
extern asn_TYPE_member_t asn_MBR_InterRAT_UE_RadioAccessCapabilityList_1[1];
extern asn_per_constraints_t asn_PER_type_InterRAT_UE_RadioAccessCapabilityList_constr_1;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "InterRAT-UE-RadioAccessCapability.h"

#endif	/* _InterRAT_UE_RadioAccessCapabilityList_H_ */
#include <asn_internal.h>
