/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Internode-definitions"
 * 	found in "../../Skeletons/ASN_files/UMTS/rrc-25.331-r19.asn1"
 * 	`asn1c -fcompound-names -pdu=all`
 */

#include "InterRATHandoverInfoWithInterRATCapabilities-r3.h"

static asn_oer_constraints_t asn_OER_type_InterRATHandoverInfoWithInterRATCapabilities_r3_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
asn_per_constraints_t asn_PER_type_InterRATHandoverInfoWithInterRATCapabilities_r3_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static const ber_tlv_tag_t asn_DEF_nonCriticalExtensions_tags_12[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SEQUENCE_specifics_t asn_SPC_nonCriticalExtensions_specs_12 = {
	sizeof(struct InterRATHandoverInfoWithInterRATCapabilities_r3__r3__v390NonCriticalExtensions__v690NonCriticalExtensions__v860NonCriticalExtensions__v920NonCriticalExtensions__nonCriticalExtensions),
	offsetof(struct InterRATHandoverInfoWithInterRATCapabilities_r3__r3__v390NonCriticalExtensions__v690NonCriticalExtensions__v860NonCriticalExtensions__v920NonCriticalExtensions__nonCriticalExtensions, _asn_ctx),
	0,	/* No top level tags */
	0,	/* No tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_nonCriticalExtensions_12 = {
	"nonCriticalExtensions",
	"nonCriticalExtensions",
	&asn_OP_SEQUENCE,
	asn_DEF_nonCriticalExtensions_tags_12,
	sizeof(asn_DEF_nonCriticalExtensions_tags_12)
		/sizeof(asn_DEF_nonCriticalExtensions_tags_12[0]) - 1, /* 1 */
	asn_DEF_nonCriticalExtensions_tags_12,	/* Same as above */
	sizeof(asn_DEF_nonCriticalExtensions_tags_12)
		/sizeof(asn_DEF_nonCriticalExtensions_tags_12[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	0, 0,	/* No members */
	&asn_SPC_nonCriticalExtensions_specs_12	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_v920NonCriticalExtensions_10[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct InterRATHandoverInfoWithInterRATCapabilities_r3__r3__v390NonCriticalExtensions__v690NonCriticalExtensions__v860NonCriticalExtensions__v920NonCriticalExtensions, interRATHandoverInfoWithInterRATCapabilities_v920ext),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_InterRATHandoverInfoWithInterRATCapabilities_v920ext_IEs,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"interRATHandoverInfoWithInterRATCapabilities-v920ext"
		},
	{ ATF_POINTER, 1, offsetof(struct InterRATHandoverInfoWithInterRATCapabilities_r3__r3__v390NonCriticalExtensions__v690NonCriticalExtensions__v860NonCriticalExtensions__v920NonCriticalExtensions, nonCriticalExtensions),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_nonCriticalExtensions_12,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"nonCriticalExtensions"
		},
};
static const int asn_MAP_v920NonCriticalExtensions_oms_10[] = { 1 };
static const ber_tlv_tag_t asn_DEF_v920NonCriticalExtensions_tags_10[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_v920NonCriticalExtensions_tag2el_10[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* interRATHandoverInfoWithInterRATCapabilities-v920ext */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* nonCriticalExtensions */
};
static asn_SEQUENCE_specifics_t asn_SPC_v920NonCriticalExtensions_specs_10 = {
	sizeof(struct InterRATHandoverInfoWithInterRATCapabilities_r3__r3__v390NonCriticalExtensions__v690NonCriticalExtensions__v860NonCriticalExtensions__v920NonCriticalExtensions),
	offsetof(struct InterRATHandoverInfoWithInterRATCapabilities_r3__r3__v390NonCriticalExtensions__v690NonCriticalExtensions__v860NonCriticalExtensions__v920NonCriticalExtensions, _asn_ctx),
	asn_MAP_v920NonCriticalExtensions_tag2el_10,
	2,	/* Count of tags in the map */
	asn_MAP_v920NonCriticalExtensions_oms_10,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_v920NonCriticalExtensions_10 = {
	"v920NonCriticalExtensions",
	"v920NonCriticalExtensions",
	&asn_OP_SEQUENCE,
	asn_DEF_v920NonCriticalExtensions_tags_10,
	sizeof(asn_DEF_v920NonCriticalExtensions_tags_10)
		/sizeof(asn_DEF_v920NonCriticalExtensions_tags_10[0]) - 1, /* 1 */
	asn_DEF_v920NonCriticalExtensions_tags_10,	/* Same as above */
	sizeof(asn_DEF_v920NonCriticalExtensions_tags_10)
		/sizeof(asn_DEF_v920NonCriticalExtensions_tags_10[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_v920NonCriticalExtensions_10,
	2,	/* Elements count */
	&asn_SPC_v920NonCriticalExtensions_specs_10	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_v860NonCriticalExtensions_8[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct InterRATHandoverInfoWithInterRATCapabilities_r3__r3__v390NonCriticalExtensions__v690NonCriticalExtensions__v860NonCriticalExtensions, interRATHandoverInfoWithInterRATCapabilities_v860ext),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_InterRATHandoverInfoWithInterRATCapabilities_v860ext_IEs,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"interRATHandoverInfoWithInterRATCapabilities-v860ext"
		},
	{ ATF_POINTER, 1, offsetof(struct InterRATHandoverInfoWithInterRATCapabilities_r3__r3__v390NonCriticalExtensions__v690NonCriticalExtensions__v860NonCriticalExtensions, v920NonCriticalExtensions),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_v920NonCriticalExtensions_10,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"v920NonCriticalExtensions"
		},
};
static const int asn_MAP_v860NonCriticalExtensions_oms_8[] = { 1 };
static const ber_tlv_tag_t asn_DEF_v860NonCriticalExtensions_tags_8[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_v860NonCriticalExtensions_tag2el_8[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* interRATHandoverInfoWithInterRATCapabilities-v860ext */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* v920NonCriticalExtensions */
};
static asn_SEQUENCE_specifics_t asn_SPC_v860NonCriticalExtensions_specs_8 = {
	sizeof(struct InterRATHandoverInfoWithInterRATCapabilities_r3__r3__v390NonCriticalExtensions__v690NonCriticalExtensions__v860NonCriticalExtensions),
	offsetof(struct InterRATHandoverInfoWithInterRATCapabilities_r3__r3__v390NonCriticalExtensions__v690NonCriticalExtensions__v860NonCriticalExtensions, _asn_ctx),
	asn_MAP_v860NonCriticalExtensions_tag2el_8,
	2,	/* Count of tags in the map */
	asn_MAP_v860NonCriticalExtensions_oms_8,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_v860NonCriticalExtensions_8 = {
	"v860NonCriticalExtensions",
	"v860NonCriticalExtensions",
	&asn_OP_SEQUENCE,
	asn_DEF_v860NonCriticalExtensions_tags_8,
	sizeof(asn_DEF_v860NonCriticalExtensions_tags_8)
		/sizeof(asn_DEF_v860NonCriticalExtensions_tags_8[0]) - 1, /* 1 */
	asn_DEF_v860NonCriticalExtensions_tags_8,	/* Same as above */
	sizeof(asn_DEF_v860NonCriticalExtensions_tags_8)
		/sizeof(asn_DEF_v860NonCriticalExtensions_tags_8[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_v860NonCriticalExtensions_8,
	2,	/* Elements count */
	&asn_SPC_v860NonCriticalExtensions_specs_8	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_v690NonCriticalExtensions_6[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct InterRATHandoverInfoWithInterRATCapabilities_r3__r3__v390NonCriticalExtensions__v690NonCriticalExtensions, interRATHandoverInfoWithInterRATCapabilities_v690ext),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_InterRATHandoverInfoWithInterRATCapabilities_v690ext_IEs,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"interRATHandoverInfoWithInterRATCapabilities-v690ext"
		},
	{ ATF_POINTER, 1, offsetof(struct InterRATHandoverInfoWithInterRATCapabilities_r3__r3__v390NonCriticalExtensions__v690NonCriticalExtensions, v860NonCriticalExtensions),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_v860NonCriticalExtensions_8,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"v860NonCriticalExtensions"
		},
};
static const int asn_MAP_v690NonCriticalExtensions_oms_6[] = { 1 };
static const ber_tlv_tag_t asn_DEF_v690NonCriticalExtensions_tags_6[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_v690NonCriticalExtensions_tag2el_6[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* interRATHandoverInfoWithInterRATCapabilities-v690ext */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* v860NonCriticalExtensions */
};
static asn_SEQUENCE_specifics_t asn_SPC_v690NonCriticalExtensions_specs_6 = {
	sizeof(struct InterRATHandoverInfoWithInterRATCapabilities_r3__r3__v390NonCriticalExtensions__v690NonCriticalExtensions),
	offsetof(struct InterRATHandoverInfoWithInterRATCapabilities_r3__r3__v390NonCriticalExtensions__v690NonCriticalExtensions, _asn_ctx),
	asn_MAP_v690NonCriticalExtensions_tag2el_6,
	2,	/* Count of tags in the map */
	asn_MAP_v690NonCriticalExtensions_oms_6,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_v690NonCriticalExtensions_6 = {
	"v690NonCriticalExtensions",
	"v690NonCriticalExtensions",
	&asn_OP_SEQUENCE,
	asn_DEF_v690NonCriticalExtensions_tags_6,
	sizeof(asn_DEF_v690NonCriticalExtensions_tags_6)
		/sizeof(asn_DEF_v690NonCriticalExtensions_tags_6[0]) - 1, /* 1 */
	asn_DEF_v690NonCriticalExtensions_tags_6,	/* Same as above */
	sizeof(asn_DEF_v690NonCriticalExtensions_tags_6)
		/sizeof(asn_DEF_v690NonCriticalExtensions_tags_6[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_v690NonCriticalExtensions_6,
	2,	/* Elements count */
	&asn_SPC_v690NonCriticalExtensions_specs_6	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_v390NonCriticalExtensions_4[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct InterRATHandoverInfoWithInterRATCapabilities_r3__r3__v390NonCriticalExtensions, interRATHandoverInfoWithInterRATCapabilities_v390ext),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_InterRATHandoverInfoWithInterRATCapabilities_v390ext_IEs,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"interRATHandoverInfoWithInterRATCapabilities-v390ext"
		},
	{ ATF_POINTER, 1, offsetof(struct InterRATHandoverInfoWithInterRATCapabilities_r3__r3__v390NonCriticalExtensions, v690NonCriticalExtensions),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_v690NonCriticalExtensions_6,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"v690NonCriticalExtensions"
		},
};
static const int asn_MAP_v390NonCriticalExtensions_oms_4[] = { 1 };
static const ber_tlv_tag_t asn_DEF_v390NonCriticalExtensions_tags_4[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_v390NonCriticalExtensions_tag2el_4[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* interRATHandoverInfoWithInterRATCapabilities-v390ext */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* v690NonCriticalExtensions */
};
static asn_SEQUENCE_specifics_t asn_SPC_v390NonCriticalExtensions_specs_4 = {
	sizeof(struct InterRATHandoverInfoWithInterRATCapabilities_r3__r3__v390NonCriticalExtensions),
	offsetof(struct InterRATHandoverInfoWithInterRATCapabilities_r3__r3__v390NonCriticalExtensions, _asn_ctx),
	asn_MAP_v390NonCriticalExtensions_tag2el_4,
	2,	/* Count of tags in the map */
	asn_MAP_v390NonCriticalExtensions_oms_4,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_v390NonCriticalExtensions_4 = {
	"v390NonCriticalExtensions",
	"v390NonCriticalExtensions",
	&asn_OP_SEQUENCE,
	asn_DEF_v390NonCriticalExtensions_tags_4,
	sizeof(asn_DEF_v390NonCriticalExtensions_tags_4)
		/sizeof(asn_DEF_v390NonCriticalExtensions_tags_4[0]) - 1, /* 1 */
	asn_DEF_v390NonCriticalExtensions_tags_4,	/* Same as above */
	sizeof(asn_DEF_v390NonCriticalExtensions_tags_4)
		/sizeof(asn_DEF_v390NonCriticalExtensions_tags_4[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_v390NonCriticalExtensions_4,
	2,	/* Elements count */
	&asn_SPC_v390NonCriticalExtensions_specs_4	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_r3_2[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct InterRATHandoverInfoWithInterRATCapabilities_r3__r3, interRATHandoverInfo_r3),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_InterRATHandoverInfoWithInterRATCapabilities_r3_IEs,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"interRATHandoverInfo-r3"
		},
	{ ATF_POINTER, 1, offsetof(struct InterRATHandoverInfoWithInterRATCapabilities_r3__r3, v390NonCriticalExtensions),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_v390NonCriticalExtensions_4,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"v390NonCriticalExtensions"
		},
};
static const int asn_MAP_r3_oms_2[] = { 1 };
static const ber_tlv_tag_t asn_DEF_r3_tags_2[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_r3_tag2el_2[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* interRATHandoverInfo-r3 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* v390NonCriticalExtensions */
};
static asn_SEQUENCE_specifics_t asn_SPC_r3_specs_2 = {
	sizeof(struct InterRATHandoverInfoWithInterRATCapabilities_r3__r3),
	offsetof(struct InterRATHandoverInfoWithInterRATCapabilities_r3__r3, _asn_ctx),
	asn_MAP_r3_tag2el_2,
	2,	/* Count of tags in the map */
	asn_MAP_r3_oms_2,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_r3_2 = {
	"r3",
	"r3",
	&asn_OP_SEQUENCE,
	asn_DEF_r3_tags_2,
	sizeof(asn_DEF_r3_tags_2)
		/sizeof(asn_DEF_r3_tags_2[0]) - 1, /* 1 */
	asn_DEF_r3_tags_2,	/* Same as above */
	sizeof(asn_DEF_r3_tags_2)
		/sizeof(asn_DEF_r3_tags_2[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_r3_2,
	2,	/* Elements count */
	&asn_SPC_r3_specs_2	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_criticalExtensions_tags_13[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SEQUENCE_specifics_t asn_SPC_criticalExtensions_specs_13 = {
	sizeof(struct InterRATHandoverInfoWithInterRATCapabilities_r3__criticalExtensions),
	offsetof(struct InterRATHandoverInfoWithInterRATCapabilities_r3__criticalExtensions, _asn_ctx),
	0,	/* No top level tags */
	0,	/* No tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_criticalExtensions_13 = {
	"criticalExtensions",
	"criticalExtensions",
	&asn_OP_SEQUENCE,
	asn_DEF_criticalExtensions_tags_13,
	sizeof(asn_DEF_criticalExtensions_tags_13)
		/sizeof(asn_DEF_criticalExtensions_tags_13[0]) - 1, /* 1 */
	asn_DEF_criticalExtensions_tags_13,	/* Same as above */
	sizeof(asn_DEF_criticalExtensions_tags_13)
		/sizeof(asn_DEF_criticalExtensions_tags_13[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	0, 0,	/* No members */
	&asn_SPC_criticalExtensions_specs_13	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_InterRATHandoverInfoWithInterRATCapabilities_r3_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct InterRATHandoverInfoWithInterRATCapabilities_r3, choice.r3),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		0,
		&asn_DEF_r3_2,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"r3"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct InterRATHandoverInfoWithInterRATCapabilities_r3, choice.criticalExtensions),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_criticalExtensions_13,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"criticalExtensions"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_InterRATHandoverInfoWithInterRATCapabilities_r3_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* r3 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* criticalExtensions */
};
asn_CHOICE_specifics_t asn_SPC_InterRATHandoverInfoWithInterRATCapabilities_r3_specs_1 = {
	sizeof(struct InterRATHandoverInfoWithInterRATCapabilities_r3),
	offsetof(struct InterRATHandoverInfoWithInterRATCapabilities_r3, _asn_ctx),
	offsetof(struct InterRATHandoverInfoWithInterRATCapabilities_r3, present),
	sizeof(((struct InterRATHandoverInfoWithInterRATCapabilities_r3 *)0)->present),
	asn_MAP_InterRATHandoverInfoWithInterRATCapabilities_r3_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_InterRATHandoverInfoWithInterRATCapabilities_r3 = {
	"InterRATHandoverInfoWithInterRATCapabilities-r3",
	"InterRATHandoverInfoWithInterRATCapabilities-r3",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ &asn_OER_type_InterRATHandoverInfoWithInterRATCapabilities_r3_constr_1, &asn_PER_type_InterRATHandoverInfoWithInterRATCapabilities_r3_constr_1, CHOICE_constraint },
	asn_MBR_InterRATHandoverInfoWithInterRATCapabilities_r3_1,
	2,	/* Elements count */
	&asn_SPC_InterRATHandoverInfoWithInterRATCapabilities_r3_specs_1	/* Additional specs */
};

