/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "../../Skeletons/ASN_files/UMTS/rrc-25.331-r19.asn1"
 * 	`asn1c -fcompound-names -pdu=all`
 */

#include "IntraFreqCellInfoList-r4.h"

asn_TYPE_member_t asn_MBR_IntraFreqCellInfoList_r4_1[] = {
	{ ATF_POINTER, 3, offsetof(struct IntraFreqCellInfoList_r4, removedIntraFreqCellList),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_RemovedIntraFreqCellList,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"removedIntraFreqCellList"
		},
	{ ATF_POINTER, 2, offsetof(struct IntraFreqCellInfoList_r4, newIntraFreqCellList),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NewIntraFreqCellList_r4,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"newIntraFreqCellList"
		},
	{ ATF_POINTER, 1, offsetof(struct IntraFreqCellInfoList_r4, cellsForIntraFreqMeasList),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CellsForIntraFreqMeasList,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"cellsForIntraFreqMeasList"
		},
};
static const int asn_MAP_IntraFreqCellInfoList_r4_oms_1[] = { 0, 1, 2 };
static const ber_tlv_tag_t asn_DEF_IntraFreqCellInfoList_r4_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_IntraFreqCellInfoList_r4_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* removedIntraFreqCellList */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* newIntraFreqCellList */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* cellsForIntraFreqMeasList */
};
asn_SEQUENCE_specifics_t asn_SPC_IntraFreqCellInfoList_r4_specs_1 = {
	sizeof(struct IntraFreqCellInfoList_r4),
	offsetof(struct IntraFreqCellInfoList_r4, _asn_ctx),
	asn_MAP_IntraFreqCellInfoList_r4_tag2el_1,
	3,	/* Count of tags in the map */
	asn_MAP_IntraFreqCellInfoList_r4_oms_1,	/* Optional members */
	3, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_IntraFreqCellInfoList_r4 = {
	"IntraFreqCellInfoList-r4",
	"IntraFreqCellInfoList-r4",
	&asn_OP_SEQUENCE,
	asn_DEF_IntraFreqCellInfoList_r4_tags_1,
	sizeof(asn_DEF_IntraFreqCellInfoList_r4_tags_1)
		/sizeof(asn_DEF_IntraFreqCellInfoList_r4_tags_1[0]), /* 1 */
	asn_DEF_IntraFreqCellInfoList_r4_tags_1,	/* Same as above */
	sizeof(asn_DEF_IntraFreqCellInfoList_r4_tags_1)
		/sizeof(asn_DEF_IntraFreqCellInfoList_r4_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_IntraFreqCellInfoList_r4_1,
	3,	/* Elements count */
	&asn_SPC_IntraFreqCellInfoList_r4_specs_1	/* Additional specs */
};

