/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "../../Skeletons/ASN_files/UMTS/rrc-25.331-r19.asn1"
 * 	`asn1c -fcompound-names -pdu=all`
 */

#ifndef	_IntraFreqReportingCriteria_r6_H_
#define	_IntraFreqReportingCriteria_r6_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct IntraFreqEventCriteriaList_r6;

/* IntraFreqReportingCriteria-r6 */
typedef struct IntraFreqReportingCriteria_r6 {
	struct IntraFreqEventCriteriaList_r6	*eventCriteriaList	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} IntraFreqReportingCriteria_r6_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_IntraFreqReportingCriteria_r6;
extern asn_SEQUENCE_specifics_t asn_SPC_IntraFreqReportingCriteria_r6_specs_1;
extern asn_TYPE_member_t asn_MBR_IntraFreqReportingCriteria_r6_1[1];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "IntraFreqEventCriteriaList-r6.h"

#endif	/* _IntraFreqReportingCriteria_r6_H_ */
#include <asn_internal.h>
