/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "PDU-definitions"
 * 	found in "../../Skeletons/ASN_files/UMTS/rrc-25.331-r19.asn1"
 * 	`asn1c -fcompound-names -pdu=all`
 */

#ifndef	_MeasurementReport_LaterNonCriticalExtensions_H_
#define	_MeasurementReport_LaterNonCriticalExtensions_H_


#include <asn_application.h>

/* Including external dependencies */
#include "MeasurementReport-vc50ext-IEs.h"
#include "MeasurementReport-vd20ext-IEs.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct MeasurementReport_ve30ext_IEs;

/* MeasurementReport-LaterNonCriticalExtensions */
typedef struct MeasurementReport_LaterNonCriticalExtensions {
	MeasurementReport_vc50ext_IEs_t	 measurementReport_vc50ext;
	struct MeasurementReport_LaterNonCriticalExtensions__vd20NonCriticalExtensions {
		MeasurementReport_vd20ext_IEs_t	 measurementReport_vd20ext;
		struct MeasurementReport_ve30ext_IEs	*ve30NonCriticalExtensions	/* OPTIONAL */;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *vd20NonCriticalExtensions;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MeasurementReport_LaterNonCriticalExtensions_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MeasurementReport_LaterNonCriticalExtensions;
extern asn_SEQUENCE_specifics_t asn_SPC_MeasurementReport_LaterNonCriticalExtensions_specs_1;
extern asn_TYPE_member_t asn_MBR_MeasurementReport_LaterNonCriticalExtensions_1[2];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "MeasurementReport-ve30ext-IEs.h"

#endif	/* _MeasurementReport_LaterNonCriticalExtensions_H_ */
#include <asn_internal.h>
