/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "../../Skeletons/ASN_files/UMTS/rrc-25.331-r19.asn1"
 * 	`asn1c -fcompound-names -pdu=all`
 */

#ifndef	_MeasurementCapability_ve30ext_H_
#define	_MeasurementCapability_ve30ext_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum MeasurementCapability_ve30ext__rrcEventsforUPHReporting {
	MeasurementCapability_ve30ext__rrcEventsforUPHReporting_true	= 0
} e_MeasurementCapability_ve30ext__rrcEventsforUPHReporting;
typedef enum MeasurementCapability_ve30ext__qoEMeasurementCollectionForStreamingServices {
	MeasurementCapability_ve30ext__qoEMeasurementCollectionForStreamingServices_true	= 0
} e_MeasurementCapability_ve30ext__qoEMeasurementCollectionForStreamingServices;

/* MeasurementCapability-ve30ext */
typedef struct MeasurementCapability_ve30ext {
	long	*rrcEventsforUPHReporting	/* OPTIONAL */;
	long	*qoEMeasurementCollectionForStreamingServices	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MeasurementCapability_ve30ext_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_rrcEventsforUPHReporting_2;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_qoEMeasurementCollectionForStreamingServices_4;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_MeasurementCapability_ve30ext;
extern asn_SEQUENCE_specifics_t asn_SPC_MeasurementCapability_ve30ext_specs_1;
extern asn_TYPE_member_t asn_MBR_MeasurementCapability_ve30ext_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _MeasurementCapability_ve30ext_H_ */
#include <asn_internal.h>
