/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "../../Skeletons/ASN_files/UMTS/rrc-25.331-r19.asn1"
 * 	`asn1c -fcompound-names -pdu=all`
 */

#ifndef	_MeasuredResults_v390ext_H_
#define	_MeasuredResults_v390ext_H_


#include <asn_application.h>

/* Including external dependencies */
#include "UE-Positioning-MeasuredResults-v390ext.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* MeasuredResults-v390ext */
typedef struct MeasuredResults_v390ext {
	UE_Positioning_MeasuredResults_v390ext_t	 ue_positioning_MeasuredResults_v390ext;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MeasuredResults_v390ext_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MeasuredResults_v390ext;
extern asn_SEQUENCE_specifics_t asn_SPC_MeasuredResults_v390ext_specs_1;
extern asn_TYPE_member_t asn_MBR_MeasuredResults_v390ext_1[1];

#ifdef __cplusplus
}
#endif

#endif	/* _MeasuredResults_v390ext_H_ */
#include <asn_internal.h>
