/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "../../Skeletons/ASN_files/UMTS/rrc-25.331-r19.asn1"
 * 	`asn1c -fcompound-names -pdu=all`
 */

#include "MeasuredResults-ve30ext.h"

static asn_oer_constraints_t asn_OER_type_MeasuredResults_ve30ext_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
asn_per_constraints_t asn_PER_type_MeasuredResults_ve30ext_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 0,  0,  0,  0 }	/* (0..0) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
asn_TYPE_member_t asn_MBR_MeasuredResults_ve30ext_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct MeasuredResults_ve30ext, choice.ueInternalMeasuredResults),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UE_InternalMeasuredResults_ve30ext,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ueInternalMeasuredResults"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_MeasuredResults_ve30ext_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 } /* ueInternalMeasuredResults */
};
asn_CHOICE_specifics_t asn_SPC_MeasuredResults_ve30ext_specs_1 = {
	sizeof(struct MeasuredResults_ve30ext),
	offsetof(struct MeasuredResults_ve30ext, _asn_ctx),
	offsetof(struct MeasuredResults_ve30ext, present),
	sizeof(((struct MeasuredResults_ve30ext *)0)->present),
	asn_MAP_MeasuredResults_ve30ext_tag2el_1,
	1,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_MeasuredResults_ve30ext = {
	"MeasuredResults-ve30ext",
	"MeasuredResults-ve30ext",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ &asn_OER_type_MeasuredResults_ve30ext_constr_1, &asn_PER_type_MeasuredResults_ve30ext_constr_1, CHOICE_constraint },
	asn_MBR_MeasuredResults_ve30ext_1,
	1,	/* Elements count */
	&asn_SPC_MeasuredResults_ve30ext_specs_1	/* Additional specs */
};

