/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "../../Skeletons/ASN_files/UMTS/rrc-25.331-r19.asn1"
 * 	`asn1c -fcompound-names -pdu=all`
 */

#ifndef	_MeasuredResults_ve30ext_H_
#define	_MeasuredResults_ve30ext_H_


#include <asn_application.h>

/* Including external dependencies */
#include "UE-InternalMeasuredResults-ve30ext.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum MeasuredResults_ve30ext_PR {
	MeasuredResults_ve30ext_PR_NOTHING,	/* No components present */
	MeasuredResults_ve30ext_PR_ueInternalMeasuredResults
} MeasuredResults_ve30ext_PR;

/* MeasuredResults-ve30ext */
typedef struct MeasuredResults_ve30ext {
	MeasuredResults_ve30ext_PR present;
	union MeasuredResults_ve30ext_u {
		UE_InternalMeasuredResults_ve30ext_t	 ueInternalMeasuredResults;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MeasuredResults_ve30ext_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MeasuredResults_ve30ext;
extern asn_CHOICE_specifics_t asn_SPC_MeasuredResults_ve30ext_specs_1;
extern asn_TYPE_member_t asn_MBR_MeasuredResults_ve30ext_1[1];
extern asn_per_constraints_t asn_PER_type_MeasuredResults_ve30ext_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _MeasuredResults_ve30ext_H_ */
#include <asn_internal.h>
