/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "../../Skeletons/ASN_files/UMTS/rrc-25.331-r19.asn1"
 * 	`asn1c -fcompound-names -pdu=all`
 */

#ifndef	_MIB_ValueTagExt_H_
#define	_MIB_ValueTagExt_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* MIB-ValueTagExt */
typedef long	 MIB_ValueTagExt_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_MIB_ValueTagExt_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_MIB_ValueTagExt;
asn_struct_free_f MIB_ValueTagExt_free;
asn_struct_print_f MIB_ValueTagExt_print;
asn_constr_check_f MIB_ValueTagExt_constraint;
ber_type_decoder_f MIB_ValueTagExt_decode_ber;
der_type_encoder_f MIB_ValueTagExt_encode_der;
xer_type_decoder_f MIB_ValueTagExt_decode_xer;
xer_type_encoder_f MIB_ValueTagExt_encode_xer;
oer_type_decoder_f MIB_ValueTagExt_decode_oer;
oer_type_encoder_f MIB_ValueTagExt_encode_oer;
per_type_decoder_f MIB_ValueTagExt_decode_uper;
per_type_encoder_f MIB_ValueTagExt_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _MIB_ValueTagExt_H_ */
#include <asn_internal.h>
