/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "../../Skeletons/ASN_files/UMTS/rrc-25.331-r19.asn1"
 * 	`asn1c -fcompound-names -pdu=all`
 */

#include "MultiflowCapabBandCombination.h"

static int
memb_numberOfCellsBandA_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 1 && value <= 6)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_numberOfFrequenciesBandA_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 1 && value <= 3)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_numberOfCellsBandB_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 1 && value <= 6)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_numberOfFrequenciesBandB_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 1 && value <= 3)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_oer_constraints_t asn_OER_memb_numberOfCellsBandA_constr_2 CC_NOTUSED = {
	{ 1, 1 }	/* (1..6) */,
	-1};
static asn_per_constraints_t asn_PER_memb_numberOfCellsBandA_constr_2 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 3,  3,  1,  6 }	/* (1..6) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_numberOfFrequenciesBandA_constr_3 CC_NOTUSED = {
	{ 1, 1 }	/* (1..3) */,
	-1};
static asn_per_constraints_t asn_PER_memb_numberOfFrequenciesBandA_constr_3 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 2,  2,  1,  3 }	/* (1..3) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_numberOfCellsBandB_constr_4 CC_NOTUSED = {
	{ 1, 1 }	/* (1..6) */,
	-1};
static asn_per_constraints_t asn_PER_memb_numberOfCellsBandB_constr_4 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 3,  3,  1,  6 }	/* (1..6) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_numberOfFrequenciesBandB_constr_5 CC_NOTUSED = {
	{ 1, 1 }	/* (1..3) */,
	-1};
static asn_per_constraints_t asn_PER_memb_numberOfFrequenciesBandB_constr_5 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 2,  2,  1,  3 }	/* (1..3) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
asn_TYPE_member_t asn_MBR_MultiflowCapabBandCombination_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct MultiflowCapabBandCombination, numberOfCellsBandA),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ &asn_OER_memb_numberOfCellsBandA_constr_2, &asn_PER_memb_numberOfCellsBandA_constr_2,  memb_numberOfCellsBandA_constraint_1 },
		0, 0, /* No default value */
		"numberOfCellsBandA"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct MultiflowCapabBandCombination, numberOfFrequenciesBandA),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ &asn_OER_memb_numberOfFrequenciesBandA_constr_3, &asn_PER_memb_numberOfFrequenciesBandA_constr_3,  memb_numberOfFrequenciesBandA_constraint_1 },
		0, 0, /* No default value */
		"numberOfFrequenciesBandA"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct MultiflowCapabBandCombination, numberOfCellsBandB),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ &asn_OER_memb_numberOfCellsBandB_constr_4, &asn_PER_memb_numberOfCellsBandB_constr_4,  memb_numberOfCellsBandB_constraint_1 },
		0, 0, /* No default value */
		"numberOfCellsBandB"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct MultiflowCapabBandCombination, numberOfFrequenciesBandB),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ &asn_OER_memb_numberOfFrequenciesBandB_constr_5, &asn_PER_memb_numberOfFrequenciesBandB_constr_5,  memb_numberOfFrequenciesBandB_constraint_1 },
		0, 0, /* No default value */
		"numberOfFrequenciesBandB"
		},
};
static const ber_tlv_tag_t asn_DEF_MultiflowCapabBandCombination_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_MultiflowCapabBandCombination_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* numberOfCellsBandA */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* numberOfFrequenciesBandA */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* numberOfCellsBandB */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 } /* numberOfFrequenciesBandB */
};
asn_SEQUENCE_specifics_t asn_SPC_MultiflowCapabBandCombination_specs_1 = {
	sizeof(struct MultiflowCapabBandCombination),
	offsetof(struct MultiflowCapabBandCombination, _asn_ctx),
	asn_MAP_MultiflowCapabBandCombination_tag2el_1,
	4,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_MultiflowCapabBandCombination = {
	"MultiflowCapabBandCombination",
	"MultiflowCapabBandCombination",
	&asn_OP_SEQUENCE,
	asn_DEF_MultiflowCapabBandCombination_tags_1,
	sizeof(asn_DEF_MultiflowCapabBandCombination_tags_1)
		/sizeof(asn_DEF_MultiflowCapabBandCombination_tags_1[0]), /* 1 */
	asn_DEF_MultiflowCapabBandCombination_tags_1,	/* Same as above */
	sizeof(asn_DEF_MultiflowCapabBandCombination_tags_1)
		/sizeof(asn_DEF_MultiflowCapabBandCombination_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_MultiflowCapabBandCombination_1,
	4,	/* Elements count */
	&asn_SPC_MultiflowCapabBandCombination_specs_1	/* Additional specs */
};

