/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "../../Skeletons/ASN_files/UMTS/rrc-25.331-r19.asn1"
 * 	`asn1c -fcompound-names -pdu=all`
 */

#ifndef	_NewInterFreqCell_r4_H_
#define	_NewInterFreqCell_r4_H_


#include <asn_application.h>

/* Including external dependencies */
#include "InterFreqCellID.h"
#include "CellInfo-r4.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct FrequencyInfo;

/* NewInterFreqCell-r4 */
typedef struct NewInterFreqCell_r4 {
	InterFreqCellID_t	*interFreqCellID	/* OPTIONAL */;
	struct FrequencyInfo	*frequencyInfo	/* OPTIONAL */;
	CellInfo_r4_t	 cellInfo;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NewInterFreqCell_r4_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NewInterFreqCell_r4;
extern asn_SEQUENCE_specifics_t asn_SPC_NewInterFreqCell_r4_specs_1;
extern asn_TYPE_member_t asn_MBR_NewInterFreqCell_r4_1[3];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "FrequencyInfo.h"

#endif	/* _NewInterFreqCell_r4_H_ */
#include <asn_internal.h>
