/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "../../Skeletons/ASN_files/UMTS/rrc-25.331-r19.asn1"
 * 	`asn1c -fcompound-names -pdu=all`
 */

#ifndef	_PDSCH_SysInfoList_SFN_LCR_r4_H_
#define	_PDSCH_SysInfoList_SFN_LCR_r4_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include "PDSCH-SysInfo-LCR-r4.h"
#include <constr_SEQUENCE.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct SFN_TimeInfo;

/* Forward definitions */
typedef struct PDSCH_SysInfoList_SFN_LCR_r4__Member {
	PDSCH_SysInfo_LCR_r4_t	 pdsch_SysInfo;
	struct SFN_TimeInfo	*sfn_TimeInfo	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PDSCH_SysInfoList_SFN_LCR_r4__Member;

/* PDSCH-SysInfoList-SFN-LCR-r4 */
typedef struct PDSCH_SysInfoList_SFN_LCR_r4 {
	A_SEQUENCE_OF(PDSCH_SysInfoList_SFN_LCR_r4__Member) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PDSCH_SysInfoList_SFN_LCR_r4_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PDSCH_SysInfoList_SFN_LCR_r4;
extern asn_SET_OF_specifics_t asn_SPC_PDSCH_SysInfoList_SFN_LCR_r4_specs_1;
extern asn_TYPE_member_t asn_MBR_PDSCH_SysInfoList_SFN_LCR_r4_1[1];
extern asn_per_constraints_t asn_PER_type_PDSCH_SysInfoList_SFN_LCR_r4_constr_1;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "SFN-TimeInfo.h"

#endif	/* _PDSCH_SysInfoList_SFN_LCR_r4_H_ */
#include <asn_internal.h>
