/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "../../Skeletons/ASN_files/UMTS/rrc-25.331-r19.asn1"
 * 	`asn1c -fcompound-names -pdu=all`
 */

#ifndef	_PRACH_PreambleForEnhancedUplinkExtWithWeight_H_
#define	_PRACH_PreambleForEnhancedUplinkExtWithWeight_H_


#include <asn_application.h>

/* Including external dependencies */
#include "PRACH-PreambleForEnhancedUplinkExt.h"
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* PRACH-PreambleForEnhancedUplinkExtWithWeight */
typedef struct PRACH_PreambleForEnhancedUplinkExtWithWeight {
	PRACH_PreambleForEnhancedUplinkExt_t	 prach_PreambleForEnhancedUplinkExt;
	long	*weight	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PRACH_PreambleForEnhancedUplinkExtWithWeight_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PRACH_PreambleForEnhancedUplinkExtWithWeight;
extern asn_SEQUENCE_specifics_t asn_SPC_PRACH_PreambleForEnhancedUplinkExtWithWeight_specs_1;
extern asn_TYPE_member_t asn_MBR_PRACH_PreambleForEnhancedUplinkExtWithWeight_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _PRACH_PreambleForEnhancedUplinkExtWithWeight_H_ */
#include <asn_internal.h>
