/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "../../Skeletons/ASN_files/UMTS/rrc-25.331-r19.asn1"
 * 	`asn1c -fcompound-names -pdu=all`
 */

#ifndef	_SchedulingInformationSIBSb2_H_
#define	_SchedulingInformationSIBSb2_H_


#include <asn_application.h>

/* Including external dependencies */
#include "SIBSb-TypeAndTagExtValueTag.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SchedulingInformationSIBSb2 */
typedef struct SchedulingInformationSIBSb2 {
	SIBSb_TypeAndTagExtValueTag_t	 sibSb_Type;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SchedulingInformationSIBSb2_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SchedulingInformationSIBSb2;
extern asn_SEQUENCE_specifics_t asn_SPC_SchedulingInformationSIBSb2_specs_1;
extern asn_TYPE_member_t asn_MBR_SchedulingInformationSIBSb2_1[1];

#ifdef __cplusplus
}
#endif

#endif	/* _SchedulingInformationSIBSb2_H_ */
#include <asn_internal.h>
