/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "../../Skeletons/ASN_files/UMTS/rrc-25.331-r19.asn1"
 * 	`asn1c -fcompound-names -pdu=all`
 */

#ifndef	_SF512_AndPilot_r12_H_
#define	_SF512_AndPilot_r12_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NULL.h>
#include "PilotBits128-r12.h"
#include "PilotBits256-r12.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SF512_AndPilot_r12_PR {
	SF512_AndPilot_r12_PR_NOTHING,	/* No components present */
	SF512_AndPilot_r12_PR_sfd4,
	SF512_AndPilot_r12_PR_sfd8,
	SF512_AndPilot_r12_PR_sfd16,
	SF512_AndPilot_r12_PR_sfd32,
	SF512_AndPilot_r12_PR_sfd64,
	SF512_AndPilot_r12_PR_sfd128,
	SF512_AndPilot_r12_PR_sfd256,
	SF512_AndPilot_r12_PR_sfd512
} SF512_AndPilot_r12_PR;

/* SF512-AndPilot-r12 */
typedef struct SF512_AndPilot_r12 {
	SF512_AndPilot_r12_PR present;
	union SF512_AndPilot_r12_u {
		NULL_t	 sfd4;
		NULL_t	 sfd8;
		NULL_t	 sfd16;
		NULL_t	 sfd32;
		NULL_t	 sfd64;
		PilotBits128_r12_t	 sfd128;
		PilotBits256_r12_t	 sfd256;
		NULL_t	 sfd512;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SF512_AndPilot_r12_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SF512_AndPilot_r12;
extern asn_CHOICE_specifics_t asn_SPC_SF512_AndPilot_r12_specs_1;
extern asn_TYPE_member_t asn_MBR_SF512_AndPilot_r12_1[8];
extern asn_per_constraints_t asn_PER_type_SF512_AndPilot_r12_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _SF512_AndPilot_r12_H_ */
#include <asn_internal.h>
