/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "../../Skeletons/ASN_files/UMTS/rrc-25.331-r19.asn1"
 * 	`asn1c -fcompound-names -pdu=all`
 */

#ifndef	_SysInfoType8_H_
#define	_SysInfoType8_H_


#include <asn_application.h>

/* Including external dependencies */
#include "CPCH-Parameters.h"
#include "CPCH-SetInfoList.h"
#include "CSICH-PowerOffset.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SysInfoType8 */
typedef struct SysInfoType8 {
	CPCH_Parameters_t	 dummy1;
	CPCH_SetInfoList_t	 dummy2;
	CSICH_PowerOffset_t	 dummy3;
	struct SysInfoType8__nonCriticalExtensions {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *nonCriticalExtensions;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SysInfoType8_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SysInfoType8;

#ifdef __cplusplus
}
#endif

#endif	/* _SysInfoType8_H_ */
#include <asn_internal.h>
