/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "../../Skeletons/ASN_files/UMTS/rrc-25.331-r19.asn1"
 * 	`asn1c -fcompound-names -pdu=all`
 */

#include "T1-ReleaseTimer.h"

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static asn_oer_constraints_t asn_OER_type_T1_ReleaseTimer_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
asn_per_constraints_t asn_PER_type_T1_ReleaseTimer_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 4,  4,  0,  15 }	/* (0..15) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static const asn_INTEGER_enum_map_t asn_MAP_T1_ReleaseTimer_value2enum_1[] = {
	{ 0,	4,	"rt10" },
	{ 1,	4,	"rt20" },
	{ 2,	4,	"rt30" },
	{ 3,	4,	"rt40" },
	{ 4,	4,	"rt50" },
	{ 5,	4,	"rt60" },
	{ 6,	4,	"rt70" },
	{ 7,	4,	"rt80" },
	{ 8,	4,	"rt90" },
	{ 9,	5,	"rt100" },
	{ 10,	5,	"rt120" },
	{ 11,	5,	"rt140" },
	{ 12,	5,	"rt160" },
	{ 13,	5,	"rt200" },
	{ 14,	5,	"rt300" },
	{ 15,	5,	"rt400" }
};
static const unsigned int asn_MAP_T1_ReleaseTimer_enum2value_1[] = {
	0,	/* rt10(0) */
	9,	/* rt100(9) */
	10,	/* rt120(10) */
	11,	/* rt140(11) */
	12,	/* rt160(12) */
	1,	/* rt20(1) */
	13,	/* rt200(13) */
	2,	/* rt30(2) */
	14,	/* rt300(14) */
	3,	/* rt40(3) */
	15,	/* rt400(15) */
	4,	/* rt50(4) */
	5,	/* rt60(5) */
	6,	/* rt70(6) */
	7,	/* rt80(7) */
	8	/* rt90(8) */
};
const asn_INTEGER_specifics_t asn_SPC_T1_ReleaseTimer_specs_1 = {
	asn_MAP_T1_ReleaseTimer_value2enum_1,	/* "tag" => N; sorted by tag */
	asn_MAP_T1_ReleaseTimer_enum2value_1,	/* N => "tag"; sorted by N */
	16,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_T1_ReleaseTimer_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
asn_TYPE_descriptor_t asn_DEF_T1_ReleaseTimer = {
	"T1-ReleaseTimer",
	"T1-ReleaseTimer",
	&asn_OP_NativeEnumerated,
	asn_DEF_T1_ReleaseTimer_tags_1,
	sizeof(asn_DEF_T1_ReleaseTimer_tags_1)
		/sizeof(asn_DEF_T1_ReleaseTimer_tags_1[0]), /* 1 */
	asn_DEF_T1_ReleaseTimer_tags_1,	/* Same as above */
	sizeof(asn_DEF_T1_ReleaseTimer_tags_1)
		/sizeof(asn_DEF_T1_ReleaseTimer_tags_1[0]), /* 1 */
	{ &asn_OER_type_T1_ReleaseTimer_constr_1, &asn_PER_type_T1_ReleaseTimer_constr_1, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_T1_ReleaseTimer_specs_1	/* Additional specs */
};

