/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "../../Skeletons/ASN_files/UMTS/rrc-25.331-r19.asn1"
 * 	`asn1c -fcompound-names -pdu=all`
 */

#ifndef	_TrafficVolumeMeasurementObjectList_H_
#define	_TrafficVolumeMeasurementObjectList_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct UL_TrCH_Identity;

/* TrafficVolumeMeasurementObjectList */
typedef struct TrafficVolumeMeasurementObjectList {
	A_SEQUENCE_OF(struct UL_TrCH_Identity) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TrafficVolumeMeasurementObjectList_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TrafficVolumeMeasurementObjectList;
extern asn_SET_OF_specifics_t asn_SPC_TrafficVolumeMeasurementObjectList_specs_1;
extern asn_TYPE_member_t asn_MBR_TrafficVolumeMeasurementObjectList_1[1];
extern asn_per_constraints_t asn_PER_type_TrafficVolumeMeasurementObjectList_constr_1;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "UL-TrCH-Identity.h"

#endif	/* _TrafficVolumeMeasurementObjectList_H_ */
#include <asn_internal.h>
