/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "../../Skeletons/ASN_files/UMTS/rrc-25.331-r19.asn1"
 * 	`asn1c -fcompound-names -pdu=all`
 */

#ifndef	_UE_InternalReportingCriteria_r14_H_
#define	_UE_InternalReportingCriteria_r14_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct UE_InternalEventParamList_r14;

/* UE-InternalReportingCriteria-r14 */
typedef struct UE_InternalReportingCriteria_r14 {
	struct UE_InternalEventParamList_r14	*ue_InternalEventParamList	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} UE_InternalReportingCriteria_r14_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UE_InternalReportingCriteria_r14;
extern asn_SEQUENCE_specifics_t asn_SPC_UE_InternalReportingCriteria_r14_specs_1;
extern asn_TYPE_member_t asn_MBR_UE_InternalReportingCriteria_r14_1[1];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "UE-InternalEventParamList-r14.h"

#endif	/* _UE_InternalReportingCriteria_r14_H_ */
#include <asn_internal.h>
