/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "../../Skeletons/ASN_files/UMTS/rrc-25.331-r19.asn1"
 * 	`asn1c -fcompound-names -pdu=all`
 */

#include "UE-RX-TX-ReportEntry.h"

asn_TYPE_member_t asn_MBR_UE_RX_TX_ReportEntry_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct UE_RX_TX_ReportEntry, primaryCPICH_Info),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PrimaryCPICH_Info,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"primaryCPICH-Info"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct UE_RX_TX_ReportEntry, ue_RX_TX_TimeDifferenceType1),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UE_RX_TX_TimeDifferenceType1,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ue-RX-TX-TimeDifferenceType1"
		},
};
static const ber_tlv_tag_t asn_DEF_UE_RX_TX_ReportEntry_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_UE_RX_TX_ReportEntry_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* primaryCPICH-Info */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* ue-RX-TX-TimeDifferenceType1 */
};
asn_SEQUENCE_specifics_t asn_SPC_UE_RX_TX_ReportEntry_specs_1 = {
	sizeof(struct UE_RX_TX_ReportEntry),
	offsetof(struct UE_RX_TX_ReportEntry, _asn_ctx),
	asn_MAP_UE_RX_TX_ReportEntry_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_UE_RX_TX_ReportEntry = {
	"UE-RX-TX-ReportEntry",
	"UE-RX-TX-ReportEntry",
	&asn_OP_SEQUENCE,
	asn_DEF_UE_RX_TX_ReportEntry_tags_1,
	sizeof(asn_DEF_UE_RX_TX_ReportEntry_tags_1)
		/sizeof(asn_DEF_UE_RX_TX_ReportEntry_tags_1[0]), /* 1 */
	asn_DEF_UE_RX_TX_ReportEntry_tags_1,	/* Same as above */
	sizeof(asn_DEF_UE_RX_TX_ReportEntry_tags_1)
		/sizeof(asn_DEF_UE_RX_TX_ReportEntry_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_UE_RX_TX_ReportEntry_1,
	2,	/* Elements count */
	&asn_SPC_UE_RX_TX_ReportEntry_specs_1	/* Additional specs */
};

