/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "../../Skeletons/ASN_files/UMTS/rrc-25.331-r19.asn1"
 * 	`asn1c -fcompound-names -pdu=all`
 */

#include "UL-EDCH-Information-ext.h"

static asn_oer_constraints_t asn_OER_type_UL_EDCH_Information_ext_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
asn_per_constraints_t asn_PER_type_UL_EDCH_Information_ext_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_tdd_3[] = {
	{ ATF_POINTER, 1, offsetof(struct UL_EDCH_Information_ext__tdd, non_ScheduledTransGrantInfo),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_Non_ScheduledTransGrantInfoTDD_ext,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"non-ScheduledTransGrantInfo"
		},
};
static const int asn_MAP_tdd_oms_3[] = { 0 };
static const ber_tlv_tag_t asn_DEF_tdd_tags_3[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_tdd_tag2el_3[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 } /* non-ScheduledTransGrantInfo */
};
static asn_SEQUENCE_specifics_t asn_SPC_tdd_specs_3 = {
	sizeof(struct UL_EDCH_Information_ext__tdd),
	offsetof(struct UL_EDCH_Information_ext__tdd, _asn_ctx),
	asn_MAP_tdd_tag2el_3,
	1,	/* Count of tags in the map */
	asn_MAP_tdd_oms_3,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_tdd_3 = {
	"tdd",
	"tdd",
	&asn_OP_SEQUENCE,
	asn_DEF_tdd_tags_3,
	sizeof(asn_DEF_tdd_tags_3)
		/sizeof(asn_DEF_tdd_tags_3[0]) - 1, /* 1 */
	asn_DEF_tdd_tags_3,	/* Same as above */
	sizeof(asn_DEF_tdd_tags_3)
		/sizeof(asn_DEF_tdd_tags_3[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_tdd_3,
	1,	/* Elements count */
	&asn_SPC_tdd_specs_3	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_UL_EDCH_Information_ext_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct UL_EDCH_Information_ext, choice.fdd),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"fdd"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct UL_EDCH_Information_ext, choice.tdd),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_tdd_3,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"tdd"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_UL_EDCH_Information_ext_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* fdd */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* tdd */
};
asn_CHOICE_specifics_t asn_SPC_UL_EDCH_Information_ext_specs_1 = {
	sizeof(struct UL_EDCH_Information_ext),
	offsetof(struct UL_EDCH_Information_ext, _asn_ctx),
	offsetof(struct UL_EDCH_Information_ext, present),
	sizeof(((struct UL_EDCH_Information_ext *)0)->present),
	asn_MAP_UL_EDCH_Information_ext_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_UL_EDCH_Information_ext = {
	"UL-EDCH-Information-ext",
	"UL-EDCH-Information-ext",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ &asn_OER_type_UL_EDCH_Information_ext_constr_1, &asn_PER_type_UL_EDCH_Information_ext_constr_1, CHOICE_constraint },
	asn_MBR_UL_EDCH_Information_ext_1,
	2,	/* Elements count */
	&asn_SPC_UL_EDCH_Information_ext_specs_1	/* Additional specs */
};

