/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "../../Skeletons/ASN_files/UMTS/rrc-25.331-r19.asn1"
 * 	`asn1c -fcompound-names -pdu=all`
 */

#include "UL-LogicalChannelMapping.h"

static asn_oer_constraints_t asn_OER_type_rlc_SizeList_constr_4 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_rlc_SizeList_constr_4 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 2,  2,  0,  2 }	/* (0..2) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_rlc_SizeList_4[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct UL_LogicalChannelMapping__rlc_SizeList, choice.allSizes),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"allSizes"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct UL_LogicalChannelMapping__rlc_SizeList, choice.configured),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"configured"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct UL_LogicalChannelMapping__rlc_SizeList, choice.explicitList),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RLC_SizeExplicitList,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"explicitList"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_rlc_SizeList_tag2el_4[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* allSizes */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* configured */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* explicitList */
};
static asn_CHOICE_specifics_t asn_SPC_rlc_SizeList_specs_4 = {
	sizeof(struct UL_LogicalChannelMapping__rlc_SizeList),
	offsetof(struct UL_LogicalChannelMapping__rlc_SizeList, _asn_ctx),
	offsetof(struct UL_LogicalChannelMapping__rlc_SizeList, present),
	sizeof(((struct UL_LogicalChannelMapping__rlc_SizeList *)0)->present),
	asn_MAP_rlc_SizeList_tag2el_4,
	3,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_rlc_SizeList_4 = {
	"rlc-SizeList",
	"rlc-SizeList",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ &asn_OER_type_rlc_SizeList_constr_4, &asn_PER_type_rlc_SizeList_constr_4, CHOICE_constraint },
	asn_MBR_rlc_SizeList_4,
	3,	/* Elements count */
	&asn_SPC_rlc_SizeList_specs_4	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_UL_LogicalChannelMapping_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct UL_LogicalChannelMapping, ul_TransportChannelType),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_UL_TransportChannelType,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ul-TransportChannelType"
		},
	{ ATF_POINTER, 1, offsetof(struct UL_LogicalChannelMapping, logicalChannelIdentity),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_LogicalChannelIdentity,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"logicalChannelIdentity"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct UL_LogicalChannelMapping, rlc_SizeList),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_rlc_SizeList_4,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"rlc-SizeList"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct UL_LogicalChannelMapping, mac_LogicalChannelPriority),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MAC_LogicalChannelPriority,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"mac-LogicalChannelPriority"
		},
};
static const int asn_MAP_UL_LogicalChannelMapping_oms_1[] = { 1 };
static const ber_tlv_tag_t asn_DEF_UL_LogicalChannelMapping_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_UL_LogicalChannelMapping_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* ul-TransportChannelType */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* logicalChannelIdentity */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* rlc-SizeList */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 } /* mac-LogicalChannelPriority */
};
asn_SEQUENCE_specifics_t asn_SPC_UL_LogicalChannelMapping_specs_1 = {
	sizeof(struct UL_LogicalChannelMapping),
	offsetof(struct UL_LogicalChannelMapping, _asn_ctx),
	asn_MAP_UL_LogicalChannelMapping_tag2el_1,
	4,	/* Count of tags in the map */
	asn_MAP_UL_LogicalChannelMapping_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_UL_LogicalChannelMapping = {
	"UL-LogicalChannelMapping",
	"UL-LogicalChannelMapping",
	&asn_OP_SEQUENCE,
	asn_DEF_UL_LogicalChannelMapping_tags_1,
	sizeof(asn_DEF_UL_LogicalChannelMapping_tags_1)
		/sizeof(asn_DEF_UL_LogicalChannelMapping_tags_1[0]), /* 1 */
	asn_DEF_UL_LogicalChannelMapping_tags_1,	/* Same as above */
	sizeof(asn_DEF_UL_LogicalChannelMapping_tags_1)
		/sizeof(asn_DEF_UL_LogicalChannelMapping_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_UL_LogicalChannelMapping_1,
	4,	/* Elements count */
	&asn_SPC_UL_LogicalChannelMapping_specs_1	/* Additional specs */
};

