/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "../../Skeletons/ASN_files/UMTS/rrc-25.331-r19.asn1"
 * 	`asn1c -fcompound-names -pdu=all`
 */

#include "UL-TS-ChannelisationCodeList-r7.h"

static asn_oer_constraints_t asn_OER_type_UL_TS_ChannelisationCodeList_r7_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..2)) */};
asn_per_constraints_t asn_PER_type_UL_TS_ChannelisationCodeList_r7_constr_1 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 1,  1,  1,  2 }	/* (SIZE(1..2)) */,
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_Member_2[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct UL_TS_ChannelisationCodeList_r7__Member, ul_TS_Channelisation_Code),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UL_TS_ChannelisationCode,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ul-TS-Channelisation-Code"
		},
	{ ATF_POINTER, 1, offsetof(struct UL_TS_ChannelisationCodeList_r7__Member, plcch_info),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PLCCH_Info,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"plcch-info"
		},
};
static const int asn_MAP_Member_oms_2[] = { 1 };
static const ber_tlv_tag_t asn_DEF_Member_tags_2[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_Member_tag2el_2[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* ul-TS-Channelisation-Code */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* plcch-info */
};
static asn_SEQUENCE_specifics_t asn_SPC_Member_specs_2 = {
	sizeof(struct UL_TS_ChannelisationCodeList_r7__Member),
	offsetof(struct UL_TS_ChannelisationCodeList_r7__Member, _asn_ctx),
	asn_MAP_Member_tag2el_2,
	2,	/* Count of tags in the map */
	asn_MAP_Member_oms_2,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_Member_2 = {
	"SEQUENCE",
	"SEQUENCE",
	&asn_OP_SEQUENCE,
	asn_DEF_Member_tags_2,
	sizeof(asn_DEF_Member_tags_2)
		/sizeof(asn_DEF_Member_tags_2[0]), /* 1 */
	asn_DEF_Member_tags_2,	/* Same as above */
	sizeof(asn_DEF_Member_tags_2)
		/sizeof(asn_DEF_Member_tags_2[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_Member_2,
	2,	/* Elements count */
	&asn_SPC_Member_specs_2	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_UL_TS_ChannelisationCodeList_r7_1[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_Member_2,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_UL_TS_ChannelisationCodeList_r7_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_UL_TS_ChannelisationCodeList_r7_specs_1 = {
	sizeof(struct UL_TS_ChannelisationCodeList_r7),
	offsetof(struct UL_TS_ChannelisationCodeList_r7, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_UL_TS_ChannelisationCodeList_r7 = {
	"UL-TS-ChannelisationCodeList-r7",
	"UL-TS-ChannelisationCodeList-r7",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_UL_TS_ChannelisationCodeList_r7_tags_1,
	sizeof(asn_DEF_UL_TS_ChannelisationCodeList_r7_tags_1)
		/sizeof(asn_DEF_UL_TS_ChannelisationCodeList_r7_tags_1[0]), /* 1 */
	asn_DEF_UL_TS_ChannelisationCodeList_r7_tags_1,	/* Same as above */
	sizeof(asn_DEF_UL_TS_ChannelisationCodeList_r7_tags_1)
		/sizeof(asn_DEF_UL_TS_ChannelisationCodeList_r7_tags_1[0]), /* 1 */
	{ &asn_OER_type_UL_TS_ChannelisationCodeList_r7_constr_1, &asn_PER_type_UL_TS_ChannelisationCodeList_r7_constr_1, SEQUENCE_OF_constraint },
	asn_MBR_UL_TS_ChannelisationCodeList_r7_1,
	1,	/* Single element */
	&asn_SPC_UL_TS_ChannelisationCodeList_r7_specs_1	/* Additional specs */
};

