/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "../../Skeletons/ASN_files/UMTS/rrc-25.331-r19.asn1"
 * 	`asn1c -fcompound-names -pdu=all`
 */

#ifndef	_USCH_TransportChannelsInfo_H_
#define	_USCH_TransportChannelsInfo_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include "TransportChannelIdentity.h"
#include "TransportFormatSet.h"
#include <constr_SEQUENCE.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward definitions */
typedef struct USCH_TransportChannelsInfo__Member {
	TransportChannelIdentity_t	 usch_TransportChannelIdentity;
	TransportFormatSet_t	 usch_TFS;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} USCH_TransportChannelsInfo__Member;

/* USCH-TransportChannelsInfo */
typedef struct USCH_TransportChannelsInfo {
	A_SEQUENCE_OF(USCH_TransportChannelsInfo__Member) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} USCH_TransportChannelsInfo_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_USCH_TransportChannelsInfo;
extern asn_SET_OF_specifics_t asn_SPC_USCH_TransportChannelsInfo_specs_1;
extern asn_TYPE_member_t asn_MBR_USCH_TransportChannelsInfo_1[1];
extern asn_per_constraints_t asn_PER_type_USCH_TransportChannelsInfo_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _USCH_TransportChannelsInfo_H_ */
#include <asn_internal.h>
