/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "PDU-definitions"
 * 	found in "../../Skeletons/ASN_files/UMTS/rrc-25.331-r19.asn1"
 * 	`asn1c -fcompound-names -pdu=all`
 */

#include "AssistanceDataDelivery-r3-IEs.h"

asn_TYPE_member_t asn_MBR_AssistanceDataDelivery_r3_IEs_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct AssistanceDataDelivery_r3_IEs, rrc_TransactionIdentifier),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RRC_TransactionIdentifier,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"rrc-TransactionIdentifier"
		},
	{ ATF_POINTER, 2, offsetof(struct AssistanceDataDelivery_r3_IEs, ue_positioning_GPS_AssistanceData),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UE_Positioning_GPS_AssistanceData,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ue-positioning-GPS-AssistanceData"
		},
	{ ATF_POINTER, 1, offsetof(struct AssistanceDataDelivery_r3_IEs, ue_positioning_OTDOA_AssistanceData_UEB),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UE_Positioning_OTDOA_AssistanceData_UEB,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ue-positioning-OTDOA-AssistanceData-UEB"
		},
};
static const int asn_MAP_AssistanceDataDelivery_r3_IEs_oms_1[] = { 1, 2 };
static const ber_tlv_tag_t asn_DEF_AssistanceDataDelivery_r3_IEs_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_AssistanceDataDelivery_r3_IEs_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* rrc-TransactionIdentifier */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* ue-positioning-GPS-AssistanceData */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* ue-positioning-OTDOA-AssistanceData-UEB */
};
asn_SEQUENCE_specifics_t asn_SPC_AssistanceDataDelivery_r3_IEs_specs_1 = {
	sizeof(struct AssistanceDataDelivery_r3_IEs),
	offsetof(struct AssistanceDataDelivery_r3_IEs, _asn_ctx),
	asn_MAP_AssistanceDataDelivery_r3_IEs_tag2el_1,
	3,	/* Count of tags in the map */
	asn_MAP_AssistanceDataDelivery_r3_IEs_oms_1,	/* Optional members */
	2, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_AssistanceDataDelivery_r3_IEs = {
	"AssistanceDataDelivery-r3-IEs",
	"AssistanceDataDelivery-r3-IEs",
	&asn_OP_SEQUENCE,
	asn_DEF_AssistanceDataDelivery_r3_IEs_tags_1,
	sizeof(asn_DEF_AssistanceDataDelivery_r3_IEs_tags_1)
		/sizeof(asn_DEF_AssistanceDataDelivery_r3_IEs_tags_1[0]), /* 1 */
	asn_DEF_AssistanceDataDelivery_r3_IEs_tags_1,	/* Same as above */
	sizeof(asn_DEF_AssistanceDataDelivery_r3_IEs_tags_1)
		/sizeof(asn_DEF_AssistanceDataDelivery_r3_IEs_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_AssistanceDataDelivery_r3_IEs_1,
	3,	/* Elements count */
	&asn_SPC_AssistanceDataDelivery_r3_IEs_specs_1	/* Additional specs */
};

