/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Class-definitions"
 * 	found in "../../Skeletons/ASN_files/UMTS/rrc-25.331-r19.asn1"
 * 	`asn1c -fcompound-names -pdu=all`
 */

#include "BCCH-FACH-MessageType.h"

static asn_oer_constraints_t asn_OER_type_BCCH_FACH_MessageType_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
asn_per_constraints_t asn_PER_type_BCCH_FACH_MessageType_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 2,  2,  0,  3 }	/* (0..3) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
asn_TYPE_member_t asn_MBR_BCCH_FACH_MessageType_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct BCCH_FACH_MessageType, choice.dummy),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SystemInformation_FACH,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"dummy"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct BCCH_FACH_MessageType, choice.systemInformationChangeIndication),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SystemInformationChangeIndication,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"systemInformationChangeIndication"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct BCCH_FACH_MessageType, choice.spare2),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"spare2"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct BCCH_FACH_MessageType, choice.spare1),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"spare1"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_BCCH_FACH_MessageType_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* dummy */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* systemInformationChangeIndication */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* spare2 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 } /* spare1 */
};
asn_CHOICE_specifics_t asn_SPC_BCCH_FACH_MessageType_specs_1 = {
	sizeof(struct BCCH_FACH_MessageType),
	offsetof(struct BCCH_FACH_MessageType, _asn_ctx),
	offsetof(struct BCCH_FACH_MessageType, present),
	sizeof(((struct BCCH_FACH_MessageType *)0)->present),
	asn_MAP_BCCH_FACH_MessageType_tag2el_1,
	4,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_BCCH_FACH_MessageType = {
	"BCCH-FACH-MessageType",
	"BCCH-FACH-MessageType",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ &asn_OER_type_BCCH_FACH_MessageType_constr_1, &asn_PER_type_BCCH_FACH_MessageType_constr_1, CHOICE_constraint },
	asn_MBR_BCCH_FACH_MessageType_1,
	4,	/* Elements count */
	&asn_SPC_BCCH_FACH_MessageType_specs_1	/* Additional specs */
};

