/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "../../Skeletons/ASN_files/UMTS/rrc-25.331-r19.asn1"
 * 	`asn1c -fcompound-names -pdu=all`
 */

#ifndef _CellInfo_H_
#define _CellInfo_H_


#include <asn_application.h>

/* Including external dependencies */
#include "CellIndividualOffset.h"
#include "PrimaryCCPCH-Info.h"
#include "PrimaryCCPCH-TX-Power.h"
#include "PrimaryCPICH-TX-Power.h"
#include <BOOLEAN.h>
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum CellInfo__modeSpecificInfo_PR {
    CellInfo__modeSpecificInfo_PR_NOTHING, /* No components present */
    CellInfo__modeSpecificInfo_PR_fdd,
    CellInfo__modeSpecificInfo_PR_tdd
} CellInfo__modeSpecificInfo_PR;

/* Forward declarations */
struct ReferenceTimeDifferenceToCell;
struct PrimaryCPICH_Info;
struct TimeslotInfoList;

/* CellInfo */
typedef struct CellInfo {
    CellIndividualOffset_t cellIndividualOffset /* DEFAULT 0 */;
    struct ReferenceTimeDifferenceToCell *referenceTimeDifferenceToCell /* OPTIONAL */;
    struct CellInfo__modeSpecificInfo {
        CellInfo__modeSpecificInfo_PR present;
        union CellInfo__modeSpecificInfo_u {
            struct CellInfo__modeSpecificInfo__fdd {
                struct PrimaryCPICH_Info *primaryCPICH_Info /* OPTIONAL */;
                PrimaryCPICH_TX_Power_t *primaryCPICH_TX_Power /* OPTIONAL */;
                BOOLEAN_t readSFN_Indicator;
                BOOLEAN_t tx_DiversityIndicator;

                /* Context for parsing across buffer boundaries */
                asn_struct_ctx_t _asn_ctx;
            } fdd;
            struct CellInfo__modeSpecificInfo__tdd {
                PrimaryCCPCH_Info_t primaryCCPCH_Info;
                PrimaryCCPCH_TX_Power_t *primaryCCPCH_TX_Power /* OPTIONAL */;
                struct TimeslotInfoList *timeslotInfoList /* OPTIONAL */;
                BOOLEAN_t readSFN_Indicator;

                /* Context for parsing across buffer boundaries */
                asn_struct_ctx_t _asn_ctx;
            } tdd;
        } choice;

        /* Context for parsing across buffer boundaries */
        asn_struct_ctx_t _asn_ctx;
    } modeSpecificInfo;

    /* Context for parsing across buffer boundaries */
    asn_struct_ctx_t _asn_ctx;
} CellInfo_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CellInfo;
extern asn_SEQUENCE_specifics_t asn_SPC_CellInfo_specs_1;
extern asn_TYPE_member_t asn_MBR_CellInfo_1[3];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "PrimaryCPICH-Info.h"
#include "ReferenceTimeDifferenceToCell.h"
#include "TimeslotInfoList.h"

#endif /* _CellInfo_H_ */
#include <asn_internal.h>
