/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "../../Skeletons/ASN_files/UMTS/rrc-25.331-r19.asn1"
 * 	`asn1c -fcompound-names -pdu=all`
 */

#ifndef _CellSelectReselectInfo_v590ext_H_
#define _CellSelectReselectInfo_v590ext_H_


#include <asn_application.h>

/* Including external dependencies */
#include "DeltaQrxlevmin.h"
#include "DeltaRSCP.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* CellSelectReselectInfo-v590ext */
typedef struct CellSelectReselectInfo_v590ext {
    DeltaQrxlevmin_t *deltaQrxlevmin /* OPTIONAL */;
    DeltaRSCP_t *deltaQhcs /* OPTIONAL */;

    /* Context for parsing across buffer boundaries */
    asn_struct_ctx_t _asn_ctx;
} CellSelectReselectInfo_v590ext_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CellSelectReselectInfo_v590ext;
extern asn_SEQUENCE_specifics_t asn_SPC_CellSelectReselectInfo_v590ext_specs_1;
extern asn_TYPE_member_t asn_MBR_CellSelectReselectInfo_v590ext_1[2];

#ifdef __cplusplus
}
#endif

#endif /* _CellSelectReselectInfo_v590ext_H_ */
#include <asn_internal.h>
