/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Internode-definitions"
 * 	found in "../../Skeletons/ASN_files/UMTS/rrc-25.331-r19.asn1"
 * 	`asn1c -fcompound-names -pdu=all`
 */

#ifndef _COUNT_C_List_H_
#define _COUNT_C_List_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct COUNT_CSingle;

/* COUNT-C-List */
typedef struct COUNT_C_List {
    A_SEQUENCE_OF(struct COUNT_CSingle)
    list;

    /* Context for parsing across buffer boundaries */
    asn_struct_ctx_t _asn_ctx;
} COUNT_C_List_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_COUNT_C_List;
extern asn_SET_OF_specifics_t asn_SPC_COUNT_C_List_specs_1;
extern asn_TYPE_member_t asn_MBR_COUNT_C_List_1[1];
extern asn_per_constraints_t asn_PER_type_COUNT_C_List_constr_1;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "COUNT-CSingle.h"

#endif /* _COUNT_C_List_H_ */
#include <asn_internal.h>
