/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "../../Skeletons/ASN_files/UMTS/rrc-25.331-r19.asn1"
 * 	`asn1c -fcompound-names -pdu=all`
 */

#include "EstablishmentCause.h"

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static asn_oer_constraints_t asn_OER_type_EstablishmentCause_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
asn_per_constraints_t asn_PER_type_EstablishmentCause_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 5,  5,  0,  31 }	/* (0..31) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static const asn_INTEGER_enum_map_t asn_MAP_EstablishmentCause_value2enum_1[] = {
	{ 0,	29,	"originatingConversationalCall" },
	{ 1,	24,	"originatingStreamingCall" },
	{ 2,	26,	"originatingInteractiveCall" },
	{ 3,	25,	"originatingBackgroundCall" },
	{ 4,	32,	"originatingSubscribedTrafficCall" },
	{ 5,	29,	"terminatingConversationalCall" },
	{ 6,	24,	"terminatingStreamingCall" },
	{ 7,	26,	"terminatingInteractiveCall" },
	{ 8,	25,	"terminatingBackgroundCall" },
	{ 9,	13,	"emergencyCall" },
	{ 10,	24,	"interRAT-CellReselection" },
	{ 11,	24,	"interRAT-CellChangeOrder" },
	{ 12,	12,	"registration" },
	{ 13,	6,	"detach" },
	{ 14,	33,	"originatingHighPrioritySignalling" },
	{ 15,	32,	"originatingLowPrioritySignalling" },
	{ 16,	20,	"callRe-establishment" },
	{ 17,	33,	"terminatingHighPrioritySignalling" },
	{ 18,	32,	"terminatingLowPrioritySignalling" },
	{ 19,	23,	"terminatingCauseUnknown" },
	{ 20,	14,	"mbms-Reception" },
	{ 21,	19,	"mbms-PTP-RB-Request" },
	{ 22,	19,	"delayTolerantAccess" },
	{ 23,	6,	"spare9" },
	{ 24,	6,	"spare8" },
	{ 25,	6,	"spare7" },
	{ 26,	6,	"spare6" },
	{ 27,	6,	"spare5" },
	{ 28,	6,	"spare4" },
	{ 29,	6,	"spare3" },
	{ 30,	6,	"spare2" },
	{ 31,	6,	"spare1" }
};
static const unsigned int asn_MAP_EstablishmentCause_enum2value_1[] = {
	16,	/* callRe-establishment(16) */
	22,	/* delayTolerantAccess(22) */
	13,	/* detach(13) */
	9,	/* emergencyCall(9) */
	11,	/* interRAT-CellChangeOrder(11) */
	10,	/* interRAT-CellReselection(10) */
	21,	/* mbms-PTP-RB-Request(21) */
	20,	/* mbms-Reception(20) */
	3,	/* originatingBackgroundCall(3) */
	0,	/* originatingConversationalCall(0) */
	14,	/* originatingHighPrioritySignalling(14) */
	2,	/* originatingInteractiveCall(2) */
	15,	/* originatingLowPrioritySignalling(15) */
	1,	/* originatingStreamingCall(1) */
	4,	/* originatingSubscribedTrafficCall(4) */
	12,	/* registration(12) */
	31,	/* spare1(31) */
	30,	/* spare2(30) */
	29,	/* spare3(29) */
	28,	/* spare4(28) */
	27,	/* spare5(27) */
	26,	/* spare6(26) */
	25,	/* spare7(25) */
	24,	/* spare8(24) */
	23,	/* spare9(23) */
	8,	/* terminatingBackgroundCall(8) */
	19,	/* terminatingCauseUnknown(19) */
	5,	/* terminatingConversationalCall(5) */
	17,	/* terminatingHighPrioritySignalling(17) */
	7,	/* terminatingInteractiveCall(7) */
	18,	/* terminatingLowPrioritySignalling(18) */
	6	/* terminatingStreamingCall(6) */
};
const asn_INTEGER_specifics_t asn_SPC_EstablishmentCause_specs_1 = {
	asn_MAP_EstablishmentCause_value2enum_1,	/* "tag" => N; sorted by tag */
	asn_MAP_EstablishmentCause_enum2value_1,	/* N => "tag"; sorted by N */
	32,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_EstablishmentCause_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
asn_TYPE_descriptor_t asn_DEF_EstablishmentCause = {
	"EstablishmentCause",
	"EstablishmentCause",
	&asn_OP_NativeEnumerated,
	asn_DEF_EstablishmentCause_tags_1,
	sizeof(asn_DEF_EstablishmentCause_tags_1)
		/sizeof(asn_DEF_EstablishmentCause_tags_1[0]), /* 1 */
	asn_DEF_EstablishmentCause_tags_1,	/* Same as above */
	sizeof(asn_DEF_EstablishmentCause_tags_1)
		/sizeof(asn_DEF_EstablishmentCause_tags_1[0]), /* 1 */
	{ &asn_OER_type_EstablishmentCause_constr_1, &asn_PER_type_EstablishmentCause_constr_1, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_EstablishmentCause_specs_1	/* Additional specs */
};

