/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "../../Skeletons/ASN_files/UMTS/rrc-25.331-r19.asn1"
 * 	`asn1c -fcompound-names -pdu=all`
 */

#ifndef _GANSSSatelliteInformation_r10_H_
#define _GANSSSatelliteInformation_r10_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BIT_STRING.h>
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ExtraDoppler;
struct AzimuthAndElevation_r10;

/* GANSSSatelliteInformation-r10 */
typedef struct GANSSSatelliteInformation_r10 {
    long ganssSatId;
    long dopplerZeroOrder;
    struct ExtraDoppler *extraDoppler /* OPTIONAL */;
    long codePhase;
    long integerCodePhase;
    BIT_STRING_t codePhaseSearchWindow;
    struct AzimuthAndElevation_r10 *azimuthandElevation /* OPTIONAL */;

    /* Context for parsing across buffer boundaries */
    asn_struct_ctx_t _asn_ctx;
} GANSSSatelliteInformation_r10_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_GANSSSatelliteInformation_r10;
extern asn_SEQUENCE_specifics_t asn_SPC_GANSSSatelliteInformation_r10_specs_1;
extern asn_TYPE_member_t asn_MBR_GANSSSatelliteInformation_r10_1[7];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "AzimuthAndElevation-r10.h"
#include "ExtraDoppler.h"

#endif /* _GANSSSatelliteInformation_r10_H_ */
#include <asn_internal.h>
