/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "../../Skeletons/ASN_files/UMTS/rrc-25.331-r19.asn1"
 * 	`asn1c -fcompound-names -pdu=all`
 */

#ifndef _HS_SCCH_LessTFSList_H_
#define _HS_SCCH_LessTFSList_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BOOLEAN.h>
#include <NativeInteger.h>
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward definitions */
typedef struct HS_SCCH_LessTFSList__Member {
    long hs_scch_LessTFSI;
    BOOLEAN_t hs_scch_LessSecondCodeSupport;

    /* Context for parsing across buffer boundaries */
    asn_struct_ctx_t _asn_ctx;
} HS_SCCH_LessTFSList__Member;

/* HS-SCCH-LessTFSList */
typedef struct HS_SCCH_LessTFSList {
    A_SEQUENCE_OF(HS_SCCH_LessTFSList__Member)
    list;

    /* Context for parsing across buffer boundaries */
    asn_struct_ctx_t _asn_ctx;
} HS_SCCH_LessTFSList_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_HS_SCCH_LessTFSList;
extern asn_SET_OF_specifics_t asn_SPC_HS_SCCH_LessTFSList_specs_1;
extern asn_TYPE_member_t asn_MBR_HS_SCCH_LessTFSList_1[1];
extern asn_per_constraints_t asn_PER_type_HS_SCCH_LessTFSList_constr_1;

#ifdef __cplusplus
}
#endif

#endif /* _HS_SCCH_LessTFSList_H_ */
#include <asn_internal.h>
