/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "PDU-definitions"
 * 	found in "../../Skeletons/ASN_files/UMTS/rrc-25.331-r19.asn1"
 * 	`asn1c -fcompound-names -pdu=all`
 */

#ifndef _InterRATHandoverInfo_vb50ext_IEs_H_
#define _InterRATHandoverInfo_vb50ext_IEs_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct UE_RadioAccessCapability_vb50ext;
struct UE_RadioAccessCapabilityComp2_vb50ext;
struct UE_RadioAccessCapabilityInfo_TDD128_vb50ext;

/* InterRATHandoverInfo-vb50ext-IEs */
typedef struct InterRATHandoverInfo_vb50ext_IEs {
    struct UE_RadioAccessCapability_vb50ext *ue_RadioAccessCapabilityInfo_vb50ext /* OPTIONAL */;
    struct UE_RadioAccessCapabilityComp2_vb50ext *ue_RadioAccessCapabilityComp2 /* OPTIONAL */;
    struct UE_RadioAccessCapabilityInfo_TDD128_vb50ext *ue_RadioAccessCapabilityInfo_TDD128 /* OPTIONAL */;

    /* Context for parsing across buffer boundaries */
    asn_struct_ctx_t _asn_ctx;
} InterRATHandoverInfo_vb50ext_IEs_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_InterRATHandoverInfo_vb50ext_IEs;
extern asn_SEQUENCE_specifics_t asn_SPC_InterRATHandoverInfo_vb50ext_IEs_specs_1;
extern asn_TYPE_member_t asn_MBR_InterRATHandoverInfo_vb50ext_IEs_1[3];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "UE-RadioAccessCapability-vb50ext.h"
#include "UE-RadioAccessCapabilityComp2-vb50ext.h"
#include "UE-RadioAccessCapabilityInfo-TDD128-vb50ext.h"

#endif /* _InterRATHandoverInfo_vb50ext_IEs_H_ */
#include <asn_internal.h>
