/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "../../Skeletons/ASN_files/UMTS/rrc-25.331-r19.asn1"
 * 	`asn1c -fcompound-names -pdu=all`
 */

#ifndef _InterRATReportingCriteria_r12_H_
#define _InterRATReportingCriteria_r12_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct InterRATEventList_r12;

/* InterRATReportingCriteria-r12 */
typedef struct InterRATReportingCriteria_r12 {
    struct InterRATEventList_r12 *interRATEventList /* OPTIONAL */;

    /* Context for parsing across buffer boundaries */
    asn_struct_ctx_t _asn_ctx;
} InterRATReportingCriteria_r12_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_InterRATReportingCriteria_r12;
extern asn_SEQUENCE_specifics_t asn_SPC_InterRATReportingCriteria_r12_specs_1;
extern asn_TYPE_member_t asn_MBR_InterRATReportingCriteria_r12_1[1];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "InterRATEventList-r12.h"

#endif /* _InterRATReportingCriteria_r12_H_ */
#include <asn_internal.h>
