/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "../../Skeletons/ASN_files/UMTS/rrc-25.331-r19.asn1"
 * 	`asn1c -fcompound-names -pdu=all`
 */

#ifndef _InterFreqEventResults_H_
#define _InterFreqEventResults_H_


#include <asn_application.h>

/* Including external dependencies */
#include "EventIDInterFreq.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct InterFreqCellList;

/* InterFreqEventResults */
typedef struct InterFreqEventResults {
    EventIDInterFreq_t eventID;
    struct InterFreqCellList *interFreqCellList /* OPTIONAL */;

    /* Context for parsing across buffer boundaries */
    asn_struct_ctx_t _asn_ctx;
} InterFreqEventResults_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_InterFreqEventResults;
extern asn_SEQUENCE_specifics_t asn_SPC_InterFreqEventResults_specs_1;
extern asn_TYPE_member_t asn_MBR_InterFreqEventResults_1[2];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "InterFreqCellList.h"

#endif /* _InterFreqEventResults_H_ */
#include <asn_internal.h>
