/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "../../Skeletons/ASN_files/UMTS/rrc-25.331-r19.asn1"
 * 	`asn1c -fcompound-names -pdu=all`
 */

#ifndef _IntraFreqCellInfoList_r10_H_
#define _IntraFreqCellInfoList_r10_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct RemovedIntraFreqCellList;
struct NewIntraFreqCellList_r10;
struct CellsForIntraFreqMeasList;
struct CSGIntraFreqCellInfoList;
struct IntraFreqSIAcquisition;

/* IntraFreqCellInfoList-r10 */
typedef struct IntraFreqCellInfoList_r10 {
    struct RemovedIntraFreqCellList *removedIntraFreqCellList /* OPTIONAL */;
    struct NewIntraFreqCellList_r10 *newIntraFreqCellList /* OPTIONAL */;
    struct CellsForIntraFreqMeasList *cellsForIntraFreqMeasList /* OPTIONAL */;
    struct CSGIntraFreqCellInfoList *cSGIntraFreqCellInfoList /* OPTIONAL */;
    struct IntraFreqSIAcquisition *intraFreqSIAcquisition /* OPTIONAL */;

    /* Context for parsing across buffer boundaries */
    asn_struct_ctx_t _asn_ctx;
} IntraFreqCellInfoList_r10_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_IntraFreqCellInfoList_r10;
extern asn_SEQUENCE_specifics_t asn_SPC_IntraFreqCellInfoList_r10_specs_1;
extern asn_TYPE_member_t asn_MBR_IntraFreqCellInfoList_r10_1[5];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "CSGIntraFreqCellInfoList.h"
#include "CellsForIntraFreqMeasList.h"
#include "IntraFreqSIAcquisition.h"
#include "NewIntraFreqCellList-r10.h"
#include "RemovedIntraFreqCellList.h"

#endif /* _IntraFreqCellInfoList_r10_H_ */
#include <asn_internal.h>
