/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "../../Skeletons/ASN_files/UMTS/rrc-25.331-r19.asn1"
 * 	`asn1c -fcompound-names -pdu=all`
 */

#include "LoggedConnectionEstablishmentFailureLocationInfo.h"

static asn_oer_constraints_t asn_OER_type_location_constr_2 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_location_constr_2 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 3,  3,  0,  4 }	/* (0..4) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_location_2[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct LoggedConnectionEstablishmentFailureLocationInfo__location, choice.ellipsoidPoint),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_EllipsoidPoint,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ellipsoidPoint"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LoggedConnectionEstablishmentFailureLocationInfo__location, choice.ellipsoidPointUncertCircle),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_EllipsoidPointUncertCircle,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ellipsoidPointUncertCircle"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LoggedConnectionEstablishmentFailureLocationInfo__location, choice.ellipsoidPointUncertEllipse),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_EllipsoidPointUncertEllipse,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ellipsoidPointUncertEllipse"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LoggedConnectionEstablishmentFailureLocationInfo__location, choice.ellipsoidPointAltitude),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_EllipsoidPointAltitude,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ellipsoidPointAltitude"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LoggedConnectionEstablishmentFailureLocationInfo__location, choice.ellipsoidPointAltitudeEllipse),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_EllipsoidPointAltitudeEllipsoide,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ellipsoidPointAltitudeEllipse"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_location_tag2el_2[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* ellipsoidPoint */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* ellipsoidPointUncertCircle */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* ellipsoidPointUncertEllipse */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* ellipsoidPointAltitude */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 } /* ellipsoidPointAltitudeEllipse */
};
static asn_CHOICE_specifics_t asn_SPC_location_specs_2 = {
	sizeof(struct LoggedConnectionEstablishmentFailureLocationInfo__location),
	offsetof(struct LoggedConnectionEstablishmentFailureLocationInfo__location, _asn_ctx),
	offsetof(struct LoggedConnectionEstablishmentFailureLocationInfo__location, present),
	sizeof(((struct LoggedConnectionEstablishmentFailureLocationInfo__location *)0)->present),
	asn_MAP_location_tag2el_2,
	5,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_location_2 = {
	"location",
	"location",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ &asn_OER_type_location_constr_2, &asn_PER_type_location_constr_2, CHOICE_constraint },
	asn_MBR_location_2,
	5,	/* Elements count */
	&asn_SPC_location_specs_2	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_LoggedConnectionEstablishmentFailureLocationInfo_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct LoggedConnectionEstablishmentFailureLocationInfo, location),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_location_2,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"location"
		},
	{ ATF_POINTER, 1, offsetof(struct LoggedConnectionEstablishmentFailureLocationInfo, horizontalVelocity),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_HorizontalVelocity,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"horizontalVelocity"
		},
};
static const int asn_MAP_LoggedConnectionEstablishmentFailureLocationInfo_oms_1[] = { 1 };
static const ber_tlv_tag_t asn_DEF_LoggedConnectionEstablishmentFailureLocationInfo_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_LoggedConnectionEstablishmentFailureLocationInfo_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* location */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* horizontalVelocity */
};
asn_SEQUENCE_specifics_t asn_SPC_LoggedConnectionEstablishmentFailureLocationInfo_specs_1 = {
	sizeof(struct LoggedConnectionEstablishmentFailureLocationInfo),
	offsetof(struct LoggedConnectionEstablishmentFailureLocationInfo, _asn_ctx),
	asn_MAP_LoggedConnectionEstablishmentFailureLocationInfo_tag2el_1,
	2,	/* Count of tags in the map */
	asn_MAP_LoggedConnectionEstablishmentFailureLocationInfo_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_LoggedConnectionEstablishmentFailureLocationInfo = {
	"LoggedConnectionEstablishmentFailureLocationInfo",
	"LoggedConnectionEstablishmentFailureLocationInfo",
	&asn_OP_SEQUENCE,
	asn_DEF_LoggedConnectionEstablishmentFailureLocationInfo_tags_1,
	sizeof(asn_DEF_LoggedConnectionEstablishmentFailureLocationInfo_tags_1)
		/sizeof(asn_DEF_LoggedConnectionEstablishmentFailureLocationInfo_tags_1[0]), /* 1 */
	asn_DEF_LoggedConnectionEstablishmentFailureLocationInfo_tags_1,	/* Same as above */
	sizeof(asn_DEF_LoggedConnectionEstablishmentFailureLocationInfo_tags_1)
		/sizeof(asn_DEF_LoggedConnectionEstablishmentFailureLocationInfo_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_LoggedConnectionEstablishmentFailureLocationInfo_1,
	2,	/* Elements count */
	&asn_SPC_LoggedConnectionEstablishmentFailureLocationInfo_specs_1	/* Additional specs */
};

