/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "../../Skeletons/ASN_files/UMTS/rrc-25.331-r19.asn1"
 * 	`asn1c -fcompound-names -pdu=all`
 */

#ifndef _MaxNumberOfTF_H_
#define _MaxNumberOfTF_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum MaxNumberOfTF {
    MaxNumberOfTF_tf32 = 0,
    MaxNumberOfTF_tf64 = 1,
    MaxNumberOfTF_tf128 = 2,
    MaxNumberOfTF_tf256 = 3,
    MaxNumberOfTF_tf512 = 4,
    MaxNumberOfTF_tf1024 = 5
} e_MaxNumberOfTF;

/* MaxNumberOfTF */
typedef long MaxNumberOfTF_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_MaxNumberOfTF_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_MaxNumberOfTF;
extern const asn_INTEGER_specifics_t asn_SPC_MaxNumberOfTF_specs_1;
asn_struct_free_f MaxNumberOfTF_free;
asn_struct_print_f MaxNumberOfTF_print;
asn_constr_check_f MaxNumberOfTF_constraint;
ber_type_decoder_f MaxNumberOfTF_decode_ber;
der_type_encoder_f MaxNumberOfTF_encode_der;
xer_type_decoder_f MaxNumberOfTF_decode_xer;
xer_type_encoder_f MaxNumberOfTF_encode_xer;
oer_type_decoder_f MaxNumberOfTF_decode_oer;
oer_type_encoder_f MaxNumberOfTF_encode_oer;
per_type_decoder_f MaxNumberOfTF_decode_uper;
per_type_encoder_f MaxNumberOfTF_encode_uper;

#ifdef __cplusplus
}
#endif

#endif /* _MaxNumberOfTF_H_ */
#include <asn_internal.h>
