/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "../../Skeletons/ASN_files/UMTS/rrc-25.331-r19.asn1"
 * 	`asn1c -fcompound-names -pdu=all`
 */

#ifndef _MaxReportedCellsOnRACH_H_
#define _MaxReportedCellsOnRACH_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum MaxReportedCellsOnRACH {
    MaxReportedCellsOnRACH_noReport = 0,
    MaxReportedCellsOnRACH_currentCell = 1,
    MaxReportedCellsOnRACH_currentAnd_1_BestNeighbour = 2,
    MaxReportedCellsOnRACH_currentAnd_2_BestNeighbour = 3,
    MaxReportedCellsOnRACH_currentAnd_3_BestNeighbour = 4,
    MaxReportedCellsOnRACH_currentAnd_4_BestNeighbour = 5,
    MaxReportedCellsOnRACH_currentAnd_5_BestNeighbour = 6,
    MaxReportedCellsOnRACH_currentAnd_6_BestNeighbour = 7
} e_MaxReportedCellsOnRACH;

/* MaxReportedCellsOnRACH */
typedef long MaxReportedCellsOnRACH_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_MaxReportedCellsOnRACH_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_MaxReportedCellsOnRACH;
extern const asn_INTEGER_specifics_t asn_SPC_MaxReportedCellsOnRACH_specs_1;
asn_struct_free_f MaxReportedCellsOnRACH_free;
asn_struct_print_f MaxReportedCellsOnRACH_print;
asn_constr_check_f MaxReportedCellsOnRACH_constraint;
ber_type_decoder_f MaxReportedCellsOnRACH_decode_ber;
der_type_encoder_f MaxReportedCellsOnRACH_encode_der;
xer_type_decoder_f MaxReportedCellsOnRACH_decode_xer;
xer_type_encoder_f MaxReportedCellsOnRACH_encode_xer;
oer_type_decoder_f MaxReportedCellsOnRACH_decode_oer;
oer_type_encoder_f MaxReportedCellsOnRACH_encode_oer;
per_type_decoder_f MaxReportedCellsOnRACH_decode_uper;
per_type_encoder_f MaxReportedCellsOnRACH_encode_uper;

#ifdef __cplusplus
}
#endif

#endif /* _MaxReportedCellsOnRACH_H_ */
#include <asn_internal.h>
