/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "../../Skeletons/ASN_files/UMTS/rrc-25.331-r19.asn1"
 * 	`asn1c -fcompound-names -pdu=all`
 */

#include "MBMS-TranspChInfoForCCTrCh-r6.h"

asn_TYPE_member_t asn_MBR_MBMS_TranspChInfoForCCTrCh_r6_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct MBMS_TranspChInfoForCCTrCh_r6, commonCCTrChIdentity),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MBMS_CommonCCTrChIdentity,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"commonCCTrChIdentity"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct MBMS_TranspChInfoForCCTrCh_r6, transportFormatCombinationSet),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_TFCS,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"transportFormatCombinationSet"
		},
};
static const ber_tlv_tag_t asn_DEF_MBMS_TranspChInfoForCCTrCh_r6_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_MBMS_TranspChInfoForCCTrCh_r6_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* commonCCTrChIdentity */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* transportFormatCombinationSet */
};
asn_SEQUENCE_specifics_t asn_SPC_MBMS_TranspChInfoForCCTrCh_r6_specs_1 = {
	sizeof(struct MBMS_TranspChInfoForCCTrCh_r6),
	offsetof(struct MBMS_TranspChInfoForCCTrCh_r6, _asn_ctx),
	asn_MAP_MBMS_TranspChInfoForCCTrCh_r6_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_MBMS_TranspChInfoForCCTrCh_r6 = {
	"MBMS-TranspChInfoForCCTrCh-r6",
	"MBMS-TranspChInfoForCCTrCh-r6",
	&asn_OP_SEQUENCE,
	asn_DEF_MBMS_TranspChInfoForCCTrCh_r6_tags_1,
	sizeof(asn_DEF_MBMS_TranspChInfoForCCTrCh_r6_tags_1)
		/sizeof(asn_DEF_MBMS_TranspChInfoForCCTrCh_r6_tags_1[0]), /* 1 */
	asn_DEF_MBMS_TranspChInfoForCCTrCh_r6_tags_1,	/* Same as above */
	sizeof(asn_DEF_MBMS_TranspChInfoForCCTrCh_r6_tags_1)
		/sizeof(asn_DEF_MBMS_TranspChInfoForCCTrCh_r6_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_MBMS_TranspChInfoForCCTrCh_r6_1,
	2,	/* Elements count */
	&asn_SPC_MBMS_TranspChInfoForCCTrCh_r6_specs_1	/* Additional specs */
};

