/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "../../Skeletons/ASN_files/UMTS/rrc-25.331-r19.asn1"
 * 	`asn1c -fcompound-names -pdu=all`
 */

#ifndef _MeasurementReleaseEnhancement_H_
#define _MeasurementReleaseEnhancement_H_


#include <asn_application.h>

/* Including external dependencies */
#include "MeasurementsToRelease.h"
#include <NULL.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum MeasurementReleaseEnhancement_PR {
    MeasurementReleaseEnhancement_PR_NOTHING, /* No components present */
    MeasurementReleaseEnhancement_PR_releaseAllMeasurements,
    MeasurementReleaseEnhancement_PR_releaseSomeMeasurements
} MeasurementReleaseEnhancement_PR;

/* MeasurementReleaseEnhancement */
typedef struct MeasurementReleaseEnhancement {
    MeasurementReleaseEnhancement_PR present;
    union MeasurementReleaseEnhancement_u {
        NULL_t releaseAllMeasurements;
        MeasurementsToRelease_t releaseSomeMeasurements;
    } choice;

    /* Context for parsing across buffer boundaries */
    asn_struct_ctx_t _asn_ctx;
} MeasurementReleaseEnhancement_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MeasurementReleaseEnhancement;
extern asn_CHOICE_specifics_t asn_SPC_MeasurementReleaseEnhancement_specs_1;
extern asn_TYPE_member_t asn_MBR_MeasurementReleaseEnhancement_1[2];
extern asn_per_constraints_t asn_PER_type_MeasurementReleaseEnhancement_constr_1;

#ifdef __cplusplus
}
#endif

#endif /* _MeasurementReleaseEnhancement_H_ */
#include <asn_internal.h>
