/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "../../Skeletons/ASN_files/UMTS/rrc-25.331-r19.asn1"
 * 	`asn1c -fcompound-names -pdu=all`
 */

#ifndef _MIMO_Parameters_r7_H_
#define _MIMO_Parameters_r7_H_


#include <asn_application.h>

/* Including external dependencies */
#include "MIMO-N-M-Ratio.h"
#include "MIMO-Operation.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct MIMO_PilotConfiguration;

/* MIMO-Parameters-r7 */
typedef struct MIMO_Parameters_r7 {
    MIMO_Operation_t mimoOperation;
    MIMO_N_M_Ratio_t *mimoN_M_Ratio /* OPTIONAL */;
    struct MIMO_PilotConfiguration *mimoPilotConfiguration /* OPTIONAL */;

    /* Context for parsing across buffer boundaries */
    asn_struct_ctx_t _asn_ctx;
} MIMO_Parameters_r7_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MIMO_Parameters_r7;
extern asn_SEQUENCE_specifics_t asn_SPC_MIMO_Parameters_r7_specs_1;
extern asn_TYPE_member_t asn_MBR_MIMO_Parameters_r7_1[3];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "MIMO-PilotConfiguration.h"

#endif /* _MIMO_Parameters_r7_H_ */
#include <asn_internal.h>
