/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "../../Skeletons/ASN_files/UMTS/rrc-25.331-r19.asn1"
 * 	`asn1c -fcompound-names -pdu=all`
 */

#ifndef _NewInterFreqCellList_v7b0ext_H_
#define _NewInterFreqCellList_v7b0ext_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct NewInterFreqCell_v7b0ext;

/* NewInterFreqCellList-v7b0ext */
typedef struct NewInterFreqCellList_v7b0ext {
    A_SEQUENCE_OF(struct NewInterFreqCell_v7b0ext)
    list;

    /* Context for parsing across buffer boundaries */
    asn_struct_ctx_t _asn_ctx;
} NewInterFreqCellList_v7b0ext_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NewInterFreqCellList_v7b0ext;
extern asn_SET_OF_specifics_t asn_SPC_NewInterFreqCellList_v7b0ext_specs_1;
extern asn_TYPE_member_t asn_MBR_NewInterFreqCellList_v7b0ext_1[1];
extern asn_per_constraints_t asn_PER_type_NewInterFreqCellList_v7b0ext_constr_1;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "NewInterFreqCell-v7b0ext.h"

#endif /* _NewInterFreqCellList_v7b0ext_H_ */
#include <asn_internal.h>
