/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "../../Skeletons/ASN_files/UMTS/rrc-25.331-r19.asn1"
 * 	`asn1c -fcompound-names -pdu=all`
 */

#ifndef _Non_ScheduledTransGrantInfoTDD_ext_H_
#define _Non_ScheduledTransGrantInfoTDD_ext_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NULL.h>
#include <NativeEnumerated.h>
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Non_ScheduledTransGrantInfoTDD_ext_PR {
    Non_ScheduledTransGrantInfoTDD_ext_PR_NOTHING, /* No components present */
    Non_ScheduledTransGrantInfoTDD_ext_PR_tdd384_768,
    Non_ScheduledTransGrantInfoTDD_ext_PR_tdd128
} Non_ScheduledTransGrantInfoTDD_ext_PR;
typedef enum Non_ScheduledTransGrantInfoTDD_ext__tdd128__t_SI_nst {
    Non_ScheduledTransGrantInfoTDD_ext__tdd128__t_SI_nst_everyEDCHTTI = 0,
    Non_ScheduledTransGrantInfoTDD_ext__tdd128__t_SI_nst_ms20 = 1,
    Non_ScheduledTransGrantInfoTDD_ext__tdd128__t_SI_nst_ms40 = 2,
    Non_ScheduledTransGrantInfoTDD_ext__tdd128__t_SI_nst_ms60 = 3,
    Non_ScheduledTransGrantInfoTDD_ext__tdd128__t_SI_nst_ms80 = 4,
    Non_ScheduledTransGrantInfoTDD_ext__tdd128__t_SI_nst_ms160 = 5,
    Non_ScheduledTransGrantInfoTDD_ext__tdd128__t_SI_nst_ms200 = 6
} e_Non_ScheduledTransGrantInfoTDD_ext__tdd128__t_SI_nst;

/* Non-ScheduledTransGrantInfoTDD-ext */
typedef struct Non_ScheduledTransGrantInfoTDD_ext {
    Non_ScheduledTransGrantInfoTDD_ext_PR present;
    union Non_ScheduledTransGrantInfoTDD_ext_u {
        NULL_t tdd384_768;
        struct Non_ScheduledTransGrantInfoTDD_ext__tdd128 {
            long *t_SI_nst /* OPTIONAL */;

            /* Context for parsing across buffer boundaries */
            asn_struct_ctx_t _asn_ctx;
        } tdd128;
    } choice;

    /* Context for parsing across buffer boundaries */
    asn_struct_ctx_t _asn_ctx;
} Non_ScheduledTransGrantInfoTDD_ext_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_t_SI_nst_4;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_Non_ScheduledTransGrantInfoTDD_ext;
extern asn_CHOICE_specifics_t asn_SPC_Non_ScheduledTransGrantInfoTDD_ext_specs_1;
extern asn_TYPE_member_t asn_MBR_Non_ScheduledTransGrantInfoTDD_ext_1[2];
extern asn_per_constraints_t asn_PER_type_Non_ScheduledTransGrantInfoTDD_ext_constr_1;

#ifdef __cplusplus
}
#endif

#endif /* _Non_ScheduledTransGrantInfoTDD_ext_H_ */
#include <asn_internal.h>
