/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "../../Skeletons/ASN_files/UMTS/rrc-25.331-r19.asn1"
 * 	`asn1c -fcompound-names -pdu=all`
 */

#ifndef _NumberOfTransportBlocks_H_
#define _NumberOfTransportBlocks_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NULL.h>
#include <NativeInteger.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NumberOfTransportBlocks_PR {
    NumberOfTransportBlocks_PR_NOTHING, /* No components present */
    NumberOfTransportBlocks_PR_zero,
    NumberOfTransportBlocks_PR_one,
    NumberOfTransportBlocks_PR_small,
    NumberOfTransportBlocks_PR_large
} NumberOfTransportBlocks_PR;

/* NumberOfTransportBlocks */
typedef struct NumberOfTransportBlocks {
    NumberOfTransportBlocks_PR present;
    union NumberOfTransportBlocks_u {
        NULL_t zero;
        NULL_t one;
        long small;
        long large;
    } choice;

    /* Context for parsing across buffer boundaries */
    asn_struct_ctx_t _asn_ctx;
} NumberOfTransportBlocks_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NumberOfTransportBlocks;
extern asn_CHOICE_specifics_t asn_SPC_NumberOfTransportBlocks_specs_1;
extern asn_TYPE_member_t asn_MBR_NumberOfTransportBlocks_1[4];
extern asn_per_constraints_t asn_PER_type_NumberOfTransportBlocks_constr_1;

#ifdef __cplusplus
}
#endif

#endif /* _NumberOfTransportBlocks_H_ */
#include <asn_internal.h>
