/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "../../Skeletons/ASN_files/UMTS/rrc-25.331-r19.asn1"
 * 	`asn1c -fcompound-names -pdu=all`
 */

#ifndef _PhysicalChannelCapability_H_
#define _PhysicalChannelCapability_H_


#include <asn_application.h>

/* Including external dependencies */
#include "DL-PhysChCapabilityFDD.h"
#include "DL-PhysChCapabilityTDD.h"
#include "UL-PhysChCapabilityFDD.h"
#include "UL-PhysChCapabilityTDD.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* PhysicalChannelCapability */
typedef struct PhysicalChannelCapability {
    struct PhysicalChannelCapability__fddPhysChCapability {
        DL_PhysChCapabilityFDD_t downlinkPhysChCapability;
        UL_PhysChCapabilityFDD_t uplinkPhysChCapability;

        /* Context for parsing across buffer boundaries */
        asn_struct_ctx_t _asn_ctx;
    } *fddPhysChCapability;
    struct PhysicalChannelCapability__tddPhysChCapability {
        DL_PhysChCapabilityTDD_t downlinkPhysChCapability;
        UL_PhysChCapabilityTDD_t uplinkPhysChCapability;

        /* Context for parsing across buffer boundaries */
        asn_struct_ctx_t _asn_ctx;
    } *tddPhysChCapability;

    /* Context for parsing across buffer boundaries */
    asn_struct_ctx_t _asn_ctx;
} PhysicalChannelCapability_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PhysicalChannelCapability;
extern asn_SEQUENCE_specifics_t asn_SPC_PhysicalChannelCapability_specs_1;
extern asn_TYPE_member_t asn_MBR_PhysicalChannelCapability_1[2];

#ifdef __cplusplus
}
#endif

#endif /* _PhysicalChannelCapability_H_ */
#include <asn_internal.h>
