/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "../../Skeletons/ASN_files/UMTS/rrc-25.331-r19.asn1"
 * 	`asn1c -fcompound-names -pdu=all`
 */

#ifndef _RB_InformationReconfig_H_
#define _RB_InformationReconfig_H_


#include <asn_application.h>

/* Including external dependencies */
#include "PDCP-SN-Info.h"
#include "RB-Identity.h"
#include "RB-StopContinue.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct PDCP_InfoReconfig;
struct RLC_Info;
struct RB_MappingInfo;

/* RB-InformationReconfig */
typedef struct RB_InformationReconfig {
    RB_Identity_t rb_Identity;
    struct PDCP_InfoReconfig *pdcp_Info /* OPTIONAL */;
    PDCP_SN_Info_t *pdcp_SN_Info /* OPTIONAL */;
    struct RLC_Info *rlc_Info /* OPTIONAL */;
    struct RB_MappingInfo *rb_MappingInfo /* OPTIONAL */;
    RB_StopContinue_t *rb_StopContinue /* OPTIONAL */;

    /* Context for parsing across buffer boundaries */
    asn_struct_ctx_t _asn_ctx;
} RB_InformationReconfig_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RB_InformationReconfig;
extern asn_SEQUENCE_specifics_t asn_SPC_RB_InformationReconfig_specs_1;
extern asn_TYPE_member_t asn_MBR_RB_InformationReconfig_1[6];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "PDCP-InfoReconfig.h"
#include "RB-MappingInfo.h"
#include "RLC-Info.h"

#endif /* _RB_InformationReconfig_H_ */
#include <asn_internal.h>
