/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "../../Skeletons/ASN_files/UMTS/rrc-25.331-r19.asn1"
 * 	`asn1c -fcompound-names -pdu=all`
 */

#ifndef _RB_InformationAffected_r7_H_
#define _RB_InformationAffected_r7_H_


#include <asn_application.h>

/* Including external dependencies */
#include "RB-Identity.h"
#include "RB-MappingInfo-r7.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* RB-InformationAffected-r7 */
typedef struct RB_InformationAffected_r7 {
    RB_Identity_t rb_Identity;
    RB_MappingInfo_r7_t rb_MappingInfo;

    /* Context for parsing across buffer boundaries */
    asn_struct_ctx_t _asn_ctx;
} RB_InformationAffected_r7_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RB_InformationAffected_r7;
extern asn_SEQUENCE_specifics_t asn_SPC_RB_InformationAffected_r7_specs_1;
extern asn_TYPE_member_t asn_MBR_RB_InformationAffected_r7_1[2];

#ifdef __cplusplus
}
#endif

#endif /* _RB_InformationAffected_r7_H_ */
#include <asn_internal.h>
