/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "../../Skeletons/ASN_files/UMTS/rrc-25.331-r19.asn1"
 * 	`asn1c -fcompound-names -pdu=all`
 */

#ifndef _ReportingRange_H_
#define _ReportingRange_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ReportingRange */
typedef long ReportingRange_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_ReportingRange_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ReportingRange;
asn_struct_free_f ReportingRange_free;
asn_struct_print_f ReportingRange_print;
asn_constr_check_f ReportingRange_constraint;
ber_type_decoder_f ReportingRange_decode_ber;
der_type_encoder_f ReportingRange_encode_der;
xer_type_decoder_f ReportingRange_decode_xer;
xer_type_encoder_f ReportingRange_encode_xer;
oer_type_decoder_f ReportingRange_decode_oer;
oer_type_encoder_f ReportingRange_encode_oer;
per_type_decoder_f ReportingRange_decode_uper;
per_type_encoder_f ReportingRange_encode_uper;

#ifdef __cplusplus
}
#endif

#endif /* _ReportingRange_H_ */
#include <asn_internal.h>
