/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "../../Skeletons/ASN_files/UMTS/rrc-25.331-r19.asn1"
 * 	`asn1c -fcompound-names -pdu=all`
 */

#include "RF-Capability.h"

static asn_TYPE_member_t asn_MBR_fddRF_Capability_2[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct RF_Capability__fddRF_Capability, ue_PowerClass),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UE_PowerClass,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ue-PowerClass"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RF_Capability__fddRF_Capability, txRxFrequencySeparation),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TxRxFrequencySeparation,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"txRxFrequencySeparation"
		},
};
static const ber_tlv_tag_t asn_DEF_fddRF_Capability_tags_2[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_fddRF_Capability_tag2el_2[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* ue-PowerClass */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* txRxFrequencySeparation */
};
static asn_SEQUENCE_specifics_t asn_SPC_fddRF_Capability_specs_2 = {
	sizeof(struct RF_Capability__fddRF_Capability),
	offsetof(struct RF_Capability__fddRF_Capability, _asn_ctx),
	asn_MAP_fddRF_Capability_tag2el_2,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_fddRF_Capability_2 = {
	"fddRF-Capability",
	"fddRF-Capability",
	&asn_OP_SEQUENCE,
	asn_DEF_fddRF_Capability_tags_2,
	sizeof(asn_DEF_fddRF_Capability_tags_2)
		/sizeof(asn_DEF_fddRF_Capability_tags_2[0]) - 1, /* 1 */
	asn_DEF_fddRF_Capability_tags_2,	/* Same as above */
	sizeof(asn_DEF_fddRF_Capability_tags_2)
		/sizeof(asn_DEF_fddRF_Capability_tags_2[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_fddRF_Capability_2,
	2,	/* Elements count */
	&asn_SPC_fddRF_Capability_specs_2	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_tddRF_Capability_5[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct RF_Capability__tddRF_Capability, ue_PowerClass),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UE_PowerClass,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ue-PowerClass"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RF_Capability__tddRF_Capability, radioFrequencyTDDBandList),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RadioFrequencyBandTDDList,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"radioFrequencyTDDBandList"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RF_Capability__tddRF_Capability, chipRateCapability),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ChipRateCapability,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"chipRateCapability"
		},
};
static const ber_tlv_tag_t asn_DEF_tddRF_Capability_tags_5[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_tddRF_Capability_tag2el_5[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* ue-PowerClass */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* radioFrequencyTDDBandList */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* chipRateCapability */
};
static asn_SEQUENCE_specifics_t asn_SPC_tddRF_Capability_specs_5 = {
	sizeof(struct RF_Capability__tddRF_Capability),
	offsetof(struct RF_Capability__tddRF_Capability, _asn_ctx),
	asn_MAP_tddRF_Capability_tag2el_5,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_tddRF_Capability_5 = {
	"tddRF-Capability",
	"tddRF-Capability",
	&asn_OP_SEQUENCE,
	asn_DEF_tddRF_Capability_tags_5,
	sizeof(asn_DEF_tddRF_Capability_tags_5)
		/sizeof(asn_DEF_tddRF_Capability_tags_5[0]) - 1, /* 1 */
	asn_DEF_tddRF_Capability_tags_5,	/* Same as above */
	sizeof(asn_DEF_tddRF_Capability_tags_5)
		/sizeof(asn_DEF_tddRF_Capability_tags_5[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_tddRF_Capability_5,
	3,	/* Elements count */
	&asn_SPC_tddRF_Capability_specs_5	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_RF_Capability_1[] = {
	{ ATF_POINTER, 2, offsetof(struct RF_Capability, fddRF_Capability),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		0,
		&asn_DEF_fddRF_Capability_2,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"fddRF-Capability"
		},
	{ ATF_POINTER, 1, offsetof(struct RF_Capability, tddRF_Capability),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_tddRF_Capability_5,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"tddRF-Capability"
		},
};
static const int asn_MAP_RF_Capability_oms_1[] = { 0, 1 };
static const ber_tlv_tag_t asn_DEF_RF_Capability_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_RF_Capability_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* fddRF-Capability */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* tddRF-Capability */
};
asn_SEQUENCE_specifics_t asn_SPC_RF_Capability_specs_1 = {
	sizeof(struct RF_Capability),
	offsetof(struct RF_Capability, _asn_ctx),
	asn_MAP_RF_Capability_tag2el_1,
	2,	/* Count of tags in the map */
	asn_MAP_RF_Capability_oms_1,	/* Optional members */
	2, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_RF_Capability = {
	"RF-Capability",
	"RF-Capability",
	&asn_OP_SEQUENCE,
	asn_DEF_RF_Capability_tags_1,
	sizeof(asn_DEF_RF_Capability_tags_1)
		/sizeof(asn_DEF_RF_Capability_tags_1[0]), /* 1 */
	asn_DEF_RF_Capability_tags_1,	/* Same as above */
	sizeof(asn_DEF_RF_Capability_tags_1)
		/sizeof(asn_DEF_RF_Capability_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_RF_Capability_1,
	2,	/* Elements count */
	&asn_SPC_RF_Capability_specs_1	/* Additional specs */
};

