/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "../../Skeletons/ASN_files/UMTS/rrc-25.331-r19.asn1"
 * 	`asn1c -fcompound-names -pdu=all`
 */

#ifndef _RL_AdditionInformationList_v890ext_H_
#define _RL_AdditionInformationList_v890ext_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct RL_AdditionInformation_v890ext;

/* RL-AdditionInformationList-v890ext */
typedef struct RL_AdditionInformationList_v890ext {
    A_SEQUENCE_OF(struct RL_AdditionInformation_v890ext)
    list;

    /* Context for parsing across buffer boundaries */
    asn_struct_ctx_t _asn_ctx;
} RL_AdditionInformationList_v890ext_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RL_AdditionInformationList_v890ext;
extern asn_SET_OF_specifics_t asn_SPC_RL_AdditionInformationList_v890ext_specs_1;
extern asn_TYPE_member_t asn_MBR_RL_AdditionInformationList_v890ext_1[1];
extern asn_per_constraints_t asn_PER_type_RL_AdditionInformationList_v890ext_constr_1;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "RL-AdditionInformation-v890ext.h"

#endif /* _RL_AdditionInformationList_v890ext_H_ */
#include <asn_internal.h>
