/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "../../Skeletons/ASN_files/UMTS/rrc-25.331-r19.asn1"
 * 	`asn1c -fcompound-names -pdu=all`
 */

#ifndef _RLC_InfoChoice_r5_H_
#define _RLC_InfoChoice_r5_H_


#include <asn_application.h>

/* Including external dependencies */
#include "RB-Identity.h"
#include "RLC-Info-r5.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum RLC_InfoChoice_r5_PR {
    RLC_InfoChoice_r5_PR_NOTHING, /* No components present */
    RLC_InfoChoice_r5_PR_rlc_Info,
    RLC_InfoChoice_r5_PR_same_as_RB
} RLC_InfoChoice_r5_PR;

/* RLC-InfoChoice-r5 */
typedef struct RLC_InfoChoice_r5 {
    RLC_InfoChoice_r5_PR present;
    union RLC_InfoChoice_r5_u {
        RLC_Info_r5_t rlc_Info;
        RB_Identity_t same_as_RB;
    } choice;

    /* Context for parsing across buffer boundaries */
    asn_struct_ctx_t _asn_ctx;
} RLC_InfoChoice_r5_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RLC_InfoChoice_r5;
extern asn_CHOICE_specifics_t asn_SPC_RLC_InfoChoice_r5_specs_1;
extern asn_TYPE_member_t asn_MBR_RLC_InfoChoice_r5_1[2];
extern asn_per_constraints_t asn_PER_type_RLC_InfoChoice_r5_constr_1;

#ifdef __cplusplus
}
#endif

#endif /* _RLC_InfoChoice_r5_H_ */
#include <asn_internal.h>
