/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "PDU-definitions"
 * 	found in "../../Skeletons/ASN_files/UMTS/rrc-25.331-r19.asn1"
 * 	`asn1c -fcompound-names -pdu=all`
 */

#ifndef _RRCConnectionRelease_r4_IEs_H_
#define _RRCConnectionRelease_r4_IEs_H_


#include <asn_application.h>

/* Including external dependencies */
#include "N-308.h"
#include "ReleaseCause.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct Rplmn_Information_r4;

/* RRCConnectionRelease-r4-IEs */
typedef struct RRCConnectionRelease_r4_IEs {
    N_308_t *n_308 /* OPTIONAL */;
    ReleaseCause_t releaseCause;
    struct Rplmn_Information_r4 *rplmn_information /* OPTIONAL */;

    /* Context for parsing across buffer boundaries */
    asn_struct_ctx_t _asn_ctx;
} RRCConnectionRelease_r4_IEs_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RRCConnectionRelease_r4_IEs;
extern asn_SEQUENCE_specifics_t asn_SPC_RRCConnectionRelease_r4_IEs_specs_1;
extern asn_TYPE_member_t asn_MBR_RRCConnectionRelease_r4_IEs_1[3];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "Rplmn-Information-r4.h"

#endif /* _RRCConnectionRelease_r4_IEs_H_ */
#include <asn_internal.h>
