/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "../../Skeletons/ASN_files/UMTS/rrc-25.331-r19.asn1"
 * 	`asn1c -fcompound-names -pdu=all`
 */

#ifndef _SchedulingInformation2_H_
#define _SchedulingInformation2_H_


#include <asn_application.h>

/* Including external dependencies */
#include "SegCount.h"
#include <NativeInteger.h>
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SchedulingInformation2_PR {
    SchedulingInformation2_PR_NOTHING, /* No components present */
    SchedulingInformation2_PR_scheduling
} SchedulingInformation2_PR;
typedef enum SchedulingInformation2__scheduling__sib_Pos_PR {
    SchedulingInformation2__scheduling__sib_Pos_PR_NOTHING, /* No components present */
    SchedulingInformation2__scheduling__sib_Pos_PR_rep4,
    SchedulingInformation2__scheduling__sib_Pos_PR_rep8,
    SchedulingInformation2__scheduling__sib_Pos_PR_rep16,
    SchedulingInformation2__scheduling__sib_Pos_PR_rep32,
    SchedulingInformation2__scheduling__sib_Pos_PR_rep64,
    SchedulingInformation2__scheduling__sib_Pos_PR_rep128,
    SchedulingInformation2__scheduling__sib_Pos_PR_rep256,
    SchedulingInformation2__scheduling__sib_Pos_PR_rep512,
    SchedulingInformation2__scheduling__sib_Pos_PR_rep1024,
    SchedulingInformation2__scheduling__sib_Pos_PR_rep2048,
    SchedulingInformation2__scheduling__sib_Pos_PR_rep4096
} SchedulingInformation2__scheduling__sib_Pos_PR;

/* Forward declarations */
struct SibOFF_List2;

/* SchedulingInformation2 */
typedef struct SchedulingInformation2 {
    SchedulingInformation2_PR present;
    union SchedulingInformation2_u {
        struct SchedulingInformation2__scheduling {
            SegCount_t *segCount /* OPTIONAL */;
            struct SchedulingInformation2__scheduling__sib_Pos {
                SchedulingInformation2__scheduling__sib_Pos_PR present;
                union SchedulingInformation2__scheduling__sib_Pos_u {
                    long rep4;
                    long rep8;
                    long rep16;
                    long rep32;
                    long rep64;
                    long rep128;
                    long rep256;
                    long rep512;
                    long rep1024;
                    long rep2048;
                    long rep4096;
                } choice;

                /* Context for parsing across buffer boundaries */
                asn_struct_ctx_t _asn_ctx;
            } sib_Pos;
            struct SibOFF_List2 *sib_PosOffsetInfo /* OPTIONAL */;

            /* Context for parsing across buffer boundaries */
            asn_struct_ctx_t _asn_ctx;
        } scheduling;
    } choice;

    /* Context for parsing across buffer boundaries */
    asn_struct_ctx_t _asn_ctx;
} SchedulingInformation2_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SchedulingInformation2;
extern asn_CHOICE_specifics_t asn_SPC_SchedulingInformation2_specs_1;
extern asn_TYPE_member_t asn_MBR_SchedulingInformation2_1[1];
extern asn_per_constraints_t asn_PER_type_SchedulingInformation2_constr_1;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "SibOFF-List2.h"

#endif /* _SchedulingInformation2_H_ */
#include <asn_internal.h>
