/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "../../Skeletons/ASN_files/UMTS/rrc-25.331-r19.asn1"
 * 	`asn1c -fcompound-names -pdu=all`
 */

#ifndef _SecondaryCCPCHFrameType2Info_H_
#define _SecondaryCCPCHFrameType2Info_H_


#include <asn_application.h>

/* Including external dependencies */
#include "DL-ChannelCodes-MBSFN-IMB384.h"
#include <NULL.h>
#include <NativeInteger.h>
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SecondaryCCPCHFrameType2Info__modulation_PR {
    SecondaryCCPCHFrameType2Info__modulation_PR_NOTHING, /* No components present */
    SecondaryCCPCHFrameType2Info__modulation_PR_modQPSK,
    SecondaryCCPCHFrameType2Info__modulation_PR_mod16QAM
} SecondaryCCPCHFrameType2Info__modulation_PR;

/* SecondaryCCPCHFrameType2Info */
typedef struct SecondaryCCPCHFrameType2Info {
    long subFrameNumber;
    DL_ChannelCodes_MBSFN_IMB384_t dl_ChannelisationCodes;
    struct SecondaryCCPCHFrameType2Info__modulation {
        SecondaryCCPCHFrameType2Info__modulation_PR present;
        union SecondaryCCPCHFrameType2Info__modulation_u {
            NULL_t modQPSK;
            struct SecondaryCCPCHFrameType2Info__modulation__mod16QAM {
                long cpich_SecCCPCH_PowerOffset;

                /* Context for parsing across buffer boundaries */
                asn_struct_ctx_t _asn_ctx;
            } mod16QAM;
        } choice;

        /* Context for parsing across buffer boundaries */
        asn_struct_ctx_t _asn_ctx;
    } modulation;

    /* Context for parsing across buffer boundaries */
    asn_struct_ctx_t _asn_ctx;
} SecondaryCCPCHFrameType2Info_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SecondaryCCPCHFrameType2Info;
extern asn_SEQUENCE_specifics_t asn_SPC_SecondaryCCPCHFrameType2Info_specs_1;
extern asn_TYPE_member_t asn_MBR_SecondaryCCPCHFrameType2Info_1[3];

#ifdef __cplusplus
}
#endif

#endif /* _SecondaryCCPCHFrameType2Info_H_ */
#include <asn_internal.h>
