/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "../../Skeletons/ASN_files/UMTS/rrc-25.331-r19.asn1"
 * 	`asn1c -fcompound-names -pdu=all`
 */

#ifndef _SecondaryCellMIMOparametersFDD_H_
#define _SecondaryCellMIMOparametersFDD_H_


#include <asn_application.h>

/* Including external dependencies */
#include "MIMO-N-M-Ratio.h"
#include <NULL.h>
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SecondaryCellMIMOparametersFDD_PR {
    SecondaryCellMIMOparametersFDD_PR_NOTHING, /* No components present */
    SecondaryCellMIMOparametersFDD_PR_continue,
    SecondaryCellMIMOparametersFDD_PR_newConfiguration
} SecondaryCellMIMOparametersFDD_PR;

/* Forward declarations */
struct MIMO_PilotConfiguration_r9;

/* SecondaryCellMIMOparametersFDD */
typedef struct SecondaryCellMIMOparametersFDD {
    SecondaryCellMIMOparametersFDD_PR present;
    union SecondaryCellMIMOparametersFDD_u {
        NULL_t Continue;
        struct SecondaryCellMIMOparametersFDD__newConfiguration {
            MIMO_N_M_Ratio_t *mimoN_M_Ratio /* OPTIONAL */;
            struct MIMO_PilotConfiguration_r9 *mimoPilotConfiguration /* OPTIONAL */;

            /* Context for parsing across buffer boundaries */
            asn_struct_ctx_t _asn_ctx;
        } newConfiguration;
    } choice;

    /* Context for parsing across buffer boundaries */
    asn_struct_ctx_t _asn_ctx;
} SecondaryCellMIMOparametersFDD_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SecondaryCellMIMOparametersFDD;
extern asn_CHOICE_specifics_t asn_SPC_SecondaryCellMIMOparametersFDD_specs_1;
extern asn_TYPE_member_t asn_MBR_SecondaryCellMIMOparametersFDD_1[2];
extern asn_per_constraints_t asn_PER_type_SecondaryCellMIMOparametersFDD_constr_1;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "MIMO-PilotConfiguration-r9.h"

#endif /* _SecondaryCellMIMOparametersFDD_H_ */
#include <asn_internal.h>
