/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "../../Skeletons/ASN_files/UMTS/rrc-25.331-r19.asn1"
 * 	`asn1c -fcompound-names -pdu=all`
 */

#ifndef _SecondaryCCPCHInfo_MBMS_r6_H_
#define _SecondaryCCPCHInfo_MBMS_r6_H_


#include <asn_application.h>

/* Including external dependencies */
#include "CommonTimeslotInfoMBMS.h"
#include "DownlinkTimeslotsCodes-LCR-r4.h"
#include "DownlinkTimeslotsCodes.h"
#include "SF256-AndCodeNumber.h"
#include "SecondaryScramblingCode.h"
#include "TimingOffset.h"
#include <BOOLEAN.h>
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SecondaryCCPCHInfo_MBMS_r6__modeSpecificInfo_PR {
    SecondaryCCPCHInfo_MBMS_r6__modeSpecificInfo_PR_NOTHING, /* No components present */
    SecondaryCCPCHInfo_MBMS_r6__modeSpecificInfo_PR_fdd,
    SecondaryCCPCHInfo_MBMS_r6__modeSpecificInfo_PR_tdd384,
    SecondaryCCPCHInfo_MBMS_r6__modeSpecificInfo_PR_tdd128
} SecondaryCCPCHInfo_MBMS_r6__modeSpecificInfo_PR;

/* SecondaryCCPCHInfo-MBMS-r6 */
typedef struct SecondaryCCPCHInfo_MBMS_r6 {
    struct SecondaryCCPCHInfo_MBMS_r6__modeSpecificInfo {
        SecondaryCCPCHInfo_MBMS_r6__modeSpecificInfo_PR present;
        union SecondaryCCPCHInfo_MBMS_r6__modeSpecificInfo_u {
            struct SecondaryCCPCHInfo_MBMS_r6__modeSpecificInfo__fdd {
                SecondaryScramblingCode_t *secondaryScramblingCode /* OPTIONAL */;
                BOOLEAN_t sttd_Indicator;
                SF256_AndCodeNumber_t sf_AndCodeNumber;
                TimingOffset_t timingOffset /* DEFAULT 0 */;

                /* Context for parsing across buffer boundaries */
                asn_struct_ctx_t _asn_ctx;
            } fdd;
            struct SecondaryCCPCHInfo_MBMS_r6__modeSpecificInfo__tdd384 {
                CommonTimeslotInfoMBMS_t commonTimeslotInfoMBMS;
                DownlinkTimeslotsCodes_t downlinkTimeslotsCodes;

                /* Context for parsing across buffer boundaries */
                asn_struct_ctx_t _asn_ctx;
            } tdd384;
            struct SecondaryCCPCHInfo_MBMS_r6__modeSpecificInfo__tdd128 {
                CommonTimeslotInfoMBMS_t commonTimeslotInfoMBMS;
                DownlinkTimeslotsCodes_LCR_r4_t downlinkTimeslotsCodes;

                /* Context for parsing across buffer boundaries */
                asn_struct_ctx_t _asn_ctx;
            } tdd128;
        } choice;

        /* Context for parsing across buffer boundaries */
        asn_struct_ctx_t _asn_ctx;
    } modeSpecificInfo;

    /* Context for parsing across buffer boundaries */
    asn_struct_ctx_t _asn_ctx;
} SecondaryCCPCHInfo_MBMS_r6_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SecondaryCCPCHInfo_MBMS_r6;
extern asn_SEQUENCE_specifics_t asn_SPC_SecondaryCCPCHInfo_MBMS_r6_specs_1;
extern asn_TYPE_member_t asn_MBR_SecondaryCCPCHInfo_MBMS_r6_1[1];

#ifdef __cplusplus
}
#endif

#endif /* _SecondaryCCPCHInfo_MBMS_r6_H_ */
#include <asn_internal.h>
