/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "../../Skeletons/ASN_files/UMTS/rrc-25.331-r19.asn1"
 * 	`asn1c -fcompound-names -pdu=all`
 */

#ifndef _T_308_H_
#define _T_308_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum T_308 {
    T_308_ms40 = 0,
    T_308_ms80 = 1,
    T_308_ms160 = 2,
    T_308_ms320 = 3
} e_T_308;

/* T-308 */
typedef long T_308_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_T_308_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_T_308;
extern const asn_INTEGER_specifics_t asn_SPC_T_308_specs_1;
asn_struct_free_f T_308_free;
asn_struct_print_f T_308_print;
asn_constr_check_f T_308_constraint;
ber_type_decoder_f T_308_decode_ber;
der_type_encoder_f T_308_encode_der;
xer_type_decoder_f T_308_decode_xer;
xer_type_encoder_f T_308_encode_xer;
oer_type_decoder_f T_308_decode_oer;
oer_type_encoder_f T_308_encode_oer;
per_type_decoder_f T_308_decode_uper;
per_type_encoder_f T_308_encode_uper;

#ifdef __cplusplus
}
#endif

#endif /* _T_308_H_ */
#include <asn_internal.h>
