/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "../../Skeletons/ASN_files/UMTS/rrc-25.331-r19.asn1"
 * 	`asn1c -fcompound-names -pdu=all`
 */

#include "T-311.h"

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static asn_oer_constraints_t asn_OER_type_T_311_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
asn_per_constraints_t asn_PER_type_T_311_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 3,  3,  0,  7 }	/* (0..7) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static const asn_INTEGER_enum_map_t asn_MAP_T_311_value2enum_1[] = {
	{ 0,	5,	"ms250" },
	{ 1,	5,	"ms500" },
	{ 2,	5,	"ms750" },
	{ 3,	6,	"ms1000" },
	{ 4,	6,	"ms1250" },
	{ 5,	6,	"ms1500" },
	{ 6,	6,	"ms1750" },
	{ 7,	6,	"ms2000" }
};
static const unsigned int asn_MAP_T_311_enum2value_1[] = {
	3,	/* ms1000(3) */
	4,	/* ms1250(4) */
	5,	/* ms1500(5) */
	6,	/* ms1750(6) */
	7,	/* ms2000(7) */
	0,	/* ms250(0) */
	1,	/* ms500(1) */
	2	/* ms750(2) */
};
const asn_INTEGER_specifics_t asn_SPC_T_311_specs_1 = {
	asn_MAP_T_311_value2enum_1,	/* "tag" => N; sorted by tag */
	asn_MAP_T_311_enum2value_1,	/* N => "tag"; sorted by N */
	8,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_T_311_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
asn_TYPE_descriptor_t asn_DEF_T_311 = {
	"T-311",
	"T-311",
	&asn_OP_NativeEnumerated,
	asn_DEF_T_311_tags_1,
	sizeof(asn_DEF_T_311_tags_1)
		/sizeof(asn_DEF_T_311_tags_1[0]), /* 1 */
	asn_DEF_T_311_tags_1,	/* Same as above */
	sizeof(asn_DEF_T_311_tags_1)
		/sizeof(asn_DEF_T_311_tags_1[0]), /* 1 */
	{ &asn_OER_type_T_311_constr_1, &asn_PER_type_T_311_constr_1, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_T_311_specs_1	/* Additional specs */
};

