/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "../../Skeletons/ASN_files/UMTS/rrc-25.331-r19.asn1"
 * 	`asn1c -fcompound-names -pdu=all`
 */

#include "TxFailParams.h"

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static int
memb_connEstFailTempQoffset_constraint_3(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 15)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_oer_constraints_t asn_OER_type_connEstFailCount_constr_4 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_connEstFailCount_constr_4 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 2,  2,  0,  3 }	/* (0..3) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_offsetValidity_constr_9 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_offsetValidity_constr_9 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 3,  3,  0,  7 }	/* (0..7) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_connEstFailTempQoffset_constr_18 CC_NOTUSED = {
	{ 1, 1 }	/* (0..15) */,
	-1};
static asn_per_constraints_t asn_PER_memb_connEstFailTempQoffset_constr_18 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 4,  4,  0,  15 }	/* (0..15) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_modeSpecificInfo_constr_2 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_modeSpecificInfo_constr_2 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static const asn_INTEGER_enum_map_t asn_MAP_connEstFailCount_value2enum_4[] = {
	{ 0,	2,	"n1" },
	{ 1,	2,	"n2" },
	{ 2,	2,	"n3" },
	{ 3,	2,	"n4" }
};
static const unsigned int asn_MAP_connEstFailCount_enum2value_4[] = {
	0,	/* n1(0) */
	1,	/* n2(1) */
	2,	/* n3(2) */
	3	/* n4(3) */
};
static const asn_INTEGER_specifics_t asn_SPC_connEstFailCount_specs_4 = {
	asn_MAP_connEstFailCount_value2enum_4,	/* "tag" => N; sorted by tag */
	asn_MAP_connEstFailCount_enum2value_4,	/* N => "tag"; sorted by N */
	4,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_connEstFailCount_tags_4[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_connEstFailCount_4 = {
	"connEstFailCount",
	"connEstFailCount",
	&asn_OP_NativeEnumerated,
	asn_DEF_connEstFailCount_tags_4,
	sizeof(asn_DEF_connEstFailCount_tags_4)
		/sizeof(asn_DEF_connEstFailCount_tags_4[0]) - 1, /* 1 */
	asn_DEF_connEstFailCount_tags_4,	/* Same as above */
	sizeof(asn_DEF_connEstFailCount_tags_4)
		/sizeof(asn_DEF_connEstFailCount_tags_4[0]), /* 2 */
	{ &asn_OER_type_connEstFailCount_constr_4, &asn_PER_type_connEstFailCount_constr_4, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_connEstFailCount_specs_4	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_offsetValidity_value2enum_9[] = {
	{ 0,	3,	"s30" },
	{ 1,	3,	"s60" },
	{ 2,	4,	"s120" },
	{ 3,	4,	"s240" },
	{ 4,	4,	"s300" },
	{ 5,	4,	"s420" },
	{ 6,	4,	"s600" },
	{ 7,	4,	"s900" }
};
static const unsigned int asn_MAP_offsetValidity_enum2value_9[] = {
	2,	/* s120(2) */
	3,	/* s240(3) */
	0,	/* s30(0) */
	4,	/* s300(4) */
	5,	/* s420(5) */
	1,	/* s60(1) */
	6,	/* s600(6) */
	7	/* s900(7) */
};
static const asn_INTEGER_specifics_t asn_SPC_offsetValidity_specs_9 = {
	asn_MAP_offsetValidity_value2enum_9,	/* "tag" => N; sorted by tag */
	asn_MAP_offsetValidity_enum2value_9,	/* N => "tag"; sorted by N */
	8,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_offsetValidity_tags_9[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_offsetValidity_9 = {
	"offsetValidity",
	"offsetValidity",
	&asn_OP_NativeEnumerated,
	asn_DEF_offsetValidity_tags_9,
	sizeof(asn_DEF_offsetValidity_tags_9)
		/sizeof(asn_DEF_offsetValidity_tags_9[0]) - 1, /* 1 */
	asn_DEF_offsetValidity_tags_9,	/* Same as above */
	sizeof(asn_DEF_offsetValidity_tags_9)
		/sizeof(asn_DEF_offsetValidity_tags_9[0]), /* 2 */
	{ &asn_OER_type_offsetValidity_constr_9, &asn_PER_type_offsetValidity_constr_9, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_offsetValidity_specs_9	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_fdd_3[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct TxFailParams__modeSpecificInfo__fdd, connEstFailCount),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_connEstFailCount_4,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"connEstFailCount"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct TxFailParams__modeSpecificInfo__fdd, offsetValidity),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_offsetValidity_9,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"offsetValidity"
		},
	{ ATF_POINTER, 1, offsetof(struct TxFailParams__modeSpecificInfo__fdd, connEstFailTempQoffset),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ &asn_OER_memb_connEstFailTempQoffset_constr_18, &asn_PER_memb_connEstFailTempQoffset_constr_18,  memb_connEstFailTempQoffset_constraint_3 },
		0, 0, /* No default value */
		"connEstFailTempQoffset"
		},
};
static const int asn_MAP_fdd_oms_3[] = { 2 };
static const ber_tlv_tag_t asn_DEF_fdd_tags_3[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_fdd_tag2el_3[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* connEstFailCount */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* offsetValidity */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* connEstFailTempQoffset */
};
static asn_SEQUENCE_specifics_t asn_SPC_fdd_specs_3 = {
	sizeof(struct TxFailParams__modeSpecificInfo__fdd),
	offsetof(struct TxFailParams__modeSpecificInfo__fdd, _asn_ctx),
	asn_MAP_fdd_tag2el_3,
	3,	/* Count of tags in the map */
	asn_MAP_fdd_oms_3,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_fdd_3 = {
	"fdd",
	"fdd",
	&asn_OP_SEQUENCE,
	asn_DEF_fdd_tags_3,
	sizeof(asn_DEF_fdd_tags_3)
		/sizeof(asn_DEF_fdd_tags_3[0]) - 1, /* 1 */
	asn_DEF_fdd_tags_3,	/* Same as above */
	sizeof(asn_DEF_fdd_tags_3)
		/sizeof(asn_DEF_fdd_tags_3[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_fdd_3,
	3,	/* Elements count */
	&asn_SPC_fdd_specs_3	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_modeSpecificInfo_2[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct TxFailParams__modeSpecificInfo, choice.fdd),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		0,
		&asn_DEF_fdd_3,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"fdd"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct TxFailParams__modeSpecificInfo, choice.tdd),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"tdd"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_modeSpecificInfo_tag2el_2[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* fdd */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* tdd */
};
static asn_CHOICE_specifics_t asn_SPC_modeSpecificInfo_specs_2 = {
	sizeof(struct TxFailParams__modeSpecificInfo),
	offsetof(struct TxFailParams__modeSpecificInfo, _asn_ctx),
	offsetof(struct TxFailParams__modeSpecificInfo, present),
	sizeof(((struct TxFailParams__modeSpecificInfo *)0)->present),
	asn_MAP_modeSpecificInfo_tag2el_2,
	2,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_modeSpecificInfo_2 = {
	"modeSpecificInfo",
	"modeSpecificInfo",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ &asn_OER_type_modeSpecificInfo_constr_2, &asn_PER_type_modeSpecificInfo_constr_2, CHOICE_constraint },
	asn_MBR_modeSpecificInfo_2,
	2,	/* Elements count */
	&asn_SPC_modeSpecificInfo_specs_2	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_TxFailParams_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct TxFailParams, modeSpecificInfo),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_modeSpecificInfo_2,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"modeSpecificInfo"
		},
};
static const ber_tlv_tag_t asn_DEF_TxFailParams_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_TxFailParams_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 } /* modeSpecificInfo */
};
asn_SEQUENCE_specifics_t asn_SPC_TxFailParams_specs_1 = {
	sizeof(struct TxFailParams),
	offsetof(struct TxFailParams, _asn_ctx),
	asn_MAP_TxFailParams_tag2el_1,
	1,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_TxFailParams = {
	"TxFailParams",
	"TxFailParams",
	&asn_OP_SEQUENCE,
	asn_DEF_TxFailParams_tags_1,
	sizeof(asn_DEF_TxFailParams_tags_1)
		/sizeof(asn_DEF_TxFailParams_tags_1[0]), /* 1 */
	asn_DEF_TxFailParams_tags_1,	/* Same as above */
	sizeof(asn_DEF_TxFailParams_tags_1)
		/sizeof(asn_DEF_TxFailParams_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_TxFailParams_1,
	1,	/* Elements count */
	&asn_SPC_TxFailParams_specs_1	/* Additional specs */
};

