/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "../../Skeletons/ASN_files/UMTS/rrc-25.331-r19.asn1"
 * 	`asn1c -fcompound-names -pdu=all`
 */

#include "UE-AddPos-element.h"

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static asn_oer_constraints_t asn_OER_type_addPos_ID_constr_2 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_addPos_ID_constr_2 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 3,  3,  0,  7 }	/* (0..7) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_addPos_Mode_constr_11 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_addPos_Mode_constr_11 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 2,  2,  0,  3 }	/* (0..3) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static const asn_INTEGER_enum_map_t asn_MAP_addPos_ID_value2enum_2[] = {
	{ 0,	18,	"barometricPressure" },
	{ 1,	4,	"wlan" },
	{ 2,	2,	"bt" },
	{ 3,	3,	"mbs" },
	{ 4,	6,	"spare4" },
	{ 5,	6,	"spare3" },
	{ 6,	6,	"spare2" },
	{ 7,	6,	"spare1" }
};
static const unsigned int asn_MAP_addPos_ID_enum2value_2[] = {
	0,	/* barometricPressure(0) */
	2,	/* bt(2) */
	3,	/* mbs(3) */
	7,	/* spare1(7) */
	6,	/* spare2(6) */
	5,	/* spare3(5) */
	4,	/* spare4(4) */
	1	/* wlan(1) */
};
static const asn_INTEGER_specifics_t asn_SPC_addPos_ID_specs_2 = {
	asn_MAP_addPos_ID_value2enum_2,	/* "tag" => N; sorted by tag */
	asn_MAP_addPos_ID_enum2value_2,	/* N => "tag"; sorted by N */
	8,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_addPos_ID_tags_2[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_addPos_ID_2 = {
	"addPos-ID",
	"addPos-ID",
	&asn_OP_NativeEnumerated,
	asn_DEF_addPos_ID_tags_2,
	sizeof(asn_DEF_addPos_ID_tags_2)
		/sizeof(asn_DEF_addPos_ID_tags_2[0]) - 1, /* 1 */
	asn_DEF_addPos_ID_tags_2,	/* Same as above */
	sizeof(asn_DEF_addPos_ID_tags_2)
		/sizeof(asn_DEF_addPos_ID_tags_2[0]), /* 2 */
	{ &asn_OER_type_addPos_ID_constr_2, &asn_PER_type_addPos_ID_constr_2, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_addPos_ID_specs_2	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_addPos_Mode_value2enum_11[] = {
	{ 0,	10,	"standalone" },
	{ 1,	11,	"ue-assisted" },
	{ 2,	4,	"both" },
	{ 3,	6,	"spare1" }
};
static const unsigned int asn_MAP_addPos_Mode_enum2value_11[] = {
	2,	/* both(2) */
	3,	/* spare1(3) */
	0,	/* standalone(0) */
	1	/* ue-assisted(1) */
};
static const asn_INTEGER_specifics_t asn_SPC_addPos_Mode_specs_11 = {
	asn_MAP_addPos_Mode_value2enum_11,	/* "tag" => N; sorted by tag */
	asn_MAP_addPos_Mode_enum2value_11,	/* N => "tag"; sorted by N */
	4,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_addPos_Mode_tags_11[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_addPos_Mode_11 = {
	"addPos-Mode",
	"addPos-Mode",
	&asn_OP_NativeEnumerated,
	asn_DEF_addPos_Mode_tags_11,
	sizeof(asn_DEF_addPos_Mode_tags_11)
		/sizeof(asn_DEF_addPos_Mode_tags_11[0]) - 1, /* 1 */
	asn_DEF_addPos_Mode_tags_11,	/* Same as above */
	sizeof(asn_DEF_addPos_Mode_tags_11)
		/sizeof(asn_DEF_addPos_Mode_tags_11[0]), /* 2 */
	{ &asn_OER_type_addPos_Mode_constr_11, &asn_PER_type_addPos_Mode_constr_11, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_addPos_Mode_specs_11	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_UE_AddPos_element_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct UE_AddPos_element, addPos_ID),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_addPos_ID_2,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"addPos-ID"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct UE_AddPos_element, addPos_Mode),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_addPos_Mode_11,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"addPos-Mode"
		},
};
static const ber_tlv_tag_t asn_DEF_UE_AddPos_element_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_UE_AddPos_element_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* addPos-ID */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* addPos-Mode */
};
asn_SEQUENCE_specifics_t asn_SPC_UE_AddPos_element_specs_1 = {
	sizeof(struct UE_AddPos_element),
	offsetof(struct UE_AddPos_element, _asn_ctx),
	asn_MAP_UE_AddPos_element_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_UE_AddPos_element = {
	"UE-AddPos-element",
	"UE-AddPos-element",
	&asn_OP_SEQUENCE,
	asn_DEF_UE_AddPos_element_tags_1,
	sizeof(asn_DEF_UE_AddPos_element_tags_1)
		/sizeof(asn_DEF_UE_AddPos_element_tags_1[0]), /* 1 */
	asn_DEF_UE_AddPos_element_tags_1,	/* Same as above */
	sizeof(asn_DEF_UE_AddPos_element_tags_1)
		/sizeof(asn_DEF_UE_AddPos_element_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_UE_AddPos_element_1,
	2,	/* Elements count */
	&asn_SPC_UE_AddPos_element_specs_1	/* Additional specs */
};

