/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "../../Skeletons/ASN_files/UMTS/rrc-25.331-r19.asn1"
 * 	`asn1c -fcompound-names -pdu=all`
 */

#ifndef _UE_HistoryInformation_H_
#define _UE_HistoryInformation_H_


#include <asn_application.h>

/* Including external dependencies */
#include "High-MobilityDetected.h"
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct DataVolumeHistory;

/* UE-HistoryInformation */
typedef struct UE_HistoryInformation {
    long ue_InactivityPeriod;
    High_MobilityDetected_t *ueMobilityStateIndicator /* OPTIONAL */;
    struct DataVolumeHistory *ul_dataVolumeHistory /* OPTIONAL */;
    struct DataVolumeHistory *dl_dataVolumeHistory /* OPTIONAL */;

    /* Context for parsing across buffer boundaries */
    asn_struct_ctx_t _asn_ctx;
} UE_HistoryInformation_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UE_HistoryInformation;
extern asn_SEQUENCE_specifics_t asn_SPC_UE_HistoryInformation_specs_1;
extern asn_TYPE_member_t asn_MBR_UE_HistoryInformation_1[4];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "DataVolumeHistory.h"

#endif /* _UE_HistoryInformation_H_ */
#include <asn_internal.h>
