/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "../../Skeletons/ASN_files/UMTS/rrc-25.331-r19.asn1"
 * 	`asn1c -fcompound-names -pdu=all`
 */

#ifndef _UE_Positioning_OTDOA_ReferenceCellInfo_r7_H_
#define _UE_Positioning_OTDOA_ReferenceCellInfo_r7_H_


#include <asn_application.h>

/* Including external dependencies */
#include "CellAndChannelIdentity.h"
#include "PrimaryCPICH-Info.h"
#include <NativeInteger.h>
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum UE_Positioning_OTDOA_ReferenceCellInfo_r7__modeSpecificInfo_PR {
    UE_Positioning_OTDOA_ReferenceCellInfo_r7__modeSpecificInfo_PR_NOTHING, /* No components present */
    UE_Positioning_OTDOA_ReferenceCellInfo_r7__modeSpecificInfo_PR_fdd,
    UE_Positioning_OTDOA_ReferenceCellInfo_r7__modeSpecificInfo_PR_tdd
} UE_Positioning_OTDOA_ReferenceCellInfo_r7__modeSpecificInfo_PR;
typedef enum UE_Positioning_OTDOA_ReferenceCellInfo_r7__positioningMode_PR {
    UE_Positioning_OTDOA_ReferenceCellInfo_r7__positioningMode_PR_NOTHING, /* No components present */
    UE_Positioning_OTDOA_ReferenceCellInfo_r7__positioningMode_PR_ueBased,
    UE_Positioning_OTDOA_ReferenceCellInfo_r7__positioningMode_PR_ueAssisted
} UE_Positioning_OTDOA_ReferenceCellInfo_r7__positioningMode_PR;

/* Forward declarations */
struct FrequencyInfo;
struct UE_Positioning_IPDL_Parameters_r4;
struct ReferenceCellPosition;

/* UE-Positioning-OTDOA-ReferenceCellInfo-r7 */
typedef struct UE_Positioning_OTDOA_ReferenceCellInfo_r7 {
    long *sfn /* OPTIONAL */;
    struct UE_Positioning_OTDOA_ReferenceCellInfo_r7__modeSpecificInfo {
        UE_Positioning_OTDOA_ReferenceCellInfo_r7__modeSpecificInfo_PR present;
        union UE_Positioning_OTDOA_ReferenceCellInfo_r7__modeSpecificInfo_u {
            struct UE_Positioning_OTDOA_ReferenceCellInfo_r7__modeSpecificInfo__fdd {
                PrimaryCPICH_Info_t primaryCPICH_Info;

                /* Context for parsing across buffer boundaries */
                asn_struct_ctx_t _asn_ctx;
            } fdd;
            struct UE_Positioning_OTDOA_ReferenceCellInfo_r7__modeSpecificInfo__tdd {
                CellAndChannelIdentity_t cellAndChannelIdentity;

                /* Context for parsing across buffer boundaries */
                asn_struct_ctx_t _asn_ctx;
            } tdd;
        } choice;

        /* Context for parsing across buffer boundaries */
        asn_struct_ctx_t _asn_ctx;
    } modeSpecificInfo;
    struct FrequencyInfo *frequencyInfo /* OPTIONAL */;
    struct UE_Positioning_OTDOA_ReferenceCellInfo_r7__positioningMode {
        UE_Positioning_OTDOA_ReferenceCellInfo_r7__positioningMode_PR present;
        union UE_Positioning_OTDOA_ReferenceCellInfo_r7__positioningMode_u {
            struct UE_Positioning_OTDOA_ReferenceCellInfo_r7__positioningMode__ueBased {
                struct ReferenceCellPosition *cellPosition /* OPTIONAL */;
                long *roundTripTime /* OPTIONAL */;
                long *roundTripTimeExtension /* OPTIONAL */;

                /* Context for parsing across buffer boundaries */
                asn_struct_ctx_t _asn_ctx;
            } ueBased;
            struct UE_Positioning_OTDOA_ReferenceCellInfo_r7__positioningMode__ueAssisted {

                /* Context for parsing across buffer boundaries */
                asn_struct_ctx_t _asn_ctx;
            } ueAssisted;
        } choice;

        /* Context for parsing across buffer boundaries */
        asn_struct_ctx_t _asn_ctx;
    } positioningMode;
    struct UE_Positioning_IPDL_Parameters_r4 *ue_positioning_IPDL_Paremeters /* OPTIONAL */;

    /* Context for parsing across buffer boundaries */
    asn_struct_ctx_t _asn_ctx;
} UE_Positioning_OTDOA_ReferenceCellInfo_r7_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UE_Positioning_OTDOA_ReferenceCellInfo_r7;
extern asn_SEQUENCE_specifics_t asn_SPC_UE_Positioning_OTDOA_ReferenceCellInfo_r7_specs_1;
extern asn_TYPE_member_t asn_MBR_UE_Positioning_OTDOA_ReferenceCellInfo_r7_1[5];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "FrequencyInfo.h"
#include "ReferenceCellPosition.h"
#include "UE-Positioning-IPDL-Parameters-r4.h"

#endif /* _UE_Positioning_OTDOA_ReferenceCellInfo_r7_H_ */
#include <asn_internal.h>
