/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "../../Skeletons/ASN_files/UMTS/rrc-25.331-r19.asn1"
 * 	`asn1c -fcompound-names -pdu=all`
 */

#ifndef _UE_RadioAccessCapabBandFDDList7_H_
#define _UE_RadioAccessCapabBandFDDList7_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct UE_RadioAccessCapabBandFDD7;

/* UE-RadioAccessCapabBandFDDList7 */
typedef struct UE_RadioAccessCapabBandFDDList7 {
    A_SEQUENCE_OF(struct UE_RadioAccessCapabBandFDD7)
    list;

    /* Context for parsing across buffer boundaries */
    asn_struct_ctx_t _asn_ctx;
} UE_RadioAccessCapabBandFDDList7_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UE_RadioAccessCapabBandFDDList7;
extern asn_SET_OF_specifics_t asn_SPC_UE_RadioAccessCapabBandFDDList7_specs_1;
extern asn_TYPE_member_t asn_MBR_UE_RadioAccessCapabBandFDDList7_1[1];
extern asn_per_constraints_t asn_PER_type_UE_RadioAccessCapabBandFDDList7_constr_1;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "UE-RadioAccessCapabBandFDD7.h"

#endif /* _UE_RadioAccessCapabBandFDDList7_H_ */
#include <asn_internal.h>
