/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "../../Skeletons/ASN_files/UMTS/rrc-25.331-r19.asn1"
 * 	`asn1c -fcompound-names -pdu=all`
 */

#include "UL-AddReconfTransChInformation-r6.h"

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static asn_oer_constraints_t asn_OER_type_harq_Info_constr_8 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_harq_Info_constr_8 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_UL_AddReconfTransChInformation_r6_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
asn_per_constraints_t asn_PER_type_UL_AddReconfTransChInformation_r6_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_dch_usch_2[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct UL_AddReconfTransChInformation_r6__dch_usch, ul_TransportChannelType),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UL_TrCH_Type,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ul-TransportChannelType"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct UL_AddReconfTransChInformation_r6__dch_usch, transportChannelIdentity),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TransportChannelIdentity,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"transportChannelIdentity"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct UL_AddReconfTransChInformation_r6__dch_usch, transportFormatSet),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_TransportFormatSet,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"transportFormatSet"
		},
};
static const ber_tlv_tag_t asn_DEF_dch_usch_tags_2[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_dch_usch_tag2el_2[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* ul-TransportChannelType */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* transportChannelIdentity */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* transportFormatSet */
};
static asn_SEQUENCE_specifics_t asn_SPC_dch_usch_specs_2 = {
	sizeof(struct UL_AddReconfTransChInformation_r6__dch_usch),
	offsetof(struct UL_AddReconfTransChInformation_r6__dch_usch, _asn_ctx),
	asn_MAP_dch_usch_tag2el_2,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_dch_usch_2 = {
	"dch-usch",
	"dch-usch",
	&asn_OP_SEQUENCE,
	asn_DEF_dch_usch_tags_2,
	sizeof(asn_DEF_dch_usch_tags_2)
		/sizeof(asn_DEF_dch_usch_tags_2[0]) - 1, /* 1 */
	asn_DEF_dch_usch_tags_2,	/* Same as above */
	sizeof(asn_DEF_dch_usch_tags_2)
		/sizeof(asn_DEF_dch_usch_tags_2[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_dch_usch_2,
	3,	/* Elements count */
	&asn_SPC_dch_usch_specs_2	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_harq_Info_value2enum_8[] = {
	{ 0,	3,	"rv0" },
	{ 1,	7,	"rvtable" }
};
static const unsigned int asn_MAP_harq_Info_enum2value_8[] = {
	0,	/* rv0(0) */
	1	/* rvtable(1) */
};
static const asn_INTEGER_specifics_t asn_SPC_harq_Info_specs_8 = {
	asn_MAP_harq_Info_value2enum_8,	/* "tag" => N; sorted by tag */
	asn_MAP_harq_Info_enum2value_8,	/* N => "tag"; sorted by N */
	2,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_harq_Info_tags_8[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_harq_Info_8 = {
	"harq-Info",
	"harq-Info",
	&asn_OP_NativeEnumerated,
	asn_DEF_harq_Info_tags_8,
	sizeof(asn_DEF_harq_Info_tags_8)
		/sizeof(asn_DEF_harq_Info_tags_8[0]) - 1, /* 1 */
	asn_DEF_harq_Info_tags_8,	/* Same as above */
	sizeof(asn_DEF_harq_Info_tags_8)
		/sizeof(asn_DEF_harq_Info_tags_8[0]), /* 2 */
	{ &asn_OER_type_harq_Info_constr_8, &asn_PER_type_harq_Info_constr_8, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_harq_Info_specs_8	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_e_dch_6[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct UL_AddReconfTransChInformation_r6__e_dch, tti),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_E_DCH_TTI,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"tti"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct UL_AddReconfTransChInformation_r6__e_dch, harq_Info),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_harq_Info_8,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"harq-Info"
		},
	{ ATF_POINTER, 1, offsetof(struct UL_AddReconfTransChInformation_r6__e_dch, addReconf_MAC_d_FlowList),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_E_DCH_AddReconf_MAC_d_FlowList,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"addReconf-MAC-d-FlowList"
		},
};
static const int asn_MAP_e_dch_oms_6[] = { 2 };
static const ber_tlv_tag_t asn_DEF_e_dch_tags_6[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_e_dch_tag2el_6[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* tti */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* harq-Info */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* addReconf-MAC-d-FlowList */
};
static asn_SEQUENCE_specifics_t asn_SPC_e_dch_specs_6 = {
	sizeof(struct UL_AddReconfTransChInformation_r6__e_dch),
	offsetof(struct UL_AddReconfTransChInformation_r6__e_dch, _asn_ctx),
	asn_MAP_e_dch_tag2el_6,
	3,	/* Count of tags in the map */
	asn_MAP_e_dch_oms_6,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_e_dch_6 = {
	"e-dch",
	"e-dch",
	&asn_OP_SEQUENCE,
	asn_DEF_e_dch_tags_6,
	sizeof(asn_DEF_e_dch_tags_6)
		/sizeof(asn_DEF_e_dch_tags_6[0]) - 1, /* 1 */
	asn_DEF_e_dch_tags_6,	/* Same as above */
	sizeof(asn_DEF_e_dch_tags_6)
		/sizeof(asn_DEF_e_dch_tags_6[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_e_dch_6,
	3,	/* Elements count */
	&asn_SPC_e_dch_specs_6	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_UL_AddReconfTransChInformation_r6_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct UL_AddReconfTransChInformation_r6, choice.dch_usch),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		0,
		&asn_DEF_dch_usch_2,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"dch-usch"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct UL_AddReconfTransChInformation_r6, choice.e_dch),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_e_dch_6,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"e-dch"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_UL_AddReconfTransChInformation_r6_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* dch-usch */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* e-dch */
};
asn_CHOICE_specifics_t asn_SPC_UL_AddReconfTransChInformation_r6_specs_1 = {
	sizeof(struct UL_AddReconfTransChInformation_r6),
	offsetof(struct UL_AddReconfTransChInformation_r6, _asn_ctx),
	offsetof(struct UL_AddReconfTransChInformation_r6, present),
	sizeof(((struct UL_AddReconfTransChInformation_r6 *)0)->present),
	asn_MAP_UL_AddReconfTransChInformation_r6_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_UL_AddReconfTransChInformation_r6 = {
	"UL-AddReconfTransChInformation-r6",
	"UL-AddReconfTransChInformation-r6",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ &asn_OER_type_UL_AddReconfTransChInformation_r6_constr_1, &asn_PER_type_UL_AddReconfTransChInformation_r6_constr_1, CHOICE_constraint },
	asn_MBR_UL_AddReconfTransChInformation_r6_1,
	2,	/* Elements count */
	&asn_SPC_UL_AddReconfTransChInformation_r6_specs_1	/* Additional specs */
};

