/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "../../Skeletons/ASN_files/UMTS/rrc-25.331-r19.asn1"
 * 	`asn1c -fcompound-names -pdu=all`
 */

#ifndef _UL_CommonTransChInfo_r12_H_
#define _UL_CommonTransChInfo_r12_H_


#include <asn_application.h>

/* Including external dependencies */
#include "TFCS-r12.h"
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum UL_CommonTransChInfo_r12__modeSpecificInfo_PR {
    UL_CommonTransChInfo_r12__modeSpecificInfo_PR_NOTHING, /* No components present */
    UL_CommonTransChInfo_r12__modeSpecificInfo_PR_fdd,
    UL_CommonTransChInfo_r12__modeSpecificInfo_PR_tdd
} UL_CommonTransChInfo_r12__modeSpecificInfo_PR;

/* Forward declarations */
struct TFC_Subset;
struct TFCS;
struct TFC_SubsetList;
struct IndividualUL_CCTrCH_InfoList;

/* UL-CommonTransChInfo-r12 */
typedef struct UL_CommonTransChInfo_r12 {
    struct TFC_Subset *tfc_Subset /* OPTIONAL */;
    struct TFCS *prach_TFCS /* OPTIONAL */;
    struct UL_CommonTransChInfo_r12__modeSpecificInfo {
        UL_CommonTransChInfo_r12__modeSpecificInfo_PR present;
        union UL_CommonTransChInfo_r12__modeSpecificInfo_u {
            struct UL_CommonTransChInfo_r12__modeSpecificInfo__fdd {
                TFCS_r12_t ul_TFCS;

                /* Context for parsing across buffer boundaries */
                asn_struct_ctx_t _asn_ctx;
            } fdd;
            struct UL_CommonTransChInfo_r12__modeSpecificInfo__tdd {
                struct IndividualUL_CCTrCH_InfoList *individualUL_CCTrCH_InfoList /* OPTIONAL */;

                /* Context for parsing across buffer boundaries */
                asn_struct_ctx_t _asn_ctx;
            } tdd;
        } choice;

        /* Context for parsing across buffer boundaries */
        asn_struct_ctx_t _asn_ctx;
    } *modeSpecificInfo;
    struct TFC_SubsetList *tfc_SubsetList /* OPTIONAL */;

    /* Context for parsing across buffer boundaries */
    asn_struct_ctx_t _asn_ctx;
} UL_CommonTransChInfo_r12_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UL_CommonTransChInfo_r12;
extern asn_SEQUENCE_specifics_t asn_SPC_UL_CommonTransChInfo_r12_specs_1;
extern asn_TYPE_member_t asn_MBR_UL_CommonTransChInfo_r12_1[4];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "IndividualUL-CCTrCH-InfoList.h"
#include "TFC-Subset.h"
#include "TFC-SubsetList.h"
#include "TFCS.h"

#endif /* _UL_CommonTransChInfo_r12_H_ */
#include <asn_internal.h>
