/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "../../Skeletons/ASN_files/UMTS/rrc-25.331-r19.asn1"
 * 	`asn1c -fcompound-names -pdu=all`
 */

#include "UL-RLC-Mode.h"

static asn_oer_constraints_t asn_OER_type_UL_RLC_Mode_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
asn_per_constraints_t asn_PER_type_UL_RLC_Mode_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 2,  2,  0,  3 }	/* (0..3) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
asn_TYPE_member_t asn_MBR_UL_RLC_Mode_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct UL_RLC_Mode, choice.ul_AM_RLC_Mode),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UL_AM_RLC_Mode,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ul-AM-RLC-Mode"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct UL_RLC_Mode, choice.ul_UM_RLC_Mode),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UL_UM_RLC_Mode,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ul-UM-RLC-Mode"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct UL_RLC_Mode, choice.ul_TM_RLC_Mode),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UL_TM_RLC_Mode,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ul-TM-RLC-Mode"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct UL_RLC_Mode, choice.spare),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"spare"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_UL_RLC_Mode_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* ul-AM-RLC-Mode */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* ul-UM-RLC-Mode */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* ul-TM-RLC-Mode */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 } /* spare */
};
asn_CHOICE_specifics_t asn_SPC_UL_RLC_Mode_specs_1 = {
	sizeof(struct UL_RLC_Mode),
	offsetof(struct UL_RLC_Mode, _asn_ctx),
	offsetof(struct UL_RLC_Mode, present),
	sizeof(((struct UL_RLC_Mode *)0)->present),
	asn_MAP_UL_RLC_Mode_tag2el_1,
	4,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_UL_RLC_Mode = {
	"UL-RLC-Mode",
	"UL-RLC-Mode",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ &asn_OER_type_UL_RLC_Mode_constr_1, &asn_PER_type_UL_RLC_Mode_constr_1, CHOICE_constraint },
	asn_MBR_UL_RLC_Mode_1,
	4,	/* Elements count */
	&asn_SPC_UL_RLC_Mode_specs_1	/* Additional specs */
};

